################################################################
## Binary Sensor / Dash Buttons
################################################################

- platform: mqtt
  name: dashbutton_bounty
  state_topic: dash-button/bounty
  payload_on: 'active'
  payload_off: 'inactive'

- platform: mqtt
  name: dashbutton_dixie
  state_topic: dash-button/dixie
  payload_on: 'active'
  payload_off: 'inactive'

- platform: mqtt
  name: dashbutton_finish
  state_topic: dash-button/finish
  payload_on: 'active'
  payload_off: 'inactive'

- platform: mqtt
  name: dashbutton_gatorade
  state_topic: dash-button/gatorade
  payload_on: 'active'
  payload_off: 'inactive'

- platform: mqtt
  name: dashbutton_hefty
  state_topic: dash-button/hefty
  payload_on: 'active'
  payload_off: 'inactive'

- platform: mqtt
  name: dashbutton_kraft
  state_topic: dash-button/kraft
  payload_on: 'active'
  payload_off: 'inactive'

- platform: mqtt
  name: dashbutton_playdoh
  state_topic: dash-button/playdoh
  payload_on: 'active'
  payload_off: 'inactive'

- platform: mqtt
  name: dashbutton_quaker
  state_topic: dash-button/quaker
  payload_on: 'active'
  payload_off: 'inactive'

- platform: mqtt
  name: dashbutton_tide
  state_topic: dash-button/tide
  payload_on: 'active'
  payload_off: 'inactive'

- platform: mqtt
  name: dashbutton_ziploc
  state_topic: dash-button/ziploc
  payload_on: 'active'
  payload_off: 'inactive'
