################################################################
## Binary Sensor / Occupancy
################################################################

- platform: mqtt
  name: occupancy_test
  state_topic: home-assistant/occupancy/occupancy_test
  payload_on: 'on'
  payload_off: 'off'
  sensor_class: occupancy
