# Description:
#   Restart Homebridge on Home Assistant startup
#
# Written for:
#   @aptonline
#
# Components:
#   automation
#   shell_command
#
# License:
#   MIT
#
# Author:
#   Dale Higgs <@dale3h>
#
# PLEASE NOTE: THIS CONFIGURATION IS UNTESTED AND MAY CONTAIN ERRORS

automation:
  - alias: restart_homebridge
    trigger:
      - platform: event
        event_type: homeassistant_start
    action:
      - delay: '00:01:00'
      - service: shell_command.restart_homebridge

shell_command:
  restart_homebridge: 'sudo su pi -c "pm2 restart homebridge"'
  start_homebridge: 'sudo su pi -c "pm2 start homebridge"'
  stop_homebridge: 'sudo su pi -c "pm2 stop homebridge"'
