sensor:
  - platform: template
    sensors:
      open_windows:
        value_template: >-
          {%- set open = 0 -%}
          {%- set open = open + (1 if is_state('binary_sensor.window1', 'on') else 0) -%}
          {%- set open = open + (1 if is_state('binary_sensor.window2', 'on') else 0) -%}
          {%- set open = open + (1 if is_state('binary_sensor.window3', 'on') else 0) -%}
          {%- set open = open + (1 if is_state('binary_sensor.window4', 'on') else 0) -%}
          {%- set open = open + (1 if is_state('binary_sensor.window5', 'on') else 0) -%}
          {%- set open = open + (1 if is_state('binary_sensor.window6', 'on') else 0) -%}
          {{ open }}
