################################################################
## Configuration
################################################################

homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  time_zone: America/Chicago
  unit_system: imperial
  customize: !include customize.yaml
  packages: !include_dir_named packages

config:
conversation:
# discovery:
history:
python_script:

frontend:
  themes: !include_dir_named themes
