################################################################
## Configuration
################################################################

homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  time_zone: America/Chicago
  unit_system: imperial
  packages: !include_dir_named packages

config:
conversation:
# discovery:
frontend:
history:
python_script:
sun:
