################################################################
## Configuration
################################################################

homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  time_zone: America/Chicago
  unit_system: imperial
  customize: !include customize.yaml
  packages: !include_dir_named packages

config:
frontend:
history:
sun:
updater:

################################################
## Components (Non-Includes)
################################################

alarm_control_panel:
  - platform: manual
    name: alarm_system
    code: !secret alarm_code

apcupsd:

# telegram:
#   api_key: !secret telegram_bot_key
#   chat_ids: !secret telegram_chat_id
#   users: dale3h
#   admins: dale3h

ecobee:
  api_key: !secret ecobee_api_key
  hold_temp: true

ffmpeg:

http:
  api_password: !secret http_api_password
  base_url: !secret http_base_url
  use_x_forwarded_for: true
  ip_ban_enabled: true
  login_attempts_threshold: 5

influxdb:
  host: !secret influxdb_host
  port: !secret influxdb_port
  username: !secret influxdb_username
  password: !secret influxdb_password
  database: !secret influxdb_database

logbook:
  exclude:
    entities:
      - sensor.time
      - sensor.date
      - sensor.ups_status_date
    domains:
      - sun

# Log Severities: notset, debug, info, warn, warning, error, fatal, critical
logger:
  default: info
  logs:
    homeassistant.components.sensor.apcupsd: error
#     homeassistant.components.climate.ecobee: warn
#     homeassistant.components.sensor.command_line: warn
#     homeassistant.components.device_tracker.asuswrt: warn
#     homeassistant.components.discovery: warn
#     homeassistant.components.ecobee: warn
#     homeassistant.components.http: warn
#     homeassistant.components.sensor.yweather: warn
#     homeassistant.components.notify.telegram: warn
#     homeassistant.components.zone: warn
#     homeassistant.components.zwave: error
#     homeassistant.core: warn
#     phue: warn
#     plexapi: warn

mqtt:
  broker: !secret mqtt_broker
  port: !secret mqtt_port
  username: !secret mqtt_username
  password: !secret mqtt_password

tts:
  - platform: google

xiaomi:
  gateways:
    - sid: !secret xiaomi_gateway_sid
      key: !secret xiaomi_gateway_key

# zigbee:
#   device: /dev/ttyUSB0
#   baud: 9600

zwave:
  usb_path: /dev/ttyACM0
  config_path: /etc/homeassistant/config
  device_config: !include zwave_device_config.yaml

################################################
## Component Includes (Single File)
################################################

# emulated_hue: !include emulated_hue.yaml
ios: !include ios.yaml
recorder: !include recorder.yaml

################################################
## Component Includes (Named)
################################################

# alexa:
#   intents: !include_dir_named alexa

################################################
## Component Includes (Merge List)
################################################

automation: !include_dir_merge_list automation
# binary_sensor: !include_dir_merge_list binary_sensor
cover: !include_dir_merge_list cover
device_tracker: !include_dir_merge_list device_tracker
light: !include_dir_merge_list light
media_player: !include_dir_merge_list media_player
notify: !include_dir_merge_list notify
sensor: !include_dir_merge_list sensor
switch: !include_dir_merge_list switch
zone: !include_dir_merge_list zone

################################################
## Component Includes (Merge Named)
################################################

group: !include_dir_merge_named group
input_boolean: !include_dir_merge_named input_boolean
# input_select: !include_dir_merge_named input_select
input_slider: !include_dir_merge_named input_slider
panel_iframe: !include_dir_merge_named panel_iframe
script: !include_dir_merge_named script
shell_command: !include_dir_merge_named shell_command
