################################################################
## Configuration
################################################################

homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  time_zone: America/Chicago
  unit_system: imperial
  customize: !include customize.yaml
  packages: !include_dir_named packages

frontend:
history:
logbook:
sun:
updater:

################################################
## Components (Non-Includes)
################################################

alarm_control_panel:
  platform: manual
  name: alarm_system
  code: !secret alarm_code

apcupsd:

# telegram:
#   api_key: !secret telegram_bot_key
#   chat_ids: !secret telegram_chat_id
#   users: dale3h
#   admins: dale3h

ecobee:
  api_key: !secret ecobee_api_key
  hold_temp: true

http:
  api_password: !secret http_api_password

# Log Severities: notset, debug, info, warn, warning, error, fatal, critical
logger:
  default: info
#   logs:
#     homeassistant.components.climate.ecobee: warn
#     homeassistant.components.sensor.command_line: warn
#     homeassistant.components.device_tracker.asuswrt: warn
#     homeassistant.components.discovery: warn
#     homeassistant.components.ecobee: warn
#     homeassistant.components.http: warn
#     homeassistant.components.sensor.apcupsd: error
#     homeassistant.components.sensor.yweather: warn
#     homeassistant.components.notify.telegram: warn
#     homeassistant.components.zone: warn
#     homeassistant.components.zwave: error
#     homeassistant.core: warn
#     phue: warn
#     plexapi: warn
#     pyicloud.base: debug

mqtt:
  broker: !secret mqtt_broker
  port: !secret mqtt_port
  username: !secret mqtt_username
  password: !secret mqtt_password

recorder:
  purge_days: 7

tts:
  - platform: google

zwave:
  usb_path: /dev/ttyACM0
  config_path: /usr/local/lib/python3.4/dist-packages/libopenzwave-0.3.1-py3.4-linux-armv7l.egg/config
  polling_interval: 60000

################################################
## Component Includes (Single File)
################################################

# emulated_hue: !include emulated_hue.yaml
ios: !include ios.yaml

################################################
## Component Includes (Named)
################################################

# alexa:
#   intents: !include_dir_named alexa

################################################
## Component Includes (Merge List)
################################################

automation: !include_dir_merge_list automation
binary_sensor: !include_dir_merge_list binary_sensor
# camera: !include_dir_merge_list camera
cover: !include_dir_merge_list cover
device_tracker: !include_dir_merge_list device_tracker
light: !include_dir_merge_list light
media_player: !include_dir_merge_list media_player
notify: !include_dir_merge_list notify
sensor: !include_dir_merge_list sensor
switch: !include_dir_merge_list switch
zone: !include_dir_merge_list zone

################################################
## Component Includes (Merge Named)
################################################

group: !include_dir_merge_named group
input_boolean: !include_dir_merge_named input_boolean
input_select: !include_dir_merge_named input_select
input_slider: !include_dir_merge_named input_slider
# panel_iframe: !include_dir_merge_named panel_iframe
script: !include_dir_merge_named script
shell_command: !include_dir_merge_named shell_command
