################################################################
## Configuration
################################################################

homeassistant:
  name: Home
  latitude: !env_var HOMEASSISTANT_LATITUDE
  longitude: !env_var HOMEASSISTANT_LONGITUDE
  elevation: !env_var HOMEASSISTANT_ELEVATION
  time_zone: America/Chicago
  unit_system: imperial
  customize: !include customize.yaml

conversation:
# discovery:
frontend:
history:
logbook:
sun:
updater:

################################################
## Components (Non-Includes)
################################################

telegram:
  api_key: !env_var TELEGRAM_BOT_KEY
  chat_ids: !env_var TELEGRAM_CHAT_ID
  users: dale3h
  admins: dale3h

ecobee:
  api_key: !env_var ECOBEE_API_KEY
  hold_temp: true

http:
  api_password: !env_var HTTP_API_PASSWORD

ifttt:
  key: !env_var IFTTT_KEY

mqtt:
  broker: !env_var MQTT_BROKER
  port: !env_var MQTT_PORT
  username: !env_var MQTT_USERNAME
  password: !env_var MQTT_PASSWORD

recorder:
  purge_days: 7

################################################
## Component Includes (Single File)
################################################

logger: !include logger.yaml
zwave: !include zwave.yaml
icloud: !include icloud.yaml

################################################
## Component Includes (Named)
################################################

alexa:
  intents: !include_dir_named alexa

################################################
## Component Includes (Merge List)
################################################

automation: !include_dir_merge_list automation
binary_sensor: !include_dir_merge_list binary_sensor
camera: !include_dir_merge_list camera
device_tracker: !include_dir_merge_list device_tracker
garage_door: !include_dir_merge_list garage_door
light: !include_dir_merge_list light
media_player: !include_dir_merge_list media_player
notify: !include_dir_merge_list notify
scene: !include_dir_merge_list scene
sensor: !include_dir_merge_list sensor
switch: !include_dir_merge_list switch
zone: !include_dir_merge_list zone

################################################
## Component Includes (Merge Named)
################################################

group: !include_dir_merge_named group
input_boolean: !include_dir_merge_named input_boolean
# input_select: !include_dir_merge_named input_select
# input_slider: !include_dir_merge_named input_slider
script: !include_dir_merge_named script
shell_command: !include_dir_merge_named shell_command
