################################################################
## Z-Wave / Device Config
################################################################

################################################
## Front Door Lock
################################################

sensor.front_door_alarm_level_2:
  ignored: true

sensor.front_door_alarm_type_2:
  ignored: true

################################################
## Front Door Sensor
################################################

sensor.front_door_access_control:
  ignored: true

sensor.front_door_alarm_level:
  ignored: true

sensor.front_door_alarm_type:
  ignored: true

sensor.front_door_burglar:
  ignored: true

sensor.front_door_sourcenodeid:
  ignored: true

################################################
## Kitchen Motion Sensor
################################################

sensor.kitchen_alarm_level:
  ignored: true

sensor.kitchen_alarm_type:
  ignored: true

sensor.kitchen_burglar:
  ignored: true

sensor.kitchen_general:
  ignored: true

sensor.kitchen_power:
  ignored: true

sensor.kitchen_sourcenodeid:
  ignored: true

sensor.kitchen_ultraviolet:
  ignored: true

################################################
## Master Bathroom Motion Sensor
################################################

sensor.master_bathroom_alarm_level:
  ignored: true

sensor.master_bathroom_alarm_type:
  ignored: true

sensor.master_bathroom_burglar:
  ignored: true

sensor.master_bathroom_sourcenodeid:
  ignored: true

sensor.master_bathroom_ultraviolet:
  ignored: true
