################################################################
## Packages / Low Battery SMS
################################################################

homeassistant:
  customize:
    automation.low_battery_sms_ac:
      friendly_name: "Geraldine's Low Battery SMS AC"

    automation.low_battery_sms_al:
      friendly_name: "Geraldine's Low Battery SMS AL"

    automation.low_battery_sms_hc:
      friendly_name: "Geraldine's Low Battery SMS HC"

    automation.low_battery_sms_jc:
      friendly_name: "Geraldine's Low Battery SMS JC"

    automation.low_battery_sms_lo:
      friendly_name: "Geraldine's Low Battery SMS LO"

    automation.low_battery_sms_st:
      friendly_name: "Geraldine's Low Battery SMS ST"

    automation.low_battery_sms_thip:
      friendly_name: "Geraldine's Low Battery SMS THIP"

    automation.low_battery_sms_thph:
      friendly_name: "Geraldine's Low Battery SMS THPH"

    automation.low_battery_sms_vs:
      friendly_name: "Geraldine's Low Battery SMS VS"

automation:
  - alias: low_battery_sms_ac
    trigger:
      - platform: numeric_state
        entity_id: sensor.geraldine_iphone_battery
        below: 30
    condition:
      - condition: template
        value_template: "{{ is_state('device_tracker.24920e90c74e', 'home') }}"
      - condition: template
        value_template: '{{ states.device_tracker.geraldine.attributes.battery|int < 30 }}'
    action:
      - service: shell_command.low_charge_sms_ac

  - alias: low_battery_sms_al
    trigger:
      - platform: numeric_state
        entity_id: sensor.geraldine_iphone_battery
        below: 30
    condition:
      - condition: template
        value_template: "{{ is_state('device_tracker.485073520650', 'home') }}"
      - condition: template
        value_template: '{{ states.device_tracker.geraldine.attributes.battery|int < 30 }}'
    action:
      - service: shell_command.low_charge_sms_al

  - alias: low_battery_sms_hc
    trigger:
      - platform: numeric_state
        entity_id: sensor.geraldine_iphone_battery
        below: 30
    condition:
      - condition: template
        value_template: "{{ is_state('device_tracker.b853ac55151d', 'home') }}"
      - condition: template
        value_template: '{{ states.device_tracker.geraldine.attributes.battery|int < 30 }}'
    action:
      - service: shell_command.low_charge_sms_hc

  - alias: low_battery_sms_jc
    trigger:
      - platform: numeric_state
        entity_id: sensor.geraldine_iphone_battery
        below: 30
    condition:
      - condition: template
        value_template: "{{ is_state('device_tracker.48e9f19b270b', 'home') }}"
      - condition: template
        value_template: '{{ states.device_tracker.geraldine.attributes.battery|int < 30 }}'
    action:
      - service: shell_command.low_charge_sms_jc

  - alias: low_battery_sms_lo
    trigger:
      - platform: numeric_state
        entity_id: sensor.geraldine_iphone_battery
        below: 30
    condition:
      - condition: template
        value_template: "{{ is_state('device_tracker.d8c46ab751cc', 'home') }}"
      - condition: template
        value_template: '{{ states.device_tracker.geraldine.attributes.battery|int < 30 }}'
    action:
      - service: shell_command.low_charge_sms_lo

  - alias: low_battery_sms_st
    trigger:
      - platform: numeric_state
        entity_id: sensor.geraldine_iphone_battery
        below: 30
    condition:
      - condition: template
        value_template: "{% if is_state('device_tracker.geraldine', 'home') %}true{% endif %}"
      - condition: template
        value_template: '{{ states.device_tracker.geraldine.attributes.battery|int < 30 }}'
    action:
      - service: shell_command.low_charge_sms_st

  - alias: low_battery_sms_thip
    trigger:
      - platform: numeric_state
        entity_id: sensor.geraldine_iphone_battery
        below: 30
    condition:
      - condition: template
        value_template: "{{ is_state('device_tracker.2078f00df5ec', 'home') }}"
      - condition: template
        value_template: '{{ states.device_tracker.geraldine.attributes.battery|int < 30 }}'
    action:
      - service: shell_command.low_charge_sms_thip

  - alias: low_battery_sms_thph
    trigger:
      - platform: numeric_state
        entity_id: sensor.geraldine_iphone_battery
        below: 30
    condition:
      - condition: template
        value_template: "{{ is_state('device_tracker.1c9148232860', 'home') }}"
      - condition: template
        value_template: '{{ states.device_tracker.geraldine.attributes.battery|int < 30 }}'
    action:
      - service: shell_command.low_charge_sms_thph

  - alias: low_battery_sms_vs
    trigger:
      - platform: numeric_state
        entity_id: sensor.geraldine_iphone_battery
        below: 30
    condition:
      - condition: template
        value_template: "{{ is_state('device_tracker.1c7b2157ef94', 'home') }}"
      - condition: template
        value_template: '{{ states.device_tracker.geraldine.attributes.battery|int < 30 }}'
    action:
      - service: shell_command.low_charge_sms_vs

shell_command:
  low_charge_sms_ac: "sh /home/homeassistant/.homeassistant/shell_scripts/low_charge_ac.sh"
  low_charge_sms_al: "sh /home/homeassistant/.homeassistant/shell_scripts/low_charge_al.sh"
  low_charge_sms_hc: "sh /home/homeassistant/.homeassistant/shell_scripts/low_charge_hc.sh"
  low_charge_sms_jc: "sh /home/homeassistant/.homeassistant/shell_scripts/low_charge_jc.sh"
  low_charge_sms_lo: "sh /home/homeassistant/.homeassistant/shell_scripts/low_charge_lo.sh"
  low_charge_sms_st: "sh /home/homeassistant/.homeassistant/shell_scripts/low_charge_st.sh"
  low_charge_sms_thip: "sh /home/homeassistant/.homeassistant/shell_scripts/low_charge_th.sh"
  low_charge_sms_thph: "sh /home/homeassistant/.homeassistant/shell_scripts/low_charge_th.sh"
  low_charge_sms_vs: "sh /home/homeassistant/.homeassistant/shell_scripts/low_charge_vs.sh"
