automation:
  - alias: x left her purse
    trigger:
      platform: state
      entity_id: binary_sensor.x_purse
      state: 'on'
    condition:
      condition: state
      entity_id: device_tracker.x
      state: 'home'
    action:
      ...
