binary_sensor:
  platform: template
  sensors:
    furnace_above_threshold:
      value_template: '{{ states('sensor.furnace') > 2}}'
      friendly_name: 'Furnace Above Threshold'

automation:
  - trigger:
      platform: state
      entity_id: binary_sensor.furnace_above_threshold
      state: 'on'
      for:
        minutes: 1
    condition:
      ...your condition(s)...
    action:
      ...your actions if threshold is reached for >1 minute...
