# Description:
#   Notify on sensor change if no one is home (using customize)
#
# Written for:
#   @sgauche
#
# Components:
#   automation
#   notify
#
# License:
#   MIT
#
# Author:
#   Dale Higgs <@dale3h>
#
# PLEASE NOTE: THIS CONFIGURATION IS UNTESTED AND MAY CONTAIN ERRORS

################################################################
## Add `notify_change: true` in the customize section to enable
##   notification on an entity.
##
## Example Configuration:
##
## homeassistant:
##   customize:
##     binary_sensor.ecolink_doorwindow_sensor_sensor_5_0:
##       notify_change: true
##
##     binary_sensor.ecolink_doorwindow_sensor_sensor_6_0:
##       notify_change: true
##
##     binary_sensor.ecolink_garage_door_sensor_sensor_3_0:
##       notify_change: true
##
##     binary_sensor.ecobee_occupancy:
##       notify_change: true
##
##     binary_sensor.living_room_occupancy:
##       notify_change: true
##
##     binary_sensor.master_bedroom_occupancy:
##       notify_change: true
##
##     binary_sensor.office_occupancy:
##       notify_change: true
##
##     switch.linear_fs20z_isolated_contact_fixture_module_switch_4_0
##       notify_change: true
##
##     switch.ge_12727_inwall_smart_switch_toggle_switch_7_0
##       notify_change: true
################################################################

automation:
  - alias: notify_sensor_change_away
    trigger:
      - platform: event
        event_type: state_changed
    condition:
      - condition: state
        entity_id: group.all_devices
        state: 'not_home'
      - condition: template
        value_template: "{{ (trigger.event.data is not none) and (trigger.event.data.old_state is not none) and (trigger.event.data.new_state is not none) and (trigger.event.data.new_state.attributes is not none) }}"
      - condition: template
        value_template: "{{ (trigger.event.data.old_state.state == 'off') and (trigger.event.data.new_state.state == 'on') }}"
      - condition: template
        value_template: "{{ trigger.event.data.new_state.attributes.notify_change|default(false, true) }}"
    action:
      - service: notify.html5_scott_phone
        data_template:
          title: "Alarm!"
          message: "The {{ trigger.event.data.new_state.name }} was changed to {{ trigger.event.data.new_state.state }} while no one is home. - {{ as_timestamp(now())|timestamp_custom('%I:%M:%S %p %d%b%Y', true) }}"
