binary_sensor:
  - platform: template
    sensors:
      tank_basking_threshold:
        value_template: "{{ states('sensor.tank_basking')|int <= 80 }}"
        entity_id: sensor.tank_basking

automation:
  - alias: check_bulbs
    trigger:
      - platform: state
        entity_id: binary_sensor.tank_basking_threshold
        state: 'on'
        for:
          minutes: 30
    action:
      - service: notify.sms_billy
        data_template:
          message: "Check basking bulbs! {{ states('sensor.tank_basking') }}"
