################################################################
## Packages / Groups / Automation Override
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'groups/automation_override'

      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

    ################################################
    ## Group
    ################################################

    group.automation_override:
      <<: *customize
      friendly_name: "Automation Override"

################################################
## Group
################################################

group:
  automation_override:
    control: hidden
    entities:
      - automation.sunrise_lighting
      - automation.kitchen_motion
      - automation.laundry_room_motion
      - automation.master_bathroom_motion
      - automation.master_bedroom_motion
      - automation.garage_lighting
      - automation.garage_door_lighting
      - automation.media_lighting
      - input_boolean.shower_mode
