################################################################
## Packages / Groups / Batteries
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'groups/batteries'

      contained: &contained
        <<: *customize
        haaska_hidden: true
        homebridge_hidden: true

      exposed: &exposed
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

      hidden: &hidden
        <<: *contained
        hidden: true

    ################################################
    ## Group
    ################################################

    group.batteries:
      <<: *contained
      friendly_name: "Batteries"

    ################################################
    ## Sensor
    ################################################

    sensor.iphone_battery_level:
      <<: *hidden
      friendly_name: "iPhone Battery Level"
      icon: mdi:battery

    sensor.iphone_battery_state:
      <<: *hidden
      friendly_name: "iPhone Battery State"
      icon: mdi:battery-charging


################################################
## Group
################################################

group:
  batteries:
    control: hidden
    entities:
      - sensor.front_door_lock_battery
      - sensor.front_door_sensor_battery
      - sensor.kitchen_motion_battery
      - sensor.master_bathroom_motion_battery
      - sensor.siren_battery
      - sensor.closet_door_battery
      - sensor.garage_entry_battery
      - sensor.iphone_battery
      - sensor.master_bedroom_battery
      - sensor.parker_closet_door_battery
      - sensor.network_cabinet_battery
      - sensor.ups_battery
