################################################################
## Packages / Groups / Batteries
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'groups/batteries'

      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

    ################################################
    ## Group
    ################################################

    group.batteries:
      <<: *customize
      friendly_name: "Batteries"

    ################################################
    ## Sensor
    ################################################

    sensor.iphone_battery_level:
      <<: *customize
      friendly_name: "iPhone Battery Level"
      hidden: true
      icon: mdi:battery

    sensor.iphone_battery_state:
      <<: *customize
      friendly_name: "iPhone Battery State"
      hidden: true
      icon: mdi:battery-charging

################################################
## Group
################################################

group:
  batteries:
    control: hidden
    entities:
      - sensor.front_door_lock_battery
      - sensor.front_door_sensor_battery
      - sensor.kitchen_motion_battery
      - sensor.master_bathroom_motion_battery
      - sensor.closet_door_battery
      - sensor.garage_entry_battery
      - sensor.iphone_battery
      - sensor.master_bedroom_battery
      - sensor.parker_closet_door_battery
      - sensor.network_cabinet_battery
      - sensor.ups_battery
      - sensor.dining_room_siren_battery
      - sensor.master_bedroom_siren_battery
