################################################################
## Packages / Groups / Media Components
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'groups/media_components'

      contained: &contained
        <<: *customize
        haaska_hidden: true
        homebridge_hidden: true

      exposed: &exposed
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

      hidden: &hidden
        <<: *contained
        hidden: true

    ################################################
    ## Group
    ################################################

    group.media_components:
      <<: *contained
      friendly_name: "Media Components"

    group.media_players:
      <<: *contained
      friendly_name: "Media Players"

################################################
## Group
################################################

group:
  media_components:
    control: hidden
    entities:
      - switch.apple_tv
      - switch.chromecast
      - switch.computer
      - switch.fire_tv
      - switch.xbox

  media_players:
    control: hidden
    entities:
      - media_player.apple_tv_bedroom
      - media_player.apple_tv_living_room
      - media_player.bedroom_speakers
      - media_player.dining_room_home
      - media_player.living_room_speakers
