################################################################
## Packages / Groups / Motion
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'groups/motion'

      contained: &contained
        <<: *customize
        haaska_hidden: true
        homebridge_hidden: true

      exposed: &exposed
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

      hidden: &hidden
        <<: *contained
        hidden: true

    ################################################
    ## Group
    ################################################

    group.motion:
      <<: *contained
      friendly_name: "Motion"

################################################
## Group
################################################

group:
  motion:
    control: hidden
    entities:
      - binary_sensor.master_bathroom_sensor
      - binary_sensor.kitchen_sensor
      - binary_sensor.master_bedroom_motion
      - binary_sensor.amcrest_ptz_cam_motion
      - binary_sensor.backyard_cam_motion
      - binary_sensor.driveway_cam_motion
      - binary_sensor.front_yard_cam_motion
      - binary_sensor.garage_cam_motion
      - binary_sensor.kitchen_cam_motion
      - binary_sensor.living_room_cam_motion
      - binary_sensor.living_room_fd_cam_motion
      - binary_sensor.master_bedroom_cam_motion
      - binary_sensor.parker_bedroom_cam_motion
      - !secret binary_sensor_laundry_room_motion
      - binary_sensor.guest_bathroom_motion
