################################################################
## Packages / Groups / Occupancy
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'groups/occupancy'

      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

    ################################################
    ## Group
    ################################################

    group.occupancy:
      <<: *customize
      friendly_name: "Occupancy"

################################################
## Group
################################################

group:
  occupancy:
    control: hidden
    entities:
      - binary_sensor.master_bedroom_occupancy
      - binary_sensor.guest_bedroom_occupancy
      - binary_sensor.home_occupancy
      - binary_sensor.living_room_occupancy
