################################################################
## Packages / Groups / Occupancy
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'groups/occupancy'

      contained: &contained
        <<: *customize
        haaska_hidden: true
        homebridge_hidden: true

      exposed: &exposed
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

      hidden: &hidden
        <<: *contained
        hidden: true

    ################################################
    ## Group
    ################################################

    group.occupancy:
      <<: *contained
      friendly_name: "Occupancy"

################################################
## Group
################################################

group:
  occupancy:
    control: hidden
    entities:
      - binary_sensor.master_bedroom_occupancy
      - binary_sensor.guest_bedroom_occupancy
      - binary_sensor.home_occupancy
      - binary_sensor.living_room_occupancy
