################################################################
## Packages / Groups / People
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'groups/people'

      exposed: &exposed
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

    ################################################
    ## Device Tracker
    ################################################

    device_tracker.dale_iphone:
      <<: *customize
      friendly_name: "Dale (iPhone)"
      icon: mdi:cellphone-iphone

    device_tracker.dale_iphone_bt:
      <<: *customize
      friendly_name: "Dale (BT)"
      icon: mdi:cellphone-iphone

    device_tracker.dale_iphone_ios:
      <<: *customize
      friendly_name: "Dale (iOS)"
      icon: mdi:cellphone-iphone

    device_tracker.meagan_android:
      <<: *customize
      friendly_name: "Meagan (Android)"
      icon: mdi:cellphone-android

    ################################################
    ## Group
    ################################################

    group.guests:
      <<: *customize
      friendly_name: "Guests"
      icon: mdi:human-male-female

    group.person_dale:
      <<: *customize
      friendly_name: "Dale"
      icon: mdi:human-male

    group.person_meagan:
      <<: *customize
      friendly_name: "Meagan"
      icon: mdi:human-female

################################################
## Group
################################################

group:
  guests:
    control: hidden
    entities:
      - group.person_meagan

  person_dale:
    control: hidden
    entities:
      - device_tracker.dale_iphone
      - device_tracker.dale_iphone_bt
      - device_tracker.dale_iphone_ios

  person_meagan:
    control: hidden
    entities:
      - device_tracker.meagan_android
