################################################################
## Packages / Groups / Rooms
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'groups/rooms'

      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

    ################################################
    ## Group
    ################################################

    group.back_porch:
      <<: *customize
      friendly_name: "Back Porch"

    group.dining_room:
      <<: *customize
      friendly_name: "Dining Room"

    group.entry:
      <<: *customize
      friendly_name: "Entry"

    group.front_porch:
      <<: *customize
      friendly_name: "Front Porch"

    group.garage:
      <<: *customize
      friendly_name: "Garage"

    group.guest_bathroom:
      <<: *customize
      friendly_name: "Guest Bathroom"

    group.guest_bedroom:
      <<: *customize
      friendly_name: "Guest Bedroom"

    group.hallway:
      <<: *customize
      friendly_name: "Hallway"

    group.kitchen:
      <<: *customize
      friendly_name: "Kitchen"

    group.laundry_room:
      <<: *customize
      friendly_name: "Laundry Room"

    group.living_room:
      <<: *customize
      friendly_name: "Living Room"

    group.master_bedroom:
      <<: *customize
      friendly_name: "Master Bedroom"

    group.parker_bedroom:
      <<: *customize
      friendly_name: "Parker Bedroom"

################################################
## Group
################################################

group:
  back_porch:
    control: hidden
    entities:
      - light.back_porch

  dining_room:
    control: hidden
    entities:
      - light.dining_room
      - media_player.dining_room_home
      - switch.siren_switch

  entry:
    control: hidden
    entities:
      - lock.front_door_locked
      - light.entry_lamp
      - light.entry_light
      - binary_sensor.front_door_sensor
      - !secret binary_sensor_doorbell

  front_porch:
    control: hidden
    entities:
      - light.front_porch
      - binary_sensor.front_porch_expected_state
      - input_select.front_porch_time_on
      - input_select.front_porch_time_off
      - script.front_porch_light
      - automation.front_porch_timer

  garage:
    control: hidden
    entities:
      - alert.garage_door_open
      - light.garage_light
      - cover.garage_door
      - binary_sensor.garage_entry_contact
      - sensor.garage_entry_battery
      - sensor.garage_entry_temperature
      - automation.garage_lighting

  guest_bathroom:
    control: hidden
    entities:
      - light.guest_bathroom
      - binary_sensor.guest_bathroom_motion
      - sensor.guest_bathroom_lux
      - sensor.guest_bathroom_temperature

  guest_bedroom:
    control: hidden
    entities:
      - light.guest_bedroom
      - binary_sensor.guest_bedroom_occupancy
      - sensor.guest_bedroom_temperature

  hallway:
    control: hidden
    entities:
      - light.hallway
      - binary_sensor.ecobee3_occupancy
      - sensor.ecobee3_temperature
      - sensor.ecobee3_humidity
      - climate.ecobee3

  kitchen:
    control: hidden
    entities:
      - light.chandelier
      - light.range_light
      - light.sink_light
      - switch.kitchen_overhead
      - sensor.kitchen_motion_battery
      - binary_sensor.kitchen_sensor
      - sensor.kitchen_moisture
      - sensor.kitchen_luminance
      - sensor.kitchen_relative_humidity
      - sensor.kitchen_temperature
      - switch.pepper_fan
      - sensor.pepper_fan_power
      - automation.kitchen_motion

  laundry_room:
    control: hidden
    entities:
      - light.laundry_room
      - automation.laundry_room_motion

  living_room:
    control: hidden
    entities:
      - light.living_room
      - !secret light_gateway_light
      - binary_sensor.living_room_occupancy
      - sensor.living_room_temperature
      - !secret sensor_gateway_lux
      - cover.projector_screen
      - remote.living_room
      - media_player.apple_tv_living_room
      - remote.apple_tv_living_room
      - media_player.living_room_speakers
      - media_player.plex_living_room

  master_bedroom:
    control: hidden
    entities:
      - light.master_bedroom
      - light.master_bathroom
      - light.master_closet
      - light.headboard
      - switch.master_bedroom_siren
      - binary_sensor.master_bedroom_occupancy
      - binary_sensor.master_bedroom_motion
      - binary_sensor.closet_door_contact
      - sensor.master_bedroom_battery
      - sensor.master_bedroom_motion_temperature
      - sensor.master_bedroom_temperature
      - automation.master_bedroom_motion

  parker_bedroom:
    control: hidden
    entities:
      - light.parker_closet
      - binary_sensor.parker_closet_door_contact
      - sensor.parker_closet_door_battery
      - sensor.parker_closet_door_temperature
      - automation.parker_closet_light_off_when_door_is_closed
      - automation.parker_closet_light_on_when_door_is_open
