################################################################
## Packages / Groups / Rooms
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'groups/rooms'

      contained: &contained
        <<: *customize
        haaska_hidden: true
        homebridge_hidden: true

      exposed: &exposed
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

      hidden: &hidden
        <<: *contained
        hidden: true

    ################################################
    ## Group
    ################################################

    group.back_porch:
      <<: *contained
      friendly_name: "Back Porch"

    group.dining_room:
      <<: *contained
      friendly_name: "Dining Room"

    group.entryway:
      <<: *contained
      friendly_name: "Entryway"

    group.front_porch:
      <<: *contained
      friendly_name: "Front Porch"

    group.garage:
      <<: *contained
      friendly_name: "Garage"

    group.guest_bathroom:
      <<: *contained
      friendly_name: "Guest Bathroom"

    group.guest_bedroom:
      <<: *contained
      friendly_name: "Guest Bedroom"

    group.hallway:
      <<: *contained
      friendly_name: "Hallway"

    group.kitchen:
      <<: *contained
      friendly_name: "Kitchen"

    group.laundry_room:
      <<: *contained
      friendly_name: "Laundry Room"

    group.living_room:
      <<: *contained
      friendly_name: "Living Room"

    group.master_bedroom:
      <<: *contained
      friendly_name: "Master Bedroom"

    group.parker_bedroom:
      <<: *contained
      friendly_name: "Parker Bedroom"

################################################
## Group
################################################

group:
  back_porch:
    control: hidden
    entities:
      - light.back_porch

  dining_room:
    control: hidden
    entities:
      - light.dining_room
      - media_player.dining_room_home

  entryway:
    control: hidden
    entities:
      - lock.front_door_locked
      - light.entry_lamp
      - light.entry_light
      - binary_sensor.front_door_sensor
      - !secret binary_sensor_doorbell

  front_porch:
    control: hidden
    entities:
      - light.front_porch
      - binary_sensor.front_porch_expected_state
      - input_select.front_porch_time_on
      - input_select.front_porch_time_off
      - script.front_porch_light
      - automation.front_porch_timer

  garage:
    control: hidden
    entities:
      - alert.garage_door_open
      - light.garage
      - cover.garage_door
      - binary_sensor.garage_entry_contact
      - sensor.garage_entry_battery
      - sensor.garage_entry_temperature
      - automation.garage_lighting

  guest_bathroom:
    control: hidden
    entities:
      - light.guest_bathroom
      - binary_sensor.guest_bathroom_motion
      - sensor.guest_bathroom_lux
      - sensor.guest_bathroom_temperature

  guest_bedroom:
    control: hidden
    entities:
      - light.guest_bedroom
      - binary_sensor.guest_bedroom_occupancy
      - sensor.guest_bedroom_temperature

  hallway:
    control: hidden
    entities:
      - light.hallway
      - binary_sensor.home_occupancy
      - sensor.home_temperature
      - sensor.home_humidity
      - climate.home

  kitchen:
    control: hidden
    entities:
      - light.chandelier
      - light.range
      - light.sink
      - switch.kitchen_overhead
      - sensor.kitchen_motion_battery
      - binary_sensor.kitchen_sensor
      - sensor.kitchen_moisture
      - sensor.kitchen_luminance
      - sensor.kitchen_relative_humidity
      - sensor.kitchen_temperature
      - switch.pepper_fan
      - sensor.pepper_fan_power
      - automation.kitchen_motion

  laundry_room:
    control: hidden
    entities:
      - light.laundry_room
      - automation.laundry_room_motion

  living_room:
    control: hidden
    entities:
      - light.living_room
      - binary_sensor.living_room_occupancy
      - sensor.living_room_temperature
      - remote.living_room
      - media_player.apple_tv_living_room
      - media_player.living_room_speakers
      - media_player.plex_living_room

  master_bedroom:
    control: hidden
    entities:
      - light.master_bedroom
      - light.master_bathroom
      - light.master_closet
      - binary_sensor.master_bedroom_occupancy
      - binary_sensor.master_bedroom_motion
      - binary_sensor.closet_door_contact
      - sensor.master_bedroom_battery
      - sensor.master_bedroom_motion_temperature
      - sensor.master_bedroom_temperature
      - automation.master_bedroom_motion

  parker_bedroom:
    control: hidden
    entities:
      - light.parker_lamp
      - light.parker_closet
      - binary_sensor.parker_closet_door_contact
      - sensor.parker_closet_door_battery
      - sensor.parker_closet_door_temperature
      - automation.parker_closet_light_off_when_door_is_closed
      - automation.parker_closet_light_on_when_door_is_open
