################################################################
## Packages / Groups / Temperature
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'groups/temperature'

      exposed: &exposed
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

    ################################################
    ## Group
    ################################################

    group.temperature:
      <<: *customize
      friendly_name: "Temperature"
      icon: mdi:thermometer

################################################
## Group
################################################

group:
  temperature:
    control: hidden
    entities:
      - sensor.closet_door_temperature
      - sensor.garage_entry_temperature
      - sensor.guest_bedroom_temperature
      - sensor.guest_bathroom_temperature
      - sensor.home_temperature
      - sensor.kitchen_temperature
      - sensor.living_room_temperature
      - sensor.master_bathroom_temperature
      - sensor.master_bedroom_motion_temperature
      - sensor.master_bedroom_temperature
      - sensor.network_cabinet_temperature
      - sensor.parker_closet_door_temperature
      - sensor.broadlink_sensor_temperature

      - sensor.home_humidity
      - sensor.kitchen_relative_humidity
      - sensor.master_bathroom_relative_humidity
