- alias: "iCloud Interval 1min if Fi's nmap away and iCloud home"
  trigger:
    - platform: state
      entity_id: device_tracker.fiona_nmap
      state: 'not_home'
  condition:
    - condition: state
      entity_id: device_tracker.fisphone
      state: 'home'
    - condition: state
      entity_id: device_tracker.jhayes_htcm8
      state: 'not_home'
  action:
    - service: icloud.setinterval
      data:
        accountname: 'Justin'
        interval: 1

- alias: "iCloud Interval 30min if Fi's nmap home and iCloud home and interval < 30"
  trigger:
    - platform: state
      entity_id: device_tracker.fiona_nmap
      state: 'home'
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: device_tracker.fisphone
      state: 'home'
    - condition: numeric_state
      entity_id: idevice.fisphone
      below: 30
  action:
    - service: icloud.setinterval
      data:
        accountname: 'Justin'
        interval: 30
