################################################################
## Light
################################################################

################################################
## Philips Hue
################################################

- platform: hue
  host: !secret hue_host
  allow_unreachable: true
  filename: phue.conf

################################################
## LimitlessLED
################################################

- platform: limitlessled
  bridges:
    - host: !secret limitlessled_host
      version: 5
      port: 8899
      groups:
      - number: 1
        type: rgbw
        name: garage

################################################
## Flux LED / MagicLight
################################################

- platform: flux_led
  devices:
    !secret flux_led_rack_light_host:
      name: rack_light
      protocol: 'ledenet'
      mode: 'rgb'
