################################################################
## Packages / Secrets Container
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'secrets_container'

      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

    ################################################
    ## Sensor
    ################################################

    sensor.secrets:
      <<: *customize
      friendly_name: "Secrets"
      hidden: true
      icon: mdi:file-lock
      eventghost_url: !secret eventghost_url
      secret_of_yours: !secret secret_of_yours
      secret_of_mine: !secret secret_of_mine

################################################
## Sensor
################################################

sensor:
  - platform: template
    sensors:
      secrets:
        value_template: "Secrets Container"
