### Example using `automation`

```yaml
automation:
  - alias: Conditional Action (Simple)
    trigger:
      - platform: state
        entity_id: device_tracker.device1, device_tracker.device2
        to: 'not_home'
    action:
      - service: notify.telegram
        data_template:
          message: >
            {% if trigger.entity_id == 'device_tracker.device1' %}
              Device 1 is away.
            {% elif trigger.entity_id == 'device_tracker.device2' %}
              Device 2 is away.
            {% endif %}
```

### Example using `automation` and `script`

```yaml
automation:
  - alias: Conditional Action (Advanced)
    trigger:
      - platform: state
        entity_id: device_tracker.device1, device_tracker.device2
        to: 'not_home'
    action:
      - service_template: "script.{{ trigger.entity_id.split('.', 1)[1] }}_is_away"

script:
  device1_is_away:
    name: Device 1 is Away
    sequence:
      - service: notify.telegram
        data:
          message: Device 1 has left the building.
      - service: light.turn_off
        entity_id: light.kitchen

  device2_is_away:
    name: Device 2 is Away
    sequence:
      - service: notify.telegram
        data:
          message: Device 2 went bye-bye!
      - service: climate.set_away_mode
        data:
          entity_id: climate.home
          away_mode: true
```
