################################################################
## MiLight Color Selector (Long Work-around)
## See http://www.tayloredmktg.com/rgb/ for more RGB values
################################################################

input_select:
  milight_color:
    name: MiLight Color
    initial: White
    icon: mdi:lightbulb
    options:
      - White
      - Red
      - Orange
      - Yellow
      - Green
      - Blue
      - Indigo
      - Violet

automation:
#   - trigger:
#       platform: state
#       entity_id: input_select.milight_color
#     action:
#       service: light.turn_on
#       data_template:
#         entity_id: light.master_bedroom_1, light.master_bedroom_2
#         brightness: 255
#         rgb_color: >
#           {%- if states('input_select.milight_color') == 'White' -%}
#             [255, 255, 255]
#           {%- elif states('input_select.milight_color') == 'Red' -%}
#             [255, 0, 0]
#           {%- elif states('input_select.milight_color') == 'Orange' -%}
#             [255, 165, 0]
#           {%- elif states('input_select.milight_color') == 'Yellow' -%}
#             [255, 255, 0]
#           {%- elif states('input_select.milight_color') == 'Green' -%}
#             [0, 255, 0]
#           {%- elif states('input_select.milight_color') == 'Blue' -%}
#             [0, 0, 255]
#           {%- elif states('input_select.milight_color') == 'Indigo' -%}
#             [75, 0, 130]
#           {%- elif states('input_select.milight_color') == 'Violet' -%}
#             [238, 130, 238]
#           {%- endif -%}


  - trigger:
      platform: state
      entity_id: input_select.milight_color
      to: 'White'
    action:
      service: light.turn_on
      data:
        entity_id: light.your_light_here
        brightness: 255
        rgb_color: [255, 255, 255]

  - trigger:
      platform: state
      entity_id: input_select.milight_color
      to: 'Red'
    action:
      service: light.turn_on
      data:
        entity_id: light.your_light_here
        brightness: 255
        rgb_color: [255, 0, 0]

  - trigger:
      platform: state
      entity_id: input_select.milight_color
      to: 'Orange'
    action:
      service: light.turn_on
      data:
        entity_id: light.your_light_here
        brightness: 255
        rgb_color: [255, 165, 0]

  - trigger:
      platform: state
      entity_id: input_select.milight_color
      to: 'Yellow'
    action:
      service: light.turn_on
      data:
        entity_id: light.your_light_here
        brightness: 255
        rgb_color: [255, 255, 0]

  - trigger:
      platform: state
      entity_id: input_select.milight_color
      to: 'Green'
    action:
      service: light.turn_on
      data:
        entity_id: light.your_light_here
        brightness: 255
        rgb_color: [0, 255, 0]

  - trigger:
      platform: state
      entity_id: input_select.milight_color
      to: 'Blue'
    action:
      service: light.turn_on
      data:
        entity_id: light.your_light_here
        brightness: 255
        rgb_color: [0, 0, 255]

  - trigger:
      platform: state
      entity_id: input_select.milight_color
      to: 'Indigo'
    action:
      service: light.turn_on
      data:
        entity_id: light.your_light_here
        brightness: 255
        rgb_color: [75, 0, 130]

  - trigger:
      platform: state
      entity_id: input_select.milight_color
      to: 'Violet'
    action:
      service: light.turn_on
      data:
        entity_id: light.your_light_here
        brightness: 255
        rgb_color: [238, 130, 238]
