################################################################
## Configuration
################################################################

homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  time_zone: America/Chicago
  unit_system: imperial
  customize: !include customize.yaml

frontend:
history:
logbook:
sun:
updater:

emulated_hue:
  host_ip: 192.168.1.186
  exposed_domains:
    - script

http:
  api_password: !secret http_api_password

script: !include script.yaml
shell_command: !include shell_command.yaml
