################################################################
## Switch / Digital Loggers
################################################################

- platform: digitalloggers
  name: rack
  host: !secret digitalloggers_host
  password: !secret digitalloggers_password
