################################################################
## Switch / Harmony Hub
################################################################

- platform: mqtt
  name: fire_tv
  state_topic: harmony-api/hubs/harmony-hub/activities/watch-fire-tv/state
  command_topic: harmony-api/hubs/harmony-hub/activities/watch-fire-tv/command
  payload_on: 'on'
  payload_off: 'off'
