################################################################
## Switch / MQTT Variables
################################################################

- platform: mqtt
  name: sunrise_lighting
  state_topic: home-assistant/variable/sunrise_lighting
  command_topic: home-assistant/variable/sunrise_lighting
  payload_on: 'on'
  payload_off: 'off'
  retain: true

- platform: mqtt
  name: master_bedroom_motion
  state_topic: home-assistant/variable/master_bedroom_motion
  command_topic: home-assistant/variable/master_bedroom_motion
  payload_on: 'on'
  payload_off: 'off'
  retain: true

- platform: mqtt
  name: master_bathroom_motion
  state_topic: home-assistant/variable/master_bathroom_motion
  command_topic: home-assistant/variable/master_bathroom_motion
  payload_on: 'on'
  payload_off: 'off'
  retain: true

- platform: mqtt
  name: kitchen_motion
  state_topic: home-assistant/variable/kitchen_motion
  command_topic: home-assistant/variable/kitchen_motion
  payload_on: 'on'
  payload_off: 'off'
  retain: true

- platform: mqtt
  name: shower_mode
  state_topic: home-assistant/variable/shower_mode
  command_topic: home-assistant/variable/shower_mode
  payload_on: 'on'
  payload_off: 'off'
  retain: true
