automation:
  - alias: Turn on lights when sun sets
    trigger:
      platform: sun
      event: sunset
      offset: '+00:30:00'
    action:
      service: switch.turn_on
      entity_id: switch.front_port_lights_switch_2, switch.back_yard_lights_switch_4, switch.driveway_lights_switch_3

  - alias: Turn off lights when sun rises
    trigger:
      platform: sun
      event: sunrise
      offset: '-01:00:00'
    action:
      service: switch.turn_off
      entity_id: switch.front_port_lights_switch_2, switch.back_yard_lights_switch_4, switch.driveway_lights_switch_3
