automation:
  alias: Turn Zone 1 On
  trigger:
    platform: time
    after: '07:30:00'
  action:
    service: script.zone_1_on

script:
  zone_1_on:
    alias: Zone 1 On
    sequence:
      - service: switch.turn_on
        entity_id: switch.zone_1
      - service: script.zone_1_timer_5m
      - service: script.zone_1_timer_10m
      - service: script.zone_1_timer_15m
      - service: script.zone_1_timer_20m
      - service: script.zone_1_timer_25m
      - service: script.zone_1_timer_30m

  zone_1_off:
    alias: Zone 1 Off
    sequence:
      - service: script.turn_off
        entity_id: script.zone_1_timer_5m
      - service: script.turn_off
        entity_id: script.zone_1_timer_10m
      - service: script.turn_off
        entity_id: script.zone_1_timer_15m
      - service: script.turn_off
        entity_id: script.zone_1_timer_20m
      - service: script.turn_off
        entity_id: script.zone_1_timer_25m
      - service: script.turn_off
        entity_id: script.zone_1_timer_30m
      - service: switch.turn_off
        entity_id: switch.zone_1

  zone_1_timer_5m:
    alias: Zone 1 Timer (5 Minutes)
    sequence:
      - condition: state
        entity_id: input_select.zone_1_time_on
        state: '00:05'
      - delay:
          minutes: 5
      - service: script.zone_1_off

  zone_1_timer_10m:
    alias: Zone 1 Timer (10 Minutes)
    sequence:
      - condition: state
        entity_id: input_select.zone_1_time_on
        state: '00:10'
      - delay:
          minutes: 10
      - service: script.zone_1_off

  zone_1_timer_15m:
    alias: Zone 1 Timer (15 Minutes)
    sequence:
      - condition: state
        entity_id: input_select.zone_1_time_on
        state: '00:15'
      - delay:
          minutes: 15
      - service: script.zone_1_off

  zone_1_timer_20m:
    alias: Zone 1 Timer (20 Minutes)
    sequence:
      - condition: state
        entity_id: input_select.zone_1_time_on
        state: '00:20'
      - delay:
          minutes: 20
      - service: script.zone_1_off

  zone_1_timer_25m:
    alias: Zone 1 Timer (25 Minutes)
    sequence:
      - condition: state
        entity_id: input_select.zone_1_time_on
        state: '00:25'
      - delay:
          minutes: 25
      - service: script.zone_1_off

  zone_1_timer_30m:
    alias: Zone 1 Timer (30 Minutes)
    sequence:
      - delay:
          minutes: 30
      - service: script.zone_1_off
