automation:
  - alias: This triggers at 5am every Tuesday
    trigger:
      - platform: time
        after: '05:00:00'
    condition:
      - condition: time
        weekday:
          - tue
    action:
      - service: notify.telegram
        data:
          message: It is 5am on Tuesday!
