################################################
## Bulky!
################################################

# shell_command:
#   marantz_main_power_on: curl -X GET http://192.168.1.120/MainZone/index.put.asp?cmd0=PutSystem_OnStandby%2FON&cmd1=aspMainZone_WebUpdateStatus%2F
#   marantz_main_power_off: curl -X GET http://192.168.1.120/MainZone/index.put.asp?cmd0=PutSystem_OnStandby%2FSTANDBY&cmd1=aspMainZone_WebUpdateStatus%2F
#   marantz_main_mute_on: curl -X GET http://192.168.1.120/MainZone/index.put.asp?cmd0=PutVolumeMute%2Fon&cmd1=aspMainZone_WebUpdateStatus%2F
#   marantz_main_mute_off: curl -X GET http://192.168.1.120/MainZone/index.put.asp?cmd0=PutVolumeMute%2Fon&cmd1=aspMainZone_WebUpdateStatus%2F
#   marantz_main_vol_up: curl -X GET http://192.168.1.120/MainZone/index.put.asp?cmd0=PutMasterVolumeBtn%2F%3C
#   marantz_main_vol_down: curl -X GET http://192.168.1.120/MainZone/index.put.asp?cmd0=PutMasterVolumeBtn%2F%3E
#   marantz_main_input_bd: curl -X GET http://192.168.1.120/MainZone/index.put.asp?cmd0=PutZone_InputFunction%2FBD&cmd1=aspMainZone_WebUpdateStatus%2F
#   marantz_main_input_cd: curl -X GET http://192.168.1.120/MainZone/index.put.asp?cmd0=PutZone_InputFunction%2FCD&cmd1=aspMainZone_WebUpdateStatus%2F
#   marantz_main_input_dvd: curl -X GET http://192.168.1.120/MainZone/index.put.asp?cmd0=PutZone_InputFunction%2FDVD&cmd1=aspMainZone_WebUpdateStatus%2F

################################################
## Ahhh, much better :)
################################################

shell_command:
  marantz_main_power: "curl -X GET 'http://192.168.1.120/MainZone/index.put.asp?cmd0=PutSystem_OnStandby%2F{{ state|upper }}&cmd1=aspMainZone_WebUpdateStatus%2F'"
  marantz_main_mute: "curl -X GET 'http://192.168.1.120/MainZone/index.put.asp?cmd0=PutVolumeMute%2F{{ state|lower }}&cmd1=aspMainZone_WebUpdateStatus%2F'"
  marantz_main_input: "curl -X GET 'http://192.168.1.120/MainZone/index.put.asp?cmd0=PutZone_InputFunction%2F{{ source|upper }}&cmd1=aspMainZone_WebUpdateStatus%2F'"
  marantz_main_vol: "curl -X GET 'http://192.168.1.120/MainZone/index.put.asp?cmd0={% if volume is number %}PutMasterVolumeSet{% else %}PutMasterVolumeBtn{% endif %}%2F{% if volume is number %}{{ volume }}{% elseif volume|lower == 'up' %}%3C{% else %}%3E{% endif %}"

################################################
## Zone Support
################################################

shell_command:
  marantz_power: "curl -X GET 'http://192.168.1.120/MainZone/index.put.asp?cmd0=PutZone_OnOff%2F{{ state|upper }}&cmd1=aspMainZone_WebUpdateStatus%2F{% if zone is defined %}&ZoneName={{ zone|upper }}{% endif %}"
  marantz_volume: "curl -X GET 'http://192.168.1.120/MainZone/index.put.asp?cmd0={% if volume is number %}PutMasterVolumeSet{% else %}PutMasterVolumeBtn{% endif %}%2F{% if volume is number %}{{ volume }}{% elseif volume|lower == 'up' %}%3C{% else %}%3E{% endif %}{% if zone is defined %}&ZoneName={{ zone|upper }}{% endif %}"

################################################
## Usage Examples
################################################

automation:
  - alias: Input Boolean for Marantz Power
    trigger:
      platform: state
      entity_id: input_boolean.marantz_power
    action:
      service: shell_command.marantz_main_power
      data_template:
        state: "{{ states('input_boolean.marantz_power') }}"

  - alias: Input Boolean for Marantz Mute
    trigger:
      platform: state
      entity_id: input_boolean.marantz_mute
    action:
      service: shell_command.marantz_main_mute
      data_template:
        state: "{{ states('input_boolean.marantz_mute') }}"

  - alias: Input Select for Marantz Source
    trigger:
      platform: state
      entity_id: input_select.marantz_input
    action:
      service: shell_command.marantz_main_input
      data_template:
        source: "{{ states('input_select.marantz_input') }}"

  - alias: Input Slider for Marantz Volume
    trigger:
      platform: state
      entity_id: input_slider.marantz_volume
    action:
      service: shell_command.marantz_main_vol
      data_template:
        volume: "{{ states('input_slider.marantz_volume') }}"

script:
  marantz_volume_up:
    sequence:
      - service: shell_command.marantz_main_vol
        data:
          volume: 'up'

  marantz_volume_down:
    sequence:
      - service: shell_command.marantz_main_vol
        data:
          volume: 'down'

################################################
## Zone Examples
################################################

automation:
  - alias: Input Slider for Marantz Main Volume
    trigger:
      platform: state
      entity_id: input_slider.marantz_volume_main
    action:
      service: shell_command.marantz_volume
      data_template:
        volume: "{{ states('input_slider.marantz_volume_main') }}"

  - alias: Input Slider for Marantz ZONE2 Volume
    trigger:
      platform: state
      entity_id: input_slider.marantz_volume_zone2
    action:
      service: shell_command.marantz_volume
      data_template:
        volume: "{{ states('input_slider.marantz_volume_zone2') }}"
        zone: 'zone2'
