# Description:
#   Trigger an automation based on a light's brightness
#
# Written for:
#   @albyalby_twitter
#
# Components:
#   automation
#   input_boolean
#   light
#
# License:
#   MIT
#
# Author:
#   Dale Higgs <@dale3h>
#
# PLEASE NOTE: THIS CONFIGURATION IS UNTESTED AND MAY CONTAIN ERRORS

automation:
  # Test for a specific brightness level
  - alias: let_there_be_light
    trigger:
      - platform: template
        entity_id: light.living_room_lamp
        value_template: "{{ trigger.to_state.attributes.brightness == 255 }}"
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.light_is_max
        state: 'on'

  # Test for brightness in a range
  - alias: let_there_be_more_light
    trigger:
      - platform: template
        entity_id: light.living_room_lamp
        value_template: "{{ trigger.to_state.attributes.brightness >= 170 and trigger.to_state.attributes.brightness <= 255 }}"
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.light_is_high
        state: 'on'

  # Test for brightness in a range (simple, but not sure it'll work)
  - alias: let_there_be_even_more_light
    trigger:
      - platform: numeric_state
        entity_id: light.living_room_lamp
        above: 0
        below: 85
        value_template: "{{ trigger.to_state.attributes.brightness }}"
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.light_is_low
        state: 'on'
