################################################################
## Group / Views
################################################################

home:
  view: yes
  entities:
    - group.back_porch
    - group.dining_room
    - group.entryway
    - group.front_porch
    - group.garage
    - group.guest_bedroom
    - group.hallway
    - group.hue_lights
    - group.kitchen
    - group.laundry_room
    - group.living_room
    - group.master_bedroom
    - group.scripts

household:
  view: yes
  entities:
    - group.person_dale
    - group.guests

cameras:
  view: yes
  entities:
    - group.cameras_home
    - group.cameras_hitech

sensors:
  view: yes
  entities:
    - group.weather
    - group.batteries
    - group.temperature
    - group.motion
    - group.occupancy
    - group.ups

media:
  view: yes
  entities:
    - group.media_components
    - group.media_player

automation:
  view: yes
  entities:
    - group.automation_override
    - group.scripts
    - group.scenes
