# NOTE: The attribute "Game" must be capitalized for this to work

sensor:
- platform: template
  sensors:
    steam_game:
      friendly_name: Playing Now
      value_template: "{{ states.sensor.steam_XXXXXXXX.attributes.Game if states.sensor.steam_XXXXXXXX else 'None' }}"
      entity_id: sensor.steam_XXXXXXXX

automation:
  - alias: Rocket League
    trigger:
      - platform: state
        entity_id: sensor.steam_game
        to: 'Rocket League'
    action:
      - service: scene.turn_on
        entity_id: scene.80s
