# Description:
#   Activate a scene using an input_select
#
# Written for:
#   @eugenelai
#
# Components:
#   automation
#   input_select
#   scene
#
# License:
#   MIT
#
# Author:
#   Dale Higgs <@dale3h>
#
# PLEASE NOTE: THIS CONFIGURATION IS UNTESTED AND MAY CONTAIN ERRORS

automation:
  - alias: select_a_scene
    trigger:
      # Trigger when the input_select changes
      - platform: state
        entity_id: input_select.scene_selector
    condition:
      # Do not trigger if "None" is selected
      - platform: template
        value_template: "{{ not is_state('input_select.scene_selector', 'None') }}"
    action:
      # Turn the selected scene on
      - service: scene.turn_on
        data_template:
          entity_id: "scene.{{ states('input_select.scene_selector')|lower|replace(' ', '_') }}"
      # Set the input_select back to "None"
      - service: input_select.select_option
        entity_id: input_select.scene_selector
        data:
          option: 'None'

input_select:
  scene_selector:
    name: Scene Selector
    initial: 'None'
    options:
      - 'None'
      - 'Low'
      - 'Bright'

scene:
  - name: Low
    entities:
      light.bedroom:
        state: on
        brightness: 20

  - name: Bright
    entities:
      light.bedroom:
        state: on
        brightness: 100
