automation:
  - alias: Stop Streaming Radio
    trigger:
      platform: state
      entity_id: input_select.radio_station
      to: 'None'
    condition: or
    conditions:
      - condition: state
        entity_id: input_select.radio_player
        state: 'Office'
      - condition: state
        entity_id: input_select.radio_player
        state: 'Bedroom'
      - condition: state
        entity_id: input_select.radio_player
        state: 'Kitchen'
    action:
      service: media_player.turn_off
      data_template:
        entity_id: >
          {%- if is_state('input_select.radio_player', 'Office') -%}
            media_player.office
          {%- elif is_state('input_select.radio_player', 'Bedroom') -%}
            media_player.bedroom
          {%- elif is_state('input_select.radio_player', 'Kitchen') -%}
            media_player.kitchen
          {%- endif -%}

  - alias: Start Streaming Radio
    trigger:
      - platform: state
        entity_id: input_select.radio_station
        to: 'X96'
      - platform: state
        entity_id: input_select.radio_station
        to: 'KISS FM'
      - platform: state
        entity_id: input_select.radio_station
        to: 'Country Time'
    condition: or
    conditions:
      - condition: state
        entity_id: input_select.radio_player
        state: 'Office'
      - condition: state
        entity_id: input_select.radio_player
        state: 'Bedroom'
      - condition: state
        entity_id: input_select.radio_player
        state: 'Kitchen'
    action:
      service: media_player.play_media
      data_template:
        entity_id: >
          {%- if is_state('input_select.radio_player', 'Office') -%}
            media_player.office
          {%- elif is_state('input_select.radio_player', 'Bedroom') -%}
            media_player.bedroom
          {%- elif is_state('input_select.radio_player', 'Kitchen') -%}
            media_player.kitchen
          {%- endif -%}
        media_content_id: >
          {%- if is_state('input_select.radio_station', 'X96') -%}
            'http://ice41.securenetsystems.net/KXRK?type=.mp4'
          {%- elif is_state('input_select.radio_station', 'KISS FM') -%}
            'http://ice41.securenetsystems.net/KISS?type=.mp4'
          {%- elif is_state('input_select.radio_station', 'Country Time') -%}
            'http://ice41.securenetsystems.net/CTRY?type=.mp4'
          {%- endif -%}
        media_content_type: 'audio/mp4'
