################################################################
## Cover / Garage Door
################################################################

################################################
## Aladdin Connect MQTT Bridge
################################################

- platform: mqtt
  name: garage_door
  state_topic: home-assistant/cover/garage_door
  command_topic: home-assistant/cover/garage_door/set
  payload_open: 'open'
  payload_close: 'close'
  payload_stop: 'stop'
  state_open: 'open'
  state_closed: 'closed'
  retain: true
