################################################################
## Remote / Logitech Harmony
################################################################

- platform: harmony
  name: Living Room
  host: !secret harmony_host
  port: !secret harmony_port
  username: !secret harmony_username
  password: !secret harmony_password
  activity: Watch Apple TV
