#################################################################
## Camera / HiTech
#################################################################

- platform: generic
  name: hitech_driveway
  still_image_url: !secret camera_hitech_driveway_url

- platform: generic
  name: hitech_front_yard
  still_image_url: !secret camera_hitech_front_yard_url

- platform: generic
  name: hitech_barn
  still_image_url: !secret camera_hitech_barn_url

- platform: generic
  name: hitech_camper
  still_image_url: !secret camera_hitech_camper_url
