#################################################################
## Camera / Home
#################################################################

- platform: mjpeg
  name: driveway
  mjpeg_url: !secret camera_home_driveway_url
  username: !secret camera_home_driveway_username
  password: !secret camera_home_driveway_password
  authentication: basic

- platform: mjpeg
  name: garage
  mjpeg_url: !secret camera_home_garage_url
  username: !secret camera_home_garage_username
  password: !secret camera_home_garage_password
  authentication: basic
