################################################################
## Sensor / Batteries
################################################################

- platform: template
  sensors:
    iphone_battery:
      value_template: "{{ states.device_tracker.iphone.attributes.battery|default(-1)|int if states.device_tracker.iphone is not none }}"
      unit_of_measurement: '%'
      entity_id: device_tracker.iphone

    master_bathroom_battery_4:
      value_template: "{{ states.binary_sensor.master_bathroom_sensor_4.attributes.battery_level|default(-1)|int if states.binary_sensor.master_bathroom_sensor_4 is not none }}"
      unit_of_measurement: '%'
      entity_id: binary_sensor.master_bathroom_sensor_4
