################################################################
## Sensor / Batteries
################################################################

- platform: template
  sensors:
    iphone_battery:
      value_template: "{{ states.device_tracker.dale_iphone_ios.attributes.battery|default(-1)|int if states.device_tracker.dale_iphone_ios is not none }}"
      unit_of_measurement: '%'
      entity_id: device_tracker.dale_iphone_ios
