################################################################
## Sensor / Batteries
################################################################

- platform: template
  sensors:
    iphone_battery:
      value_template: "{{ states.device_tracker.iphone.attributes.battery|default(-1)|int if states.device_tracker.iphone is not none }}"
      unit_of_measurement: '%'
      entity_id: device_tracker.iphone

    kitchen_battery:
      value_template: "{{ states.binary_sensor.kitchen_sensor_6_0.attributes.battery_level|default(-1)|int if states.binary_sensor.kitchen_sensor_6_0 is not none }}"
      unit_of_measurement: '%'
      entity_id: binary_sensor.kitchen_sensor_6_0

    master_bathroom_battery:
      value_template: "{{ states.binary_sensor.master_bathroom_sensor_4_0.attributes.battery_level|default(-1)|int if states.binary_sensor.master_bathroom_sensor_4_0 is not none }}"
      unit_of_measurement: '%'
      entity_id: binary_sensor.master_bathroom_sensor_4_0
