################################################################
## Sensor / System
################################################################

- platform: command_line
  name: cpu_temperature
  command: cat /sys/class/thermal/thermal_zone0/temp
  unit_of_measurement: '°F'
  value_template: '{{ (value|int / 1000 * 1.8 + 32)|round(1) }}'

- platform: time_date
  display_options:
    - date
    - time
