################################################################
## Sensor / System
################################################################

- platform: time_date
  display_options:
    - date
    - time

- platform: template
  sensors:
    hass_startup_time:
      value_template: >-
        {{ (states.automation.startup_notification.attributes|default({})).last_triggered }}
