################################################################
## Sensor / Weather
################################################################

- platform: darksky
  api_key: !secret darksky_api_key
  monitored_conditions:
    - cloud_cover
    - humidity
    - precip_probability
    - temperature

- platform: wunderground
  api_key: !secret wunderground_api_key
  monitored_conditions:
    - feelslike_f
    - heat_index_f
    - precip_today_in
    - relative_humidity
    - temp_f
    - weather

- platform: yr
  monitored_conditions:
    - cloudiness
    - humidity
    - precipitation
    - temperature

- platform: template
  sensors:
    season:
      value_template: >-
        {% set temp_entity = 'sensor.pws_temp_f' %}
        {% set temp = states(temp_entity)|float(none) %}
        {% set temp_min = states.input_slider.season_winter.state|default(68)|float %}
        {% set temp_max = states.input_slider.season_summer.state|default(84)|float %}

        {% if temp is none %}
          {{ states(temp_entity) }}
        {% elif temp < temp_min %}
          Winter
        {% elif temp > temp_max %}
          Summer
        {% else %}
          Awesome
        {% endif %}
