################################################################
## Sensor / Weather
################################################################

- platform: forecast
  api_key: !secret forecast_api_key
  monitored_conditions:
    - precip_probability
    - temperature
    - cloud_cover
    - humidity
