################################################################
## Automation / Dash Buttons
################################################################

################################################
## Master Bedroom Motion (Kraft)
################################################

# - alias: toggle_master_bedroom_motion
#   trigger:
#     platform: mqtt
#     topic: dash-button/kraft
#   action:
#     service: input_boolean.toggle
#     entity_id: input_boolean.master_bedroom_motion

################################################
## Master Bathroom Shower Mode (Ziploc)
################################################

- alias: toggle_master_bathroom_shower_mode
  trigger:
    platform: state
    entity_id: binary_sensor.dashbutton_ziploc
    to: 'on'
  action:
    service: input_boolean.toggle
    entity_id: input_boolean.shower_mode

################################################
## Good Night Script (Gatorade)
################################################

# - alias: activate_good_night_script
#   trigger:
#     platform: mqtt
#     topic: dash-button/gatorade
#   action:
#     service: script.good_night
