################################################################
## Automation / Dash Buttons
################################################################

################################################
## Master Bedroom Motion (Kraft)
################################################

- alias: toggle_master_bedroom_motion
  trigger:
    platform: mqtt
    topic: dash-button/kraft_mac_and_cheese
  action:
    service: homeassistant.toggle
    entity_id: input_boolean.master_bedroom_motion

################################################
## Master Bathroom Motion (Ziploc)
################################################

- alias: toggle_master_bathroom_motion
  trigger:
    platform: mqtt
    topic: dash-button/ziploc
  action:
    service: homeassistant.toggle
    entity_id: input_boolean.master_bathroom_motion

################################################
## Good Night Script (Gatorade)
################################################

- alias: activate_good_night_script
  trigger:
    platform: mqtt
    topic: dash-button/gatorade
  action:
    service: script.good_night
