################################################################
## Automation / Front Porch Timer
################################################################

- alias: front_porch_timer
  trigger:
    - platform: template
      value_template: "{{ is_state('input_select.front_porch_time_on', states('sensor.time')) }}"
    - platform: template
      value_template: "{{ is_state('input_select.front_porch_time_off', states('sensor.time')) }}"
  condition:
    - condition: or
      conditions:
        - condition: and
          conditions:
            - condition: template
              value_template: "{{ is_state('input_select.front_porch_time_on', states('sensor.time')) }}"
            - condition: state
              entity_id: group.front_porch_light
              state: 'off'
        - condition: and
          conditions:
            - condition: template
              value_template: "{{ is_state('input_select.front_porch_time_off', states('sensor.time')) }}"
            - condition: state
              entity_id: group.front_porch_light
              state: 'on'
  action:
    - service_template: "light.turn_{{ 'on' if is_state('input_select.front_porch_time_on', states('sensor.time')) else 'off' }}"
      entity_id: group.front_porch_light
