################################################################
## Automation / HTTPS Proxy
################################################################

- alias: restart_https_proxy
  trigger:
    platform: event
    event_type: homeassistant_start
  action:
    service: script.restart_https_proxy
