################################################################
## Automation / Hue Switches
################################################################

################################################
## Working Automations
################################################

- alias: hue_master_bedroom_dimmer_button_1_long_press
  trigger:
    - platform: mqtt
      topic: hue/master_bedroom_dimmer/buttonevent
      payload: '1003'
  action:
    - service: script.turn_on
      entity_id: script.good_morning

- alias: hue_master_bedroom_dimmer_button_4_long_press
  trigger:
    - platform: mqtt
      topic: hue/master_bedroom_dimmer/buttonevent
      payload: '4003'
  action:
    - service: script.turn_on
      entity_id: script.good_night

- alias: hue_parker_tap_button_1
  trigger:
    - platform: mqtt
      topic: hue/parker_tap/buttonevent
      payload: '34'
  action:
    - service_template: light.toggle
      entity_id: group.parker_lamp

################################################
## Debugging Automations
################################################

- alias: hue_dimmers
  trigger:
    - platform: mqtt
      topic: hue/+/buttonevent
  condition:
    - condition: template
      value_template: "{{ trigger.topic.split('/')[1] != 'parker_tap' }}"
  action:
    - service: notify.telegram
      data_template:
        message: >-
          {% set dimmer = trigger.topic.split('/')[1]|replace('_', ' ')|title %}
          {% set button = trigger.topic.payload[0] %}

          {{ dimmer }} Button {{ button }} was pressed.

#           {% elif trigger.payload == '1003' %}
#             The Hue Dimmer 1 Button 1 was long-pressed.
#           {% elif trigger.payload == '2002' %}
#             The Hue Dimmer 1 Button 2 was pressed.
#           {% elif trigger.payload == '2003' %}
#             The Hue Dimmer 1 Button 2 was long-pressed.
#           {% elif trigger.payload == '3002' %}
#             The Hue Dimmer 1 Button 3 was pressed.
#           {% elif trigger.payload == '3003' %}
#             The Hue Dimmer 1 Button 3 was long-pressed.
#           {% elif trigger.payload == '4002' %}
#             The Hue Dimmer 1 Button 4 was pressed.
#           {% elif trigger.payload == '4003' %}
#             The Hue Dimmer 1 Button 4 was long-pressed.
#           {% else %}
#             The Hue Dimmer 1 Button was not recognized: {{ trigger.payload }}.
#           {% endif %}

# - alias: hue_parker_tap
#   trigger:
#     - platform: mqtt
#       topic: hue/parker_tap/buttonevent
#   condition:
#     - condition: template
#       value_template: "{{ trigger.payload != '34' }}"
#   action:
#     - service: notify.telegram
#       data_template:
#         message: >-
#           {% if trigger.payload == '34' %}
#             The Parker Tap Button 1 was pressed.
#           {% elif trigger.payload == '16' %}
#             The Parker Tap Button 2 was pressed.
#           {% elif trigger.payload == '17' %}
#             The Parker Tap Button 3 was pressed.
#           {% elif trigger.payload == '18' %}
#             The Parker Tap Button 4 was pressed.
#           {% else %}
#             The Parker Tap Button was not recognized: {{ trigger.payload }}.
#           {% endif %}
