################################################################
## Automation / iCloud Fallback
################################################################

- alias: icloud_fallback_not_home
  trigger:
    - platform: state
      entity_id: device_tracker.dale_iphone
      to: 'not_home'
  condition:
    - condition: state
      entity_id: device_tracker.iphone
      state: 'home'
  action:
    - service: icloud.setinterval
      data:
        accountname: dale
        interval: 1

- alias: icloud_fallback_home
  trigger:
    - platform: state
      entity_id: device_tracker.dale_iphone
      to: 'home'
  condition:
    - condition: and
      conditions:
      - condition: state
        entity_id: device_tracker.iphone
        state: 'home'
      - condition: numeric_state
        entity_id: idevice.iphone
        below: 30
  action:
    - service: icloud.setinterval
      data:
        accountname: dale
