################################################################
## Automation / iCloud Fallback
################################################################

- alias: icloud_fallback
  trigger:
    - platform: state
      entity_id: device_tracker.dale_iphone
      to: 'not_home'
  condition:
    - condition: state
      entity_id: device_tracker.iphone
      state: 'home'
  action:
    - service: device_tracker.icloud_set_interval
      data_template:
        account_name: !secret icloud_account_name
        interval: "{{ 1 if trigger.to_state.state == 'not_home' else 30 }}"
