################################################################
## Automation / Media Player Lighting
################################################################

- alias: media_lights_when_playing
  trigger:
    - platform: state
      entity_id: media_player.living_room
      to: 'playing'
  condition:
    - condition: state
      entity_id: input_boolean.night_mode
      state: 'off'
  action:
    - service: light.turn_off
      data:
        entity_id:
          - light.entry_lamp
          - light.living_room
          - light.dining_room

- alias: media_lights_when_paused
  trigger:
    - platform: state
      entity_id: media_player.living_room
      from: 'playing'
  condition:
    - condition: state
      entity_id: input_boolean.night_mode
      state: 'off'
  action:
    - service: light.turn_on
      data_template:
        entity_id:
          - light.entry_lamp
          - light.living_room
          - light.dining_room
        brightness: "{{ states('sensor.global_brightness')|int }}"
