################################################################
## Automation / Garage Entry Lights
################################################################

- alias: laundry_room_and_garage_lights_on_when_garage_entry_door_is_open
  trigger:
    - platform: state
      entity_id: binary_sensor.garage_entry_contact
      to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.garage_lighting
      state: 'on'
  action:
    - service: light.turn_on
      entity_id: light.laundry_room, light.garage
      data_template:
        brightness: "{{ states('sensor.global_brightness')|int }}"

- alias: laundry_room_and_garage_lights_off_when_garage_entry_door_is_closed
  trigger:
    - platform: state
      entity_id: binary_sensor.garage_entry_contact
      to: 'off'
  condition:
    - condition: state
      entity_id: input_boolean.garage_lighting
      state: 'on'
  action:
    - delay:
        minutes: 5
    - service: light.turn_off
      entity_id: light.laundry_room, light.garage
