################################################################
## Automation / Closet Lights
################################################################

# @todo Reduce this to one automation, along with others

################################################
## Master Closet
################################################

- alias: master_closet_light_on_when_door_is_open
  trigger:
    - platform: state
      entity_id: binary_sensor.closet_door_contact
      to: 'on'
  action:
    - service: light.turn_on
      entity_id: light.master_closet
      data_template:
        brightness: "{{ states('sensor.global_brightness')|int }}"

- alias: master_closet_light_off_when_door_is_closed
  trigger:
    - platform: state
      entity_id: binary_sensor.closet_door_contact
      to: 'off'
  action:
    - service: light.turn_off
      data:
        entity_id: light.master_closet

################################################
## Parker's Closet
################################################

- alias: parker_closet_light_on_when_door_is_open
  trigger:
    - platform: state
      entity_id: binary_sensor.parker_closet_door_contact
      to: 'on'
  action:
    - service: light.turn_on
      data_template:
        entity_id: light.parker_closet
        brightness: "{{ states('sensor.global_brightness')|int }}"

- alias: parker_closet_light_off_when_door_is_closed
  trigger:
    - platform: state
      entity_id: binary_sensor.parker_closet_door_contact
      to: 'off'
  action:
    - service: light.turn_off
      data:
        entity_id: light.parker_closet
