################################################################
## Automation / Garage Entry Lighting
################################################################

- alias: Laundry Room and Garage Lights ON when Garage Entry Door is OPEN
  trigger:
    - platform: state
      entity_id: binary_sensor.garage_entry_contact
      to: 'on'
  condition:
    - condition: state
      entity_id: switch.auto_garage_entry_lighting
      state: 'on'
  action:
    - service: light.turn_on
      entity_id: light.laundry_room, light.garage
      data_template:
        brightness: "{{ states('sensor.time_brightness')|int }}"

- alias: Laundry Room and Garage Lights OFF when Garage Entry Door is CLOSED
  trigger:
    - platform: state
      entity_id: binary_sensor.garage_entry_contact
      to: 'off'
  condition:
    - condition: state
      entity_id: switch.auto_garage_entry_lighting
      state: 'on'
  action:
    - delay:
        minutes: 5
    - service: light.turn_off
      entity_id: light.laundry_room, light.garage
