################################################################
## Automation / Kitchen Lights
################################################################

- alias: kitchen_lights_on_when_motion_active
  trigger:
    platform: state
    entity_id: binary_sensor.kitchen_sensor_6_0
    to: 'on'
  condition:
    condition: state
    entity_id: input_boolean.kitchen_motion
    state: 'on'
  action:
    service: light.turn_on
    entity_id: group.kitchen
    data_template:
      brightness: "{{ states('sensor.time_brightness')|int }}"

- alias: kitchen_lights_off_when_motion_inactive
  trigger:
    platform: state
    entity_id: binary_sensor.kitchen_sensor_6_0
    to: 'off'
  condition:
    condition: state
    entity_id: input_boolean.kitchen_motion
    state: 'on'
  action:
    service: light.turn_off
    entity_id: group.kitchen
