################################################################
## Automation / Presence Light
################################################################

################################################
## Turn Lights ON when Dale Arrives
################################################

- alias: activate_arrival_scene
  trigger:
    platform: state
    entity_id: group.household
    to: 'home'
  action:
    service: scene.turn_on
    entity_id: scene.arrival

################################################
## Turn Lights OFF when Dale Leaves
################################################

- alias: activate_departure_scene
  trigger:
    platform: state
    entity_id: group.household
    from: 'home'
  action:
    service: scene.turn_on
    entity_id: scene.departure
