################################################################
## Automation / Update Notification
################################################################

- alias: home_assistant_update_notification
  trigger:
    - platform: state
      entity_id: updater.updater
    - platform: event
      event_type: homeassistant_start
  condition:
    - condition: template
      value_template: "{{ states('updater.updater') != 'unknown' }}"
  action:
    - service: notify.telegram
      data_template:
        message: "Home Assistant {{ states('updater.updater') }} is now available."
