################################################################
## Automation / Server Load Notification
################################################################

- alias: server_load_notification
  trigger:
    - platform: numeric_state
      entity_id: sensor.vixen_vapors_cpu_load
      above: 50
    - platform: numeric_state
      entity_id: sensor.vixen_vapors_cpu_load
      above: 100
    - platform: numeric_state
      entity_id: sensor.vixen_vapors_cpu_load
      above: 200
    - platform: numeric_state
      entity_id: sensor.vixen_vapors_cpu_load
      above: 400
    - platform: numeric_state
      entity_id: sensor.vixen_vapors_cpu_load
      above: 800
    - platform: numeric_state
      entity_id: sensor.vixen_vapors_cpu_load
      above: 1600
    - platform: numeric_state
      entity_id: sensor.vixen_vapors_cpu_load
      above: 3200
    - platform: numeric_state
      entity_id: sensor.vixen_vapors_cpu_load
      above: 6400
    - platform: numeric_state
      entity_id: sensor.vixen_vapors_cpu_load
      above: 12800
  action:
    - service: notify.telegram
      data_template:
        message: "The load for Vixen Vapors has reached {{ trigger.to_state.state }}% ({{ trigger.to_state.attributes.loadavg }})"
