################################################################
## Automation / Occupancy
################################################################

################################################
## Test Automation for Occupancy Sensor
################################################

- alias: occupancy_test_on
  trigger:
    - platform: state
      entity_id: binary_sensor.occupancy_test
      to: 'on'
  action:
    - service: light.turn_on
      entity_id: light.living_room_1

- alias: occupancy_test_off
  trigger:
    - platform: state
      entity_id: binary_sensor.occupancy_test
      to: 'off'
  action:
    - service: light.turn_off
      entity_id: light.living_room_1

################################################
## Dummy Motion Sensor (Quick Toggle)
################################################

- alias: motion_dummy_toggle_off
  trigger:
    - platform: state
      entity_id: input_boolean.motion_dummy
      to: 'on'
  action:
    - delay:
        seconds: 2
    - service: input_boolean.turn_off
      entity_id: input_boolean.motion_dummy

################################################
## The Real Magic
################################################

- alias: motion_dummy_on
  trigger:
    - platform: state
      entity_id: input_boolean.motion_dummy
      state: 'on'
  action:
    - service: script.occupancy
      data:
        name: occupancy_test
        timeout: '00:00:10'

- alias: occupancy_timeout_received
  trigger:
    - platform: mqtt
      topic: home-assistant/occupancy/+/timeout
  action:
    - delay: "{{ trigger.payload }}"
    - service: mqtt.publish
      data_template:
        topic: "{{ trigger.topic|replace('/timeout', '') }}"
        payload: 'off'
        retain: true
