################################################################
## Automation / Z-Wave Remotes
################################################################

################################################
## Dining Room Remote
################################################

- alias: dining_room_remote_button_1_pressed
  trigger:
    - platform: event
      event_type: zwave.scene_activated
      event_data:
        object_id: dining_room_remote_12
        scene_id: 1
  action:
    - service: light.turn_on
      data:
        entity_id: group.living_room_light
        brightness: 255

- alias: dining_room_remote_button_1_held
  trigger:
    - platform: event
      event_type: zwave.scene_activated
      event_data:
        object_id: dining_room_remote_12
        scene_id: 2
  action:
    - service: switch.turn_on
      data:
        entity_id: switch.apple_tv

- alias: dining_room_remote_button_2_pressed
  trigger:
    - platform: event
      event_type: zwave.scene_activated
      event_data:
        object_id: dining_room_remote_12
        scene_id: 3
  action:
    - service: light.turn_on
      data:
        entity_id: group.dining_room_light
        brightness: 255

# - alias: dining_room_remote_button_2_held
#   trigger:
#     - platform: event
#       event_type: zwave.scene_activated
#       event_data:
#         object_id: dining_room_remote_12
#         scene_id: 4

- alias: dining_room_remote_button_3_pressed
  trigger:
    - platform: event
      event_type: zwave.scene_activated
      event_data:
        object_id: dining_room_remote_12
        scene_id: 5
  action:
    - service: light.turn_off
      data:
        entity_id: group.living_room_light

- alias: dining_room_remote_button_3_held
  trigger:
    - platform: event
      event_type: zwave.scene_activated
      event_data:
        object_id: dining_room_remote_12
        scene_id: 6
  action:
    - service: switch.turn_off
      data:
        entity_id: switch.apple_tv

- alias: dining_room_remote_button_4_pressed
  trigger:
    - platform: event
      event_type: zwave.scene_activated
      event_data:
        object_id: dining_room_remote_12
        scene_id: 7
  action:
    - service: light.turn_off
      data:
        entity_id: group.dining_room_light

# - alias: dining_room_remote_button_4_held
#   trigger:
#     - platform: event
#       event_type: zwave.scene_activated
#       event_data:
#         object_id: dining_room_remote_12
#         scene_id: 8

################################################
## Master Bedroom Remote
################################################

# - alias: master_bedroom_remote_button_1_pressed
#   trigger:
#     - platform: event
#       event_type: zwave.scene_activated
#       event_data:
#         object_id: master_bedroom_remote_11
#         scene_id: 1

# - alias: master_bedroom_remote_button_1_held
#   trigger:
#     - platform: event
#       event_type: zwave.scene_activated
#       event_data:
#         object_id: master_bedroom_remote_11
#         scene_id: 2

# - alias: master_bedroom_remote_button_2_pressed
#   trigger:
#     - platform: event
#       event_type: zwave.scene_activated
#       event_data:
#         object_id: master_bedroom_remote_11
#         scene_id: 3

# - alias: master_bedroom_remote_button_2_held
#   trigger:
#     - platform: event
#       event_type: zwave.scene_activated
#       event_data:
#         object_id: master_bedroom_remote_11
#         scene_id: 4

# - alias: master_bedroom_remote_button_3_pressed
#   trigger:
#     - platform: event
#       event_type: zwave.scene_activated
#       event_data:
#         object_id: master_bedroom_remote_11
#         scene_id: 5

# - alias: master_bedroom_remote_button_3_held
#   trigger:
#     - platform: event
#       event_type: zwave.scene_activated
#       event_data:
#         object_id: master_bedroom_remote_11
#         scene_id: 6

# - alias: master_bedroom_remote_button_4_pressed
#   trigger:
#     - platform: event
#       event_type: zwave.scene_activated
#       event_data:
#         object_id: master_bedroom_remote_11
#         scene_id: 7

# - alias: master_bedroom_remote_button_4_held
#   trigger:
#     - platform: event
#       event_type: zwave.scene_activated
#       event_data:
#         object_id: master_bedroom_remote_11
#         scene_id: 8
