################################################################
## Media Player / Fire TV
################################################################

################################################
## Apple TV
################################################

# - platform: apple_tv
#   name: apple_tv_living_room
#   host: !secret apple_tv_living_room_host
#   login_id: !secret apple_tv_living_room_login_id

# - platform: apple_tv
#   name: apple_tv_bedroom
#   host: !secret apple_tv_bedroom_host
#   login_id: !secret apple_tv_bedroom_login_id

################################################
## Google Cast
################################################

- platform: cast
  name: dining_room_home
  host: !secret google_cast_dining_room_host

- platform: cast
  name: living_room_speakers
  host: !secret google_cast_living_room_host

- platform: cast
  name: master_bedroom_speakers
  host: !secret google_cast_master_bedroom_host

- platform: cast

################################################
## Yamaha RX-V675
################################################

# - platform: yamaha
#   name: yamaha_avr
#   host: !secret yamaha_avr_host
#   source_ignore:
#     - AUDIO2
#     - AV1
#     - AV2
#     - AV3
#     - AV4
#     - AV5
#     - AV6
#     - NET RADIO
#     - Pandora
#     - Rhapsody
#     - SiriusXM
#     - Spotify
#     - iPod (USB)
#   source_names:
#     AUDIO1: Chromecast
