################################################################
## Media Player / Fire TV
################################################################

################################################
## Plex
################################################

- platform: plex

################################################
## Apple TV
################################################

# - platform: universal
#   name: apple_tv
#   commands:
#     turn_on:
#       service: mqtt.publish
#       data:
#         topic: harmony-api/hubs/harmony-hub/activities/watch-apple-tv/command
#         payload: 'on'
#     turn_off:
#       service: mqtt.publish
#       data:
#         topic: harmony-api/hubs/harmony-hub/activities/watch-apple-tv/command
#         payload: 'off'
#     volume_up:
#       service: mqtt.publish
#       data:
#         topic: harmony-api/hubs/harmony-hub/devices/yamaha-avr/command
#         payload: 'volume-up'
#     volume_down:
#       service: mqtt.publish
#       data:
#         topic: harmony-api/hubs/harmony-hub/devices/yamaha-avr/command
#         payload: 'volume-down'
#     volume_mute:
#       service: mqtt.publish
#       data:
#         topic: harmony-api/hubs/harmony-hub/devices/yamaha-avr/command
#         payload: 'mute'
#   attributes:
#     state: switch.apple_tv
