################################################################
## Media Player / Fire TV
################################################################

################################################
## Google Cast
################################################

- platform: cast
  name: dining_room_home
  host: !secret google_cast_dining_room_host

- platform: cast
  name: living_room_speakers
  host: !secret google_cast_living_room_host

- platform: cast
  name: master_bedroom_speakers
  host: !secret google_cast_master_bedroom_host

################################################
## Plex
################################################

# - platform: plex

################################################
## Living Room Apple TV
################################################

- platform: universal
  name: living_room_apple_tv
  children:
    - media_player.living_room
  commands:
    turn_on:
      service: mqtt.publish
      data:
        topic: harmony-api/hubs/harmony-hub/activities/watch-apple-tv/command
        payload: 'on'
    turn_off:
      service: mqtt.publish
      data:
        topic: harmony-api/hubs/harmony-hub/activities/watch-apple-tv/command
        payload: 'off'
    volume_up:
      service: mqtt.publish
      data:
        topic: harmony-api/hubs/harmony-hub/devices/yamaha-av-receiver/command
        payload: 'volume-up'
    volume_down:
      service: mqtt.publish
      data:
        topic: harmony-api/hubs/harmony-hub/devices/yamaha-av-receiver/command
        payload: 'volume-down'
    volume_mute:
      service: mqtt.publish
      data:
        topic: harmony-api/hubs/harmony-hub/devices/yamaha-av-receiver/command
        payload: 'mute'
  attributes:
    state: switch.apple_tv
