################################################################
## Device Tracker / AsusWRT
################################################################

- platform: asuswrt
  host: !secret asuswrt_host
  protocol: ssh
  mode: router
  username: !secret asuswrt_username
  ssh_key: !secret asuswrt_ssh_key
