################################################################
## Device Tracker
################################################################

################################################
## AsusWRT
################################################

- platform: asuswrt
  host: !secret asuswrt_host
  protocol: ssh
  mode: router
  username: !secret asuswrt_username
  ssh_key: !secret asuswrt_ssh_key

################################################
## Bluetooth
################################################

- platform: bluetooth_tracker

################################################
## iCloud
################################################

# - platform: icloud
#   username: !secret icloud_username
#   password: !secret icloud_password

################################################
## OwnTracks
################################################

# - platform: owntracks
#   max_gps_accuracy: 200
