################################################################
## Packages / Alarm
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    packages.alarm: &customize
      haaska_hidden: true
      homebridge_hidden: true
      package: 'alarm'

    alarm_control_panel.alarm_system:
      <<: *customize
      friendly_name: "Alarm System"

    group.alarm_system:
      <<: *customize
      friendly_name: "Alarm System"

    switch.siren_switch_16_0:
      <<: *customize
      friendly_name: "Siren"

################################################
## Group
################################################

group:
  alarm_system:
    control: hidden
    entities:
      - alarm_control_panel.alarm_system
      - sensor.siren_battery
      - !secret switch_siren

################################################
## Alarm Control Panel
################################################

alarm_control_panel:
  - platform: manual
    name: alarm_system
    code: !secret alarm_code
