################################################################
## Packages / Alarm
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'alarm'

      exposed: &exposed
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

      hidden: &hidden
        <<: *customize
        hidden: true

    ################################################
    ## Alarm Control Panel
    ################################################

    alarm_control_panel.alarm_system:
      <<: *customize
      friendly_name: "Alarm System"

    ################################################
    ## Group
    ################################################

    group.alarm_system:
      <<: *customize
      friendly_name: "Alarm System"

    ################################################
    ## Switch
    ################################################

    switch.siren_switch:
      <<: *customize
      friendly_name: "Siren"

################################################
## Group
################################################

group:
  alarm_system:
    control: hidden
    entities:
      - alarm_control_panel.alarm_system
      - sensor.siren_battery
      - switch.siren_switch

################################################
## Alarm Control Panel
################################################

alarm_control_panel:
  - platform: manual
    name: alarm_system
    code: !secret alarm_code
