################################################################
## Packages / Alarm
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'alarm'

      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

    ################################################
    ## Alarm Control Panel
    ################################################

    alarm_control_panel.alarm_system:
      <<: *customize
      friendly_name: "Alarm System"

    ################################################
    ## Group
    ################################################

    group.alarm_system:
      <<: *customize
      friendly_name: "Alarm System"

    ################################################
    ## Switch
    ################################################

    switch.dining_room_siren_switch:
      <<: *customize
      friendly_name: "Dining Room Siren"

    switch.master_bedroom_siren_switch:
      <<: *customize
      friendly_name: "Master Bedroom Siren"

################################################
## Group
################################################

group:
  alarm_system:
    control: hidden
    entities:
      - alarm_control_panel.alarm_system
      - switch.dining_room_siren_switch
      - sensor.dining_room_siren_battery
      - switch.master_bedroom_siren_switch
      - sensor.master_bedroom_siren_battery

################################################
## Alarm Control Panel
################################################

alarm_control_panel:
  - platform: manual
    name: alarm_system
    code: !secret alarm_code
