################################################################
## Packages / Apple TV
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'apple_tv'

      contained: &contained
        <<: *customize
        haaska_hidden: true
        homebridge_hidden: true

      exposed: &exposed
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

      hidden: &hidden
        <<: *contained
        hidden: true

    ################################################
    ## Media Player
    ################################################

    media_player.apple_tv_bedroom:
      <<: *contained
      friendly_name: "Apple TV (Bedroom)"
      icon: mdi:apple

    media_player.apple_tv_living_room:
      <<: *contained
      friendly_name: "Apple TV (Living Room)"
      icon: mdi:apple

################################################
## Media Player
################################################

media_player:
  - platform: apple_tv
    name: apple_tv_living_room
    host: !secret apple_tv_living_room_host
    login_id: !secret apple_tv_living_room_login_id

  # - platform: apple_tv
  #   name: apple_tv_bedroom
  #   host: !secret apple_tv_bedroom_host
  #   login_id: !secret apple_tv_bedroom_login_id
