################################################################
## Packages / AsusWRT
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'asuswrt'

      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

################################################
## Device Tracker
################################################

device_tracker:
  - platform: asuswrt
    host: !secret asuswrt_host
    protocol: ssh
    mode: router
    username: !secret asuswrt_username
    ssh_key: !secret asuswrt_ssh_key
