################################################################
## Packages / Batteries
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'batteries'

      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

    ################################################
    ## Sensor
    ################################################

    sensor.dining_room_siren_battery:
      <<: *customize
      friendly_name: "Dining Room Siren Battery"

    sensor.front_door_lock_battery:
      <<: *customize
      friendly_name: "Front Door Lock Battery"

    sensor.front_door_sensor_battery:
      <<: *customize
      friendly_name: "Front Door Sensor Battery"

    sensor.iphone_battery:
      <<: *customize
      friendly_name: "iPhone Battery"

    sensor.kitchen_motion_battery:
      <<: *customize
      friendly_name: "Kitchen Motion Battery"

    sensor.master_bathroom_motion_battery:
      <<: *customize
      friendly_name: "Master Bathroom Motion Battery"

    sensor.master_bedroom_siren_battery:
      <<: *customize
      friendly_name: "Master Bedroom Siren Battery"

################################################
## Sensor
################################################

sensor:
  - platform: template
    sensors:
      dining_room_siren_battery:
        entity_id: zwave.dining_room_siren
        value_template: "{{ (states.zwave.dining_room_siren.attributes|default).battery_level|default|int('unknown') }}"
        unit_of_measurement: '%'
        icon_template: >-
          {% set battery_level = states('sensor.dining_room_siren_battery')|int('unknown') %}
          {% if battery_level == 'unknown' %}
            mdi:battery-unknown
          {% else %}
            {% set battery_round = (battery_level|int / 10)|int * 10 %}
            {% if battery_round >= 100 %}
              mdi:battery
            {% elif battery_round > 0 %}
              mdi:battery-{{ battery_round }}
            {% else %}
              mdi:battery-alert
            {% endif %}
          {% endif %}

      front_door_lock_battery:
        entity_id: zwave.front_door_2
        value_template: "{{ (states.zwave.front_door_2.attributes|default).battery_level|default|int('unknown') }}"
        unit_of_measurement: '%'
        icon_template: >-
          {% set battery_level = states('sensor.front_door_lock_battery')|int('unknown') %}
          {% if battery_level == 'unknown' %}
            mdi:battery-unknown
          {% else %}
            {% set battery_round = (battery_level|int / 10)|int * 10 %}
            {% if battery_round >= 100 %}
              mdi:battery
            {% elif battery_round > 0 %}
              mdi:battery-{{ battery_round }}
            {% else %}
              mdi:battery-alert
            {% endif %}
          {% endif %}

      front_door_sensor_battery:
        entity_id: zwave.front_door
        value_template: "{{ (states.zwave.front_door.attributes|default).battery_level|default|int('unknown') }}"
        unit_of_measurement: '%'
        icon_template: >-
          {% set battery_level = states('sensor.front_door_sensor_battery')|int('unknown') %}
          {% if battery_level == 'unknown' %}
            mdi:battery-unknown
          {% else %}
            {% set battery_round = (battery_level|int / 10)|int * 10 %}
            {% if battery_round >= 100 %}
              mdi:battery
            {% elif battery_round > 0 %}
              mdi:battery-{{ battery_round }}
            {% else %}
              mdi:battery-alert
            {% endif %}
          {% endif %}

      iphone_battery:
        entity_id: device_tracker.dale_iphone_ios
        value_template: "{{ (states.device_tracker.dale_iphone_ios.attributes|default).battery|default|int('unknown') }}"
        unit_of_measurement: '%'
        icon_template: >-
          {% set battery_state = states('sensor.iphone_battery_state')|lower %}
          {% set battery_level = states('sensor.iphone_battery_level')|int('unknown') %}
          {% set battery_round = (battery_level|int / 10)|int * 10 %}

          {% if battery_level == 'unknown' %}
            mdi:battery-unknown
          {% elif battery_state == 'charging' %}
            {% if battery_round < 20 %}
              {% set battery_round = 20 %}
            {% elif battery_round == 50 %}
              {% set battery_round = 60 %}
            {% elif battery_round == 70 %}
              {% set battery_round = 80 %}
            {% endif %}

            mdi:battery-charging-{{ battery_round }}
          {% else %}
            {% if battery_round >= 100 %}
              mdi:battery
            {% elif battery_round > 0 %}
              mdi:battery-{{ battery_round }}
            {% else %}
              mdi:battery-alert
            {% endif %}
          {% endif %}

      kitchen_motion_battery:
        entity_id: zwave.kitchen
        value_template: "{{ (states.zwave.kitchen.attributes|default).battery_level|default|int('unknown') }}"
        unit_of_measurement: '%'
        icon_template: >-
          {% set battery_level = states('sensor.kitchen_motion_battery')|int('unknown') %}
          {% if battery_level == 'unknown' %}
            mdi:battery-unknown
          {% else %}
            {% set battery_round = (battery_level|int / 10)|int * 10 %}
            {% if battery_round >= 100 %}
              mdi:battery
            {% elif battery_round > 0 %}
              mdi:battery-{{ battery_round }}
            {% else %}
              mdi:battery-alert
            {% endif %}
          {% endif %}

      master_bathroom_motion_battery:
        entity_id: zwave.master_bathroom
        value_template: "{{ (states.zwave.master_bathroom.attributes|default).battery_level|default|int('unknown') }}"
        unit_of_measurement: '%'
        icon_template: >-
          {% set battery_level = states('sensor.master_bathroom_motion_battery')|int('unknown') %}
          {% if battery_level == 'unknown' %}
            mdi:battery-unknown
          {% else %}
            {% set battery_round = (battery_level|int / 10)|int * 10 %}
            {% if battery_round >= 100 %}
              mdi:battery
            {% elif battery_round > 0 %}
              mdi:battery-{{ battery_round }}
            {% else %}
              mdi:battery-alert
            {% endif %}
          {% endif %}

      master_bedroom_siren_battery:
        entity_id: zwave.master_bedroom_siren
        value_template: "{{ (states.zwave.master_bedroom_siren.attributes|default).battery_level|default|int('unknown') }}"
        unit_of_measurement: '%'
        icon_template: >-
          {% set battery_level = states('sensor.master_bedroom_siren_battery')|int('unknown') %}
          {% if battery_level == 'unknown' %}
            mdi:battery-unknown
          {% else %}
            {% set battery_round = (battery_level|int / 10)|int * 10 %}
            {% if battery_round >= 100 %}
              mdi:battery
            {% elif battery_round > 0 %}
              mdi:battery-{{ battery_round }}
            {% else %}
              mdi:battery-alert
            {% endif %}
          {% endif %}
