################################################################
## Packages / Blue Iris
################################################################

homeassistant:
  customize:
    camera.amcrest_ptz:
      friendly_name: "Amcrest PTZ"
      package_file: 'packages/blueiris.yaml'

    camera.backyard:
      friendly_name: "Backyard"
      package_file: 'packages/blueiris.yaml'

    camera.driveway:
      friendly_name: "Driveway"
      package_file: 'packages/blueiris.yaml'

    camera.front_yard:
      friendly_name: "Front Yard"
      package_file: 'packages/blueiris.yaml'

    camera.garage:
      friendly_name: "Garage"
      package_file: 'packages/blueiris.yaml'

    camera.kitchen:
      friendly_name: "Kitchen"
      package_file: 'packages/blueiris.yaml'

    camera.living_room:
      friendly_name: "Living Room"
      package_file: 'packages/blueiris.yaml'

    camera.master_bedroom:
      friendly_name: "Master Bedroom"
      package_file: 'packages/blueiris.yaml'

    camera.parker_bedroom:
      friendly_name: "Parker Bedroom"
      package_file: 'packages/blueiris.yaml'

    group.cameras_indoor:
      friendly_name: "Indoor Cameras"
      haaska_hidden: true
      homebridge_hidden: true
      package_file: 'packages/blueiris.yaml'

    group.cameras_outdoor:
      friendly_name: "Outdoor Cameras"
      haaska_hidden: true
      homebridge_hidden: true
      package_file: 'packages/blueiris.yaml'

camera:
  - platform: mjpeg
    name: amcrest_ptz
    mjpeg_url: !secret blueiris_amcrest_ptz_url
    username: !secret blueiris_username
    password: !secret blueiris_password
    authentication: basic

  - platform: mjpeg
    name: backyard
    mjpeg_url: !secret blueiris_backyard_url
    username: !secret blueiris_username
    password: !secret blueiris_password
    authentication: basic

  - platform: mjpeg
    name: driveway
    mjpeg_url: !secret blueiris_driveway_url
    username: !secret blueiris_username
    password: !secret blueiris_password
    authentication: basic

  - platform: mjpeg
    name: front_yard
    mjpeg_url: !secret blueiris_front_yard_url
    username: !secret blueiris_username
    password: !secret blueiris_password
    authentication: basic

  - platform: mjpeg
    name: garage
    mjpeg_url: !secret blueiris_garage_url
    username: !secret blueiris_username
    password: !secret blueiris_password
    authentication: basic

  - platform: mjpeg
    name: kitchen
    mjpeg_url: !secret blueiris_kitchen_url
    username: !secret blueiris_username
    password: !secret blueiris_password
    authentication: basic

  - platform: mjpeg
    name: living_room
    mjpeg_url: !secret blueiris_living_room_url
    username: !secret blueiris_username
    password: !secret blueiris_password
    authentication: basic

  - platform: mjpeg
    name: master_bedroom
    mjpeg_url: !secret blueiris_master_bedroom_url
    username: !secret blueiris_username
    password: !secret blueiris_password
    authentication: basic

  - platform: mjpeg
    name: parker_bedroom
    mjpeg_url: !secret blueiris_parker_bedroom_url
    username: !secret blueiris_username
    password: !secret blueiris_password
    authentication: basic

group:
  cameras_indoor:
    entities:
      - camera.amcrest_ptz
      - camera.backyard
      - camera.front_yard
      - camera.garage
      - camera.kitchen
      - camera.living_room
      - camera.master_bedroom
      - camera.parker_bedroom

  cameras_outdoor:
    entities:
      - camera.driveway
