################################################################
## Packages / Blue Iris
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'blueiris'

      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

    ################################################
    ## Automation
    ################################################

    automation.notify_driveway_motion:
      <<: *customize
      friendly_name: "Driveway Motion Notification"

    ################################################
    ## Binary Sensor
    ################################################

    binary_sensor.backyard_cam_motion:
      <<: *customize
      friendly_name: "Backyard Cam Motion"
      device_class: motion

    binary_sensor.driveway_cam_motion:
      <<: *customize
      friendly_name: "Driveway Cam Motion"
      device_class: motion

    binary_sensor.front_porch_cam_motion:
      <<: *customize
      friendly_name: "Front Porch Cam Motion"
      device_class: motion

    binary_sensor.garage_cam_motion:
      <<: *customize
      friendly_name: "Garage Cam Motion"
      device_class: motion

    binary_sensor.kitchen_cam_motion:
      <<: *customize
      friendly_name: "Kitchen Cam Motion"
      device_class: motion

    binary_sensor.living_room_cam_motion:
      <<: *customize
      friendly_name: "Living Room Cam Motion"
      device_class: motion

    binary_sensor.living_room_fd_cam_motion:
      <<: *customize
      friendly_name: "Front Door Cam Motion"
      device_class: motion

    binary_sensor.master_bedroom_cam_motion:
      <<: *customize
      friendly_name: "Master Bedroom Cam Motion"
      device_class: motion

    binary_sensor.parker_bedroom_cam_motion:
      <<: *customize
      friendly_name: "Parker Bedroom Cam Motion"
      device_class: motion

    binary_sensor.safe_cam_motion:
      <<: *customize
      friendly_name: "Safe Cam Motion"
      device_class: motion

    ################################################
    ## Camera
    ################################################

    camera.backyard:
      <<: *customize
      friendly_name: "Backyard"

    camera.driveway:
      <<: *expose
      friendly_name: "Driveway"

    camera.front_porch:
      <<: *customize
      friendly_name: "Front Porch"

    camera.garage:
      <<: *customize
      friendly_name: "Garage"

    camera.kitchen:
      <<: *customize
      friendly_name: "Kitchen"

    camera.living_room:
      <<: *customize
      friendly_name: "Living Room"

    camera.master_bedroom:
      <<: *customize
      friendly_name: "Master Bedroom"

    camera.parker_bedroom:
      <<: *customize
      friendly_name: "Parker Bedroom"

    camera.safe:
      <<: *customize
      friendly_name: "Safe"

    ################################################
    ## Group
    ################################################

    group.cameras_indoor:
      <<: *customize
      friendly_name: "Indoor Cameras"

    group.cameras_outdoor:
      <<: *customize
      friendly_name: "Outdoor Cameras"

################################################
## Group
################################################

group:
  cameras_indoor:
    control: hidden
    entities:
      - camera.kitchen
      - camera.living_room
      - camera.master_bedroom
      - camera.parker_bedroom
      - camera.safe

  cameras_outdoor:
    control: hidden
    entities:
      - camera.driveway
      - camera.front_porch
      - camera.backyard
      - camera.garage

################################################
## Automation
################################################

automation:
  - alias: notify_driveway_motion
    initial_state: 'off'
    trigger:
      - platform: state
        entity_id: binary_sensor.driveway_cam_motion
    action:
      - service: script.light_control
        data_template:
          entity_id: !secret light_gateway_light
          state: "{{ trigger.to_state.state }}"
          brightness: >-
            {{ 255 if 'H' in states.binary_sensor.driveway_cam_motion.attributes.type else 3 }}
          color_name: >-
            {{ 'red' if 'H' in states.binary_sensor.driveway_cam_motion.attributes.type else 'green' }}
      - service: script.xiaomi_ringtone
        data_template:
          ringtone: >-
            {% if trigger.to_state.state == 'on' and 'H' in states.binary_sensor.driveway_cam_motion.attributes.type %}
              7
            {% else %}
              10000
            {% endif %}

################################################
## Camera
################################################

camera:
  - platform: mjpeg
    name: backyard
    mjpeg_url: !secret blueiris_backyard_url
    username: !secret blueiris_username
    password: !secret blueiris_password
    authentication: basic

  - platform: mjpeg
    name: driveway
    mjpeg_url: !secret blueiris_driveway_url
    username: !secret blueiris_username
    password: !secret blueiris_password
    authentication: basic

  - platform: mjpeg
    name: front_porch
    mjpeg_url: !secret blueiris_front_porch_url
    username: !secret blueiris_username
    password: !secret blueiris_password
    authentication: basic

  - platform: mjpeg
    name: garage
    mjpeg_url: !secret blueiris_garage_url
    username: !secret blueiris_username
    password: !secret blueiris_password
    authentication: basic

  - platform: mjpeg
    name: kitchen
    mjpeg_url: !secret blueiris_kitchen_url
    username: !secret blueiris_username
    password: !secret blueiris_password
    authentication: basic

  - platform: mjpeg
    name: living_room
    mjpeg_url: !secret blueiris_living_room_url
    username: !secret blueiris_username
    password: !secret blueiris_password
    authentication: basic

  - platform: mjpeg
    name: master_bedroom
    mjpeg_url: !secret blueiris_master_bedroom_url
    username: !secret blueiris_username
    password: !secret blueiris_password
    authentication: basic

  - platform: mjpeg
    name: parker_bedroom
    mjpeg_url: !secret blueiris_parker_bedroom_url
    username: !secret blueiris_username
    password: !secret blueiris_password
    authentication: basic

  - platform: mjpeg
    name: safe
    mjpeg_url: !secret blueiris_safe_url
    username: !secret blueiris_username
    password: !secret blueiris_password
    authentication: basic
