################################################################
## Packages / Broadlink RM Pro
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'broadlink'

      exposed: &exposed
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

    ################################################
    ## Cover
    ################################################

    cover.projection_screen:
      <<: *exposed
      friendly_name: "Projection Screen"
      icon: mdi:projector-screen

    ################################################
    ## Input Boolean
    ################################################

    input_boolean.projection_screen:
      <<: *customize
      friendly_name: "Projection Screen"
      hidden: true
      icon: mdi:projector-screen
      persistent: true

    ################################################
    ## Sensor
    ################################################

    sensor.broadlink_sensor_temperature:
      <<: *customize
      friendly_name: "Broadlink Temperature"

    ################################################
    ## Switch
    ################################################

    switch.headboard_light:
      <<: *exposed
      friendly_name: "Headboard Light"
      icon: mdi:lightbulb

################################################
## Cover
################################################

cover:
  - platform: template
    covers:
      projection_screen:
        # Open/close are inverted for the up/down icons to work as they appear
        value_template: >-
          {{ is_state('input_boolean.projection_screen', 'off') }}
        open_cover:
          - service: input_boolean.turn_off
            data:
              entity_id: input_boolean.projection_screen
          - service: broadlink.send_packet_192_168_1_7
            data:
              packet:
                - 'si40AA0kJAwkDCQMJAwkDA0kDSQNJCQMDCQNJAwkDCQNJA0kDSQNJA0kJAwNAAFuJAwkDCQMDSQAAAAA'
        close_cover:
          - service: input_boolean.turn_on
            data:
              entity_id: input_boolean.projection_screen
          - service: broadlink.send_packet_192_168_1_7
            data:
              packet:
                - 'sjc0ACQMJQwkDA0kDSMlDCQMJAwkDCQMDSQNJA0kJQwNJA0kDSQNJA0kDSMNJCQMDSMNJA0AAW4AAAAA'
        stop_cover:
          - service: broadlink.send_packet_192_168_1_7
            data:
              packet:
                - 'sh00AAwkJAwkDCQMJA0kDQwkDCQMJCQMDCQMJA0kDCQMJA0kDSQMJCQMDCQMAAFvJA0kDSQNDCQAAAAA'

################################################
## Input Boolean
################################################

input_boolean:
  projection_screen:
    initial: 'off'

################################################
## Sensor
################################################

sensor:
  - platform: broadlink
    update_interval: 60
    host: !secret broadlink_host
    mac: !secret broadlink_mac
    monitored_conditions:
      - temperature

################################################
## Switch
################################################

switch:
  - platform: broadlink
    host: !secret broadlink_host
    mac: !secret broadlink_mac
    switches:
      headboard_light:
        command_on: 'sgAuAQcREwUHERMFBhITBQcREwUHERMFBxETBQcREwUHERMFBxIHERIFEwUHERMGBxETBQe5BxETBQcSEgYGEhMECBETBQYSEgYHERMFBxETBQcREwUHEQcREwUTBgYSEgUHEhIGBroHERMFBxETBQcREwYGERMGBhISBgYSEgYGEhMFBhITBQcRBxETBRMFBxETBQcREwUHugcREwUHERMFBxESBgcREwUHERMFBxETBgYSEgUHEhIFBxIGEhMFEgYGEhIGBxETBQe5BxETBgYSEwUGEhMFBhISBgcREwUHERMFBxETBQcREwUHEQcSEgYSBgYSEgYGERMGBroHERMFBxETBQcREwYGEhIGBhETBgcREwUHERIGBhITBQcRBxESBhMFBxETBQcREwUHAAXcAAAAAAAAAAAAAA=='
        command_off: 'sgAsARIGBhISBgYSEwUGEhIGBhITBQcREwUHEhIGBhETBRMFEwYGEgYRBxISBgYSEwUGugcSEgYGERMFBxISBgYSEgYGEhIGBhITBQcREgYGEhIGEwUTBQcRBxEHEhIFBxETBQe6BhITBQYSEwUHERMFBxETBQYTEgUHERMFBxISBgYSEgYSBhIGBhIGEgcREgYGEhIGBroHERMGBhISBgYSEgYGEhIGBhITBQYSEgYGEhIGBxETBRMFEwUHEQcRBxISBgYREwUHugcREgYGEhMFBxETBQcREwUHERMFBxISBgYSEgYGEhIGEgYSBgYSBhIGEhIGBhITBQa7BhETBQcREwUHEhIFBxETBgYSEgYGEhIGBxESBgYSEgYSBhIGBxEGEgcREwUHERMFBwAF3AAAAAAAAAAAAAAAAA=='
