################################################################
## Packages / Broadlink RM Pro
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'broadlink'

      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

    ################################################
    ## Light
    ################################################

    light.headboard:
      <<: *expose
      friendly_name: "Headboard"

    ################################################
    ## Sensor
    ################################################

    sensor.broadlink_sensor_temperature:
      <<: *customize
      friendly_name: "Broadlink Temperature"

################################################
## Light
################################################

light:
  - platform: template
    lights:
      headboard:
        turn_on:
          - service: broadlink.send_packet_192_168_1_7
            data:
              packet:
                - 'sgAuAQcREwUHERMFBhITBQcREwUHERMFBxETBQcREwUHERMFBxIHERIFEwUHERMGBxETBQe5BxETBQcSEgYGEhMECBETBQYSEgYHERMFBxETBQcREwUHEQcREwUTBgYSEgUHEhIGBroHERMFBxETBQcREwYGERMGBhISBgYSEgYGEhMFBhITBQcRBxETBRMFBxETBQcREwUHugcREwUHERMFBxESBgcREwUHERMFBxETBgYSEgUHEhIFBxIGEhMFEgYGEhIGBxETBQe5BxETBgYSEwUGEhMFBhISBgcREwUHERMFBxETBQcREwUHEQcSEgYSBgYSEgYGERMGBroHERMFBxETBQcREwYGEhIGBhETBgcREwUHERIGBhITBQcRBxESBhMFBxETBQcREwUHAAXcAAAAAAAAAAAAAA=='
        turn_off:
          - service: broadlink.send_packet_192_168_1_7
            data:
              packet:
                - 'sgAsARIGBhISBgYSEwUGEhIGBhITBQcREwUHEhIGBhETBRMFEwYGEgYRBxISBgYSEwUGugcSEgYGERMFBxISBgYSEgYGEhIGBhITBQcREgYGEhIGEwUTBQcRBxEHEhIFBxETBQe6BhITBQYSEwUHERMFBxETBQYTEgUHERMFBxISBgYSEgYSBhIGBhIGEgcREgYGEhIGBroHERMGBhISBgYSEgYGEhIGBhITBQYSEgYGEhIGBxETBRMFEwUHEQcRBxISBgYREwUHugcREgYGEhMFBxETBQcREwUHERMFBxISBgYSEgYGEhIGEgYSBgYSBhIGEhIGBhITBQa7BhETBQcREwUHEhIFBxETBgYSEgYGEhIGBxESBgYSEgYSBhIGBxEGEgcREwUHERMFBwAF3AAAAAAAAAAAAAAAAA=='

################################################
## Sensor
################################################

sensor:
  - platform: broadlink
    update_interval: 60
    host: !secret broadlink_host
    mac: !secret broadlink_mac
    monitored_conditions:
      - temperature

################################################
## Switch
################################################

switch:
  - platform: broadlink
    host: !secret broadlink_host
    mac: !secret broadlink_mac
