################################################################
## Packages / Broadlink RM Pro
################################################################

automation:
  - alias: projection_screen
    trigger:
      - platform: state
        entity_id: input_select.projection_screen
    condition:
      - condition: template
        value_template: "{{ trigger.to_state.state|lower != 'idle' }}"
    action:
      - service: broadlink.send_packet_192_168_1_7
        data_template:
          packet: >-
            {% if trigger.to_state.state|lower == 'stop' %}
              sh00AAwkJAwkDCQMJA0kDQwkDCQMJCQMDCQMJA0kDCQMJA0kDSQMJCQMDCQMAAFvJA0kDSQNDCQAAAAA
            {% elif trigger.to_state.state|lower == 'down' %}
              sjc0ACQMJQwkDA0kDSMlDCQMJAwkDCQMDSQNJA0kJQwNJA0kDSQNJA0kDSMNJCQMDSMNJA0AAW4AAAAA
            {% elif trigger.to_state.state|lower == 'up' %}
              si40AA0kJAwkDCQMJAwkDA0kDSQNJCQMDCQNJAwkDCQNJA0kDSQNJA0kJAwNAAFuJAwkDCQMDSQAAAAA
            {% endif %}
      - service: input_select.select_option
        data_template:
          entity_id: "{{ trigger.to_state.entity_id }}"
          option: Idle

input_select:
  projection_screen:
    initial: Idle
    options:
      - Idle
      - Stop
      - Down
      - Up

switch:
  - platform: broadlink
    host: !secret broadlink_host
    mac: !secret broadlink_mac
    switches:
      rf_outlet_b1:
        friendly_name: RF Outlet B1
        command_on: 'eADaAAcHBwYHBwcHBwcHBwcHBgcHBwcHBwcHBwcHBgcIBgcHBwcHBggHBwYHBwcHBwcHBwcGCAYIBgcHBwcHBwcGCAYHBwcHBwcHBggHBwYHBwcHBwcHBwcHB44HFRUHFAgHFRQHCBQHFQcVFQcHFQcVBxUHFBYGCBQInAcVFQcVBwcVFAgHFQcUCBQVBwcVBxUHFQcVFQcHFAicCBUVBhUHBxUVBwcVBxQIFRQHCBQIFAgUBxUVBwcVB50HFRUGFQcHFRUHBxUHFQcVFQYIFAgUCBQIFBUHBxUHAAXcAAAAAAAAAAAAAAAAAAA='
        command_off: 'eADaAAYHBwcHBwcHBwcHBwYHCAYIBgcHBwcHBwcHBgcHBwcHBwcHBwcGCAYHBwcHBwcHBggHBwcGBwcHBwcHBwcHBggHBgcHBwcHBwcHBgcIBgcHBwcHBwcHB44HFRUHFQcHFRQHCBUHFAgUCBQVBwcVBxUHFRUHBxUHnQcVFQYVBwgUFQcHFQcVBxUHFRUGBxUIFAcVFQcHFQedBxUVBxQIBxUVBggUCBQHFQcVFQcHFQcVBxUVBwcVB50HFBUHFQcHFRUHBxQIFQcUBxYVBgcVBxUHFRUHBxUHAAXcAAAAAAAAAAAAAAAAAAA='

      rf_outlet_b2:
        friendly_name: RF Outlet B2
        command_on: 'eADaAAcHBggGCAYHBwcHBwcHBwcGBwcHBwcHBwcHBwcGCAYHBwcHBwcHBwcHBwYHBwcHBwcHBwcGCAYHBwcHBwcHBwcGCAYIBgcHBwcHBwcGCAYHBwcHBwcHB48HFBUHFQcHFRUHBxUHFQcVBhYGFhQIBhUHFRUHBxUHnQcVFAgUBwcVFQcHFQcVBxUHFQcVFAcHFQcVFQcHFQedBxUVBxQIBxUUBwcVBxUHFQcVBxUVBwcVBxUUCAYWBp0HFRUHFQcHFRQIBhUHFQcVBxUHFRUHBxUHFRQIBhYGAAXcAAAAAAAAAAAAAAAAAAA='
        command_off: 'eADaAAcHBwcHBwcHBgcHBwcHBwcHBwcHBwYHBwcHBwcHBwcHBwcGBwcHBwcHBwcHBwcGBwcHBwcHBwcHBgcHBwcHBwcHBwcHBgcHBwcHBwcHBwYIBwYHBwcHB48HFRQHFQcHFRUHBxUHFQcVBxUHFAgUFQcHFRUHBxUHnQcVFAgUBwcVFQcHFQcVBxUHFQcVBxUUCAYVFQcHFQedBxUVBxQIBxQVBwcVBxUHFQcVBxUHFRUHBxUUCAcUB50HFRUHFQcHFRQIBhUIFQcUCBQHFQcVFQcHFRUHBxUHAAXcAAAAAAAAAAAAAAAAAAA='

      rf_outlet_b3:
        friendly_name: RF Outlet B3
        command_on: 'eADaAAcHBwcHBwcHBggGBwcHBwcGCAcHBgcHBwcHBwcHBwYIBggGBwcHBwcHBwcHBggGBwcHBwcHBwcHBwcGCAYHBwcHBwcHBggGBwcHBwcHBwcHBggGBwcHB48HFRQIFAcHFRUHBxUHFRUHBxUHFQcVBxUGFhQIBhUHnQcVFQcVBwcVFAgGFgYWFAcHFQcVBxUHFQcVFQcHFQedBxUUCBQHBxUVBwcVBxUUCAYWBhYGFgYWBhUVBwcVB50HFRQIFAgHFRQHBxUHFRUHBxUHFQcVBxUHFRQIBhYGAAXcAAAAAAAAAAAAAAAAAAA='
        command_off: 'eADaAAcHBwcGBwcHBwcHBwcHBwcHBwYHBwcHBwcHBwcGCAYHBwcHBwcHBwcGCAYIBgcHBwcHBwcHBggHBgcHBwcHBwcHBwYHBwcHBwcHBwcGCAYHBwgGBwcHB48HFBUHFQcHFRUHBxUVBwYWBhYGFQgVBhUHFRUHBxUHnQcVFAgUCAcVFAcHFRUHBxUHFQcVBxUHFQcVFAgGFQedBxUVBxUHBxUUCAcVFAgGFQcVBxUHFQcVBxUVBwcVB50HFRQIFAcHFRUHBxUUCAcVBxUGFgYWBhYGFRUHBxUHAAXcAAAAAAAAAAAAAAAAAAA='

      rf_outlet_d1:
        friendly_name: RF Outlet D1
        command_on: 'eADaAAYIBgcGCAYIBggGBwYIBggGBwYIBggGCAYHBggGCAYIBggFCAYIBggFCAYIBggGBwYIBggGCAYIBQgGCAYIBggFCAYIBggFCAYIBggGCAYHBggGCAYHBo8GFhMIFAgGFhMIBhYGFgYVFAgGFgYWBhUGFgYWBhUUjwYWEwkTCAYWEwgHFQYWBhYTCAYWBhYGFQYWBhYGFhOPBhYUCBMIBhYUCAYWBRYGFhQIBhUGFgYWBhUHFQYWFI8GFRQIFAgGFhMIBhYGFQcVFAgGFQcVBhYGFgYVBhYUAAXcAAAAAAAAAAAAAAAAAAA='
        command_off: 'eADaAAYIBggFCAYIBggGCAUIBggGCAUJBQgGCAYIBQgGCAYIBQkFCQUIBggGCAUIBggGCAYHBgkFCAYIBQgGCAYIBggFCAYIBggGCAUIBggGCAYIBQgGCAYIBo4GFhMJEwgGFhMJBRYGFgYWBhUUCAYWBhUGFgYWBhYTjwYWFAgTCAYWFAcGFgYWBhYGFhMIBhYGFgYVBhYGFhSOBxUUCBMIBhYUCAYVBhYGFgYVFAgGFgYWBhUGFgYWE48GFhQIEwgGFhMJBRYGFgYWBhUUCAYWBhUGFgYWBhYTAAXcAAAAAAAAAAAAAAAAAAA='

      rf_outlet_d2:
        friendly_name: RF Outlet D2
        command_on: 'eADcAAYIBggFCQUIBggGCAUJBQgGCAUJBQkFCAYIBQkFCQUIBggFCQUJBQgGCAUJBQgGCAYIBQkFCQUIBQkFCQUJBAkFCQUIBggFCQUJBQgGCAUJBQkFCAYIBggFjwYWEwkTCAYWEwgGFgYWBRcFFgYWEwkFFwUWBhYFFxOPBhYTCRMIBhYTCAYWBhYFFwUXBRYTCQUXBRYGFgUXE48GFhMIFAgGFhMIBhYGFgYWBRYGFhMJBRYGFgYWBRcTjwYWEwkTCAYWEwgGFgYWBRYGFgYWEwkFFgYWBhYFFxMABdwAAAAAAAAAAAAAAAA='
        command_off: 'eADcAAYIBQgGCAYIBggFCAYIBggGBwYIBggGCAYIBQgGCAYIBQgGCAYIBggFCAYIBggGCAUIBggGCAYIBgcGCAYIBggFCAYIBggFCAYIBggGCAUIBggGCAYIBQgGjwYVFAgUCAYVFAgGFgYWBhUGFgYWBhUUCAYWBhYGFhOPBhYTCBQIBhYTCAYWBhYGFQYWBhYGFhMIBhYGFgYVFI8GFhMIFAgGFhMIBhYGFgYVBxUGFgYWEwgGFgYWBhYTjwYWEwgUCAYWEwgGFgYWBhUGFgYWBhYTCAYWBhYGFRQABdwAAAAAAAAAAAAAAAA='

      rf_outlet_d3:
        friendly_name: RF Outlet D3
        command_on: 'eADaAAYIBggFCQUIBggGCAUJBQgGCAYIBQgGCAYIBQkFCAYIBggFCAYIBggFCQUJBQgGCAYHBggGCAYIBggFCAYIBggFCQUIBggGCAUIBggGCAYIBQkFCAYIBY8GFhMJEwgGFhMJBRYGFhMIBhYGFgYWBhYFFgYWBhYTjwYWEwkTCAYWEwkFFgYWEwkFFgYWBhYGFgUWBhYGFhOPBhYTCRMIBhYTCQYWBRYUCAYVBhYGFgYWBRYGFgYWE48GFhMJEwkFFhMJBhYFFhQIBhYFFwUWBhYFFwUWBhYTAAXcAAAAAAAAAAAAAAAAAAA='
        command_off: 'eADaAAYHBwcGCAYIBgcGCAYIBggGBwYIBggGCAUIBggGCAUIBggGCAYIBggFCAYIBggFCAYIBggGCAUIBggGCAYHBggGCAYIBgcGCAYIBggFCAYIBggGCAYHBo8GFhMIFAgGFhMIBhYTCAYWBhYGFgYVBhYGFgYVBhYUjwYWEwgUCAYWEwgGFhMIBhYGFgYWBhUGFgYWBhUGFhSPBhUUCBQIBhYTCAYWFAcGFgYWBhYGFQYWBhYGFgUWFI8GFRQIFAgGFRQIBhYTCAYWBhYGFgYVBhYGFgYVBhYUAAXcAAAAAAAAAAAAAAAAAAA='

#       projection_screen_stop:
#         friendly_name: Projection Screen Stop
#         command_on: 'sh00AAwkJAwkDCQMJA0kDQwkDCQMJCQMDCQMJA0kDCQMJA0kDSQMJCQMDCQMAAFvJA0kDSQNDCQAAAAA'
#         command_off: 'sh00AAwkJAwkDCQMJA0kDQwkDCQMJCQMDCQMJA0kDCQMJA0kDSQMJCQMDCQMAAFvJA0kDSQNDCQAAAAA'
#
#       projection_screen_down:
#         friendly_name: Projection Screen Down
#         command_on: 'sjc0ACQMJQwkDA0kDSMlDCQMJAwkDCQMDSQNJA0kJQwNJA0kDSQNJA0kDSMNJCQMDSMNJA0AAW4AAAAA'
#         command_off: 'sjc0ACQMJQwkDA0kDSMlDCQMJAwkDCQMDSQNJA0kJQwNJA0kDSQNJA0kDSMNJCQMDSMNJA0AAW4AAAAA'
#
#       projection_screen_up:
#         friendly_name: Projection Screen Up
#         command_on: 'si40AA0kJAwkDCQMJAwkDA0kDSQNJCQMDCQNJAwkDCQNJA0kDSQNJA0kJAwNAAFuJAwkDCQMDSQAAAAA'
#         command_off: 'si40AA0kJAwkDCQMJAwkDA0kDSQNJCQMDCQNJAwkDCQNJA0kDSQNJA0kJAwNAAFuJAwkDCQMDSQAAAAA'
