################################################################
## Packages / Configurator Panel
################################################################

panel_iframe:
  configurator:
    title: 'Configurator'
    url: !secret panel_configurator_url
    icon: mdi:wrench
