################################################################
## Packages / Customizer
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'customizer'

      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

  ################################################
  ## Customize Glob
  ################################################

  # customize_glob:
  #   "*.*":
  #     custom_ui_state_card: custom-ui

customizer:
  custom_ui: hosted
