################################################################
## Packages / Dash Buttons
################################################################

# Dash Button Topics:
#   dash-button/bounty
#   dash-button/dixie
#   dash-button/finish
#   dash-button/gatorade
#   dash-button/hefty
#   dash-button/tide
#   dash-button/ziploc

automation:
  - alias: toggle_master_bathroom_shower_mode
    trigger:
      - platform: mqtt
        topic: dash-button/ziploc
        payload: 'active'
    action:
      - service: input_boolean.toggle
        entity_id: input_boolean.shower_mode
