################################################################
## Packages / ecobee
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'ecobee'

      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

    ################################################
    ## Binary Sensor
    ################################################

    binary_sensor.guest_bedroom_occupancy:
      <<: *expose
      friendly_name: "Guest Bedroom Occupancy"
      device_class: occupancy

    binary_sensor.home_occupancy:
      <<: *expose
      friendly_name: "Hallway Occupancy"
      device_class: occupancy

    binary_sensor.living_room_occupancy:
      <<: *expose
      friendly_name: "Living Room Occupancy"
      device_class: occupancy

    binary_sensor.master_bedroom_occupancy:
      <<: *expose
      friendly_name: "Master Bedroom Occupancy"
      device_class: occupancy

    ################################################
    ## Climate
    ################################################

    climate.home:
      <<: *expose
      friendly_name: "Home"
      icon: mdi:nest-thermostat

    ################################################
    ## Sensor
    ################################################

    sensor.guest_bedroom_temperature:
      <<: *expose
      friendly_name: "Guest Bedroom Temperature"
      icon: mdi:thermometer

    sensor.home_humidity:
      <<: *expose
      friendly_name: "Home Humidity"
      icon: mdi:water-percent

    sensor.home_temperature:
      <<: *expose
      friendly_name: "Home Temperature"
      icon: mdi:thermometer

    sensor.living_room_temperature:
      <<: *expose
      friendly_name: "Living Room Temperature"
      icon: mdi:thermometer

    sensor.master_bedroom_temperature:
      <<: *expose
      friendly_name: "Master Bedroom Temperature"
      icon: mdi:thermometer

################################################
## ecobee
################################################

ecobee:
  api_key: !secret ecobee_api_key
  hold_temp: true
