################################################################
## Packages / EventGhost
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    automation.toggle_security_monitor:
      friendly_name: Toggle Security Monitor
      haaska_hidden: true
      homebridge_hidden: true
      package: 'eventghost'

    automation.smartthings_button_held:
      friendly_name: SmartThings Button Held
      haaska_hidden: true
      homebridge_hidden: true
      package: 'eventghost'

    switch.eventghost_blueiris:
      friendly_name: "Blue Iris"
      haaska_hidden: false
      homebridge_hidden: false
      icon: mdi:camcorder
      package: 'eventghost'

    switch.eventghost_monitor:
      friendly_name: "Security Monitor"
      haaska_hidden: false
      homebridge_hidden: false
      icon: mdi:monitor
      package: 'eventghost'

################################################
## Automation
################################################

automation:
  - alias: toggle_security_monitor
    # initial_state: 'on'
    trigger:
      - platform: mqtt
        topic: smartthings/network_cabinet/button
        payload: 'pushed'
    condition:
      - condition: state
        entity_id: binary_sensor.system_ready
        state: 'on'
    action:
      - service: switch.toggle
        data:
          entity_id: switch.eventghost_monitor

  - alias: smartthings_button_held
    # initial_state: 'on'
    trigger:
      - platform: mqtt
        topic: smartthings/network_cabinet/button
        payload: 'held'
    condition:
      - condition: state
        entity_id: binary_sensor.system_ready
        state: 'on'
    action:
      - service: notify.syslog
        data:
          message: SmartThings button was held.

################################################
## Switch
################################################

switch:
  - platform: command_line
    switches:
      eventghost_blueiris:
        command_on: >-
          /usr/bin/curl -sS -X POST -d '{"method": "TriggerEvent", "args": ["BlueIris.Show"]}' $EVENTGHOST_URL > /dev/null
        command_off: >-
          /usr/bin/curl -sS -X POST -d '{"method": "TriggerEvent", "args": ["BlueIris.Hide"]}' $EVENTGHOST_URL > /dev/null
        command_state: >-
          /usr/bin/curl -sS -X POST -d '{"method": "GetPersistentValue", "args": ["BlueIris.State"]}' $EVENTGHOST_URL
        value_template: "{{ value_json == 'On' }}"

      eventghost_monitor:
        command_on: >-
          /usr/bin/curl -sS -X POST -d '{"method": "TriggerEvent", "args": ["Monitor.On"]}' $EVENTGHOST_URL > /dev/null
        command_off: >-
          /usr/bin/curl -sS -X POST -d '{"method": "TriggerEvent", "args": ["Monitor.Off"]}' $EVENTGHOST_URL > /dev/null
        command_state: >-
          /usr/bin/curl -sS -X POST -d '{"method": "GetPersistentValue", "args": ["Monitor.State"]}' $EVENTGHOST_URL
        value_template: "{{ value_json == 'On' }}"
