################################################################
## Packages / Flux LED
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'flux_led'

      exposed: &exposed
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

      hidden: &hidden
        <<: *customize
        hidden: true

    ################################################
    ## Light
    ################################################

    light.rack_light:
      <<: *exposed
      friendly_name: "Rack Light"
      persistent: true

################################################
## Light
################################################

light:
  - platform: flux_led
    devices:
      !secret flux_led_rack_light_host:
        name: rack_light
        protocol: 'ledenet'
        mode: 'rgb'
