################################################################
## Packages / Garage
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'garage'

      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

    ################################################
    ## Alert
    ################################################

    alert.garage_door_open:
      <<: *customize
      friendly_name: "Garage Door Open"
      speech: "Hey you, your garage door is open."

    ################################################
    ## Automation
    ################################################

    automation.garage_door_lighting:
      <<: *expose
      friendly_name: "Garage Door Lighting"
      icon: mdi:garage

    ################################################
    ## Cover
    ################################################

    cover.garage_door:
      <<: *expose
      friendly_name: "Garage Door"
      device_class: garage
      homebridge_cover_type: garage_door

    ################################################
    ## Light
    ################################################

    light.garage_light:
      <<: *expose
      friendly_name: "Garage Light"
      persistent: true

################################################
## Alert
################################################

alert:
  garage_door_open:
    name: garage_door_open
    entity_id: cover.garage_door
    state: 'open'
    repeat:
      - 5
      - 10
      - 15
      - 30
    can_acknowledge: true
    skip_first: false
    notifiers:
      - tts_alerts

################################################
## Automation
################################################

automation:
  - alias: garage_door_lighting
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: cover.garage_door
        from: 'closed'
        to: 'open'
      - platform: state
        entity_id: cover.garage_door
        from: 'open'
        to: 'closed'
        for: '00:05:00'
    action:
      - service: script.light_control
        data_template:
          entity_id: light.garage_light

################################################
## Cover
################################################

cover:
  - platform: myq
    username: !secret myq_username
    password: !secret myq_password
    type: 'liftmaster'
