################################################################
## Packages / Garage
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'garage'

      exposed: &exposed
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

    ################################################
    ## Alert
    ################################################

    alert.garage_door_open:
      <<: *customize
      friendly_name: "Garage Door Open"
      speech: "Hey you, your garage door is open."

    ################################################
    ## Automation
    ################################################

    automation.garage_door_lighting:
      <<: *exposed
      friendly_name: "Garage Door Lighting"

    ################################################
    ## Binary Sensor
    ################################################

    binary_sensor.garage_light_expected_state:
      <<: *customize
      friendly_name: "Garage Light Expected State"
      device_class: light
      hidden: true

    ################################################
    ## Cover
    ################################################

    cover.garage_door:
      <<: *exposed
      friendly_name: "Garage Door"
      homebridge_cover_type: garage_door
      icon: mdi:glassdoor

    ################################################
    ## Light
    ################################################

    light.garage:
      <<: *exposed
      friendly_name: "Garage"
      persistent: true

    ################################################
    ## Input Boolean
    ################################################

    # input_boolean.garage_light:
    #   <<: *customize
    #   friendly_name: "Garage Light"
    #   hidden: true

################################################
## Alert
################################################

alert:
  garage_door_open:
    name: garage_door_open
    entity_id: cover.garage_door
    state: 'open'
    repeat:
      - 5
      - 10
      - 15
      - 30
    can_acknowledge: true
    skip_first: false
    notifiers:
      - tts_alerts

################################################
## Automation
################################################

automation:
  - alias: garage_door_lighting
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: cover.garage_door
        from: 'closed'
        to: 'open'
      - platform: state
        entity_id: cover.garage_door
        from: 'open'
        to: 'closed'
        for: '00:05:00'
    action:
      - service: script.light_control
        data_template:
          entity_id: light.garage

################################################
## Binary Sensor
################################################

binary_sensor:
  - platform: template
    sensors:
      garage_light_expected_state:
        value_template: >-
          {{ true in (
            is_state('cover.garage_door', 'open'),
            is_state('input_boolean.garage_light', 'on')
          ) }}

################################################
## Cover
################################################

cover:
  - platform: myq
    username: !secret myq_username
    password: !secret myq_password
    type: 'liftmaster'

################################################
## Input Boolean
################################################

# input_boolean:
#   garage_light:
