################################################################
## Packages / Google Cast
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'google_cast'

      exposed: &exposed
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

      hidden: &hidden
        <<: *customize
        hidden: true

    ################################################
    ## Media Player
    ################################################

    media_player.bedroom_speakers:
      <<: *customize
      friendly_name: "Bedroom Speakers"
      icon: mdi:google-chrome

    media_player.dining_room_home:
      <<: *customize
      friendly_name: "Dining Room Home"
      icon: mdi:google-chrome

    media_player.living_room_speakers:
      <<: *customize
      friendly_name: "Living Room Speakers"
      icon: mdi:google-chrome

################################################
## Media Player
################################################

media_player:
  - platform: cast
    name: dining_room_home
    host: !secret google_cast_dining_room_host

  - platform: cast
    name: living_room_speakers
    host: !secret google_cast_living_room_host

  - platform: cast
    name: master_bedroom_speakers
    host: !secret google_cast_master_bedroom_host

  - platform: cast
