################################################################
## Package / HAASKA
################################################################

################################################
## Customize
################################################

homeassistant:
  customize_domain:
    alert:
      haaska_hidden: false

    # automation:
    #   haaska_hidden: true

    # camera:
    #   haaska_hidden: true

    # climate:
    #   haaska_hidden: true

    cover:
      haaska_hidden: false

    # fan:
    #   haaska_hidden: true

    # group:
    #   haaska_hidden: true

    # input_boolean:
    #   haaska_hidden: true

    # input_slider:
    #   haaska_hidden: true

    # light:
    #   haaska_hidden: true

    lock:
      haaska_hidden: false

    media_player:
      haaska_hidden: false

    # scene:
    #   haaska_hidden: true

    # script:
    #   haaska_hidden: true

    # switch:
    #   haaska_hidden: true
