################################################################
## Packages / Harmony Hub
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    packages.harmony: &customize
      package: 'harmony'

    packages.harmony_exposed: &customize_exposed
      <<: *customize
      haaska_hidden: false
      homebridge_hidden: false

    packages.harmony_contained: &customize_contained
      <<: *customize
      haaska_hidden: true
      homebridge_hidden: true

    automation.toggle_apple_tv:
      <<: *customize_contained
      friendly_name: "Toggle Apple TV"

    remote.living_room:
      <<: *customize_contained
      friendly_name: "Living Room"
      hidden: true
      icon: mdi:remote

    script.harmony_activity:
      <<: *customize_contained
      friendly_name: "Harmony Activity"
      icon: mdi:remote

    switch.apple_tv:
      <<: *customize_exposed
      friendly_name: "Apple TV"
      icon: mdi:apple

    switch.chromecast:
      <<: *customize_exposed
      friendly_name: "Chromecast"
      icon: mdi:google-chrome

    switch.computer:
      <<: *customize_exposed
      friendly_name: "Computer"
      icon: mdi:windows

    switch.fire_tv:
      <<: *customize_exposed
      friendly_name: "Fire TV"
      icon: mdi:amazon

    switch.xbox:
      <<: *customize_exposed
      friendly_name: "Xbox"
      icon: mdi:xbox

################################################
## Automation
################################################

automation:
  - alias: toggle_apple_tv
    # initial_state: 'on'
    trigger:
      - platform: event
        event_type: click
        event_data:
          entity_id: !secret binary_sensor_xiaomi_button
          click_type: single
    condition:
      - condition: template
        value_template: "{{ states.automation.toggle_apple_tv.attributes is not none }}"
      - condition: or
        conditions:
          - condition: template
            value_template: "{{ states.automation.toggle_apple_tv.attributes.last_triggered is none }}"
          - condition: template
            value_template: "{{ as_timestamp(now()) - as_timestamp(states.automation.toggle_apple_tv.attributes.last_triggered) > 30 }}"
    action:
      - service: switch.toggle
        data:
          entity_id: switch.apple_tv

################################################
## Remote
################################################

remote:
  - platform: harmony
    name: living_room
    host: !secret harmony_host
    activity: !secret harmony_activity_watch_apple_tv

################################################
## Script
################################################

script:
  harmony_activity:
    sequence:
      - service: switch.turn_on
        data_template:
          entity_id: "switch.projection_screen_{{ screen|default('up') }}"
      - service: remote.turn_on
        data_template:
          entity_id: "{{ entity_id|default('remote.living_room') }}"
          activity: "{{ activity|default(-1) }}"

################################################
## Switch
################################################

switch:
  - platform: template
    switches:
      apple_tv:
        value_template: "{{ is_state_attr('remote.living_room', 'current_activity', 'Watch Apple TV') or False }}"
        turn_on:
          - service: script.harmony_activity
            data:
              activity: !secret harmony_activity_watch_apple_tv
              screen: 'down'
        turn_off:
          - service: script.harmony_activity

      chromecast:
        value_template: "{{ is_state_attr('remote.living_room', 'current_activity', 'Listen to Music') or False }}"
        turn_on:
          - service: script.harmony_activity
            data:
              activity: !secret harmony_activity_listen_to_music
              screen: 'up'
        turn_off:
          - service: script.harmony_activity

      computer:
        value_template: "{{ is_state_attr('remote.living_room', 'current_activity', 'Watch PC') or False }}"
        turn_on:
          - service: script.harmony_activity
            data:
              activity: !secret harmony_activity_watch_pc
              screen: 'down'
        turn_off:
          - service: script.harmony_activity

      fire_tv:
        value_template: "{{ is_state_attr('remote.living_room', 'current_activity', 'Watch Fire TV') or False }}"
        turn_on:
          - service: script.harmony_activity
            data:
              activity: !secret harmony_activity_watch_fire_tv
              screen: 'down'
        turn_off:
          - service: script.harmony_activity

      xbox:
        value_template: "{{ is_state_attr('remote.living_room', 'current_activity', 'Play a Game') or False }}"
        turn_on:
          - service: script.harmony_activity
            data:
              activity: !secret harmony_activity_play_a_game
              screen: 'down'
        turn_off:
          - service: script.harmony_activity
