################################################################
## Packages / IKEA Trådfri
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    packages.ikea_tradfri: &customize
      package: 'ikea_tradfri'

    packages.ikea_tradfri_exposed: &customize_exposed
      <<: *customize
      haaska_hidden: false
      homebridge_hidden: false

    packages.ikea_tradfri_contained: &customize_contained
      <<: *customize
      haaska_hidden: true
      homebridge_hidden: true

    light.tradfri_bulb_e12_ws_opal_400lm:
      <<: *customize_exposed
      friendly_name: "Flower Lamp"

    light.tradfri_bulb_e26_opal_1000lm:
      <<: *customize_exposed
      friendly_name: "Warm white bulb"

    light.tradfri_bulb_e26_opal_1000lm_2:
      <<: *customize_exposed
      friendly_name: "Warm white bulb 2"

    light.tradfri_bulb_e26_ws_opal_980lm_2:
      <<: *customize_exposed
      friendly_name: "White spectrum bulb 2"

tradfri:
  host: !secret tradfri_host
  api_key: !secret tradfri_api_key
