################################################################
## Packages / LimitlessLED
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'limitless_led'

      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

################################################
## Light
################################################

light:
  - platform: limitlessled
    bridges:
      - host: !secret limitlessled_host
        version: 5
        port: 8899
        groups:
        - number: 1
          type: rgbw
          name: garage_light
