################################################################
## Packages / Media Lights
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'media_lights'

      exposed: &exposed
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

    ################################################
    ## Automation
    ################################################

    automation.media_lighting:
      <<: *exposed
      friendly_name: "Media Lighting"
      icon: mdi:movie-roll

    ################################################
    ## Binary Sensor
    ################################################

    binary_sensor.media_lights_expected_state:
      <<: *customize
      friendly_name: "Media Lights Expected State"
      device_class: light
      hidden: true

    ################################################
    ## Group
    ################################################

    group.media_lights:
      <<: *customize
      friendly_name: "Media Lights"
      icon: mdi:lightbulb

################################################
## Automation
################################################

automation:
  - alias: media_lighting
    trigger:
      - platform: state
        entity_id: binary_sensor.media_lights_expected_state
    action:
      - service: script.light_control
        data:
          entity_id: group.media_lights

################################################
## Group
################################################

group:
  media_lights:
    entities:
      - light.entry_lamp
      - light.living_room
      - light.dining_room

################################################
## Binary Sensor
################################################

binary_sensor:
  - platform: template
    sensors:
      media_lights_expected_state:
        value_template: >-
          {{ not is_state('media_player.apple_tv_living_room', 'playing') }}
