################################################################
## Packages / Morning Lights
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'morning_lights'

      exposed: &exposed
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

    ################################################
    ## Automation
    ################################################

    automation.morning_lighting:
      <<: *exposed
      friendly_name: "Morning Lighting"
      icon: mdi:weather-sunset-up

    ################################################
    ## Group
    ################################################

    group.morning_lights:
      <<: *exposed
      friendly_name: "Morning Lights"
      icon: mdi:weather-sunset-up

################################################
## Group
################################################

group:
  morning_lights:
    entities:
      - light.dining_room
      - light.entry_lamp
      - light.master_bedroom

################################################
## Automation
################################################

automation:
  - alias: morning_lighting
    initial_state: 'on'
    trigger:
      - platform: time
        at: '06:30:00'
    condition:
      - condition: state
        entity_id: group.person_dale
        state: 'home'
    action:
      - service: script.light_control
        data:
          entity_id: group.morning_lights
          state: 'on'
          brightness: 255
          color_temp: 154
          transition: 900
