################################################################
## Package / Motion Lights
################################################################

homeassistant:
  customize:
    packages.motion_lights: &customize
      haaska_hidden: false
      homebridge_hidden: false
      icon: mdi:walk
      package_file: 'packages/motion_lights.yaml'

    automation.dining_room_motion:
      <<: *customize
      friendly_name: "Dining Room Motion"

    automation.kitchen_motion:
      <<: *customize
      friendly_name: "Kitchen Motion"

    automation.master_bathroom_motion:
      <<: *customize
      friendly_name: "Bathroom Motion"

automation:
  - alias: dining_room_motion
    trigger:
      - platform: state
        entity_id: binary_sensor.motion_sensor_158d00012d71be
        to: 'on'
      - platform: state
        entity_id: binary_sensor.motion_sensor_158d00012d71be
        to: 'off'
        for: '00:04:00'
    action:
      - service: script.light_control
        data_template:
          entity_id: light.dining_room
          state: "{{ trigger.to_state.state }}"

  - alias: kitchen_motion
    trigger:
      - platform: state
        entity_id: binary_sensor.kitchen_sensor_5_0
        to: 'on'
      - platform: state
        entity_id: binary_sensor.kitchen_sensor_5_0
        to: 'off'
        for: '00:04:00'
    action:
      - service: script.light_control
        data_template:
          entity_id: light.kitchen
          state: "{{ trigger.to_state.state }}"

  - alias: master_bathroom_motion
    trigger:
      - platform: state
        entity_id: binary_sensor.master_bathroom_sensor_4_0
        to: 'on'
      - platform: state
        entity_id: binary_sensor.master_bathroom_sensor_4_0
        to: 'off'
        for: '00:04:00'
    action:
      - service: script.light_control
        data_template:
          entity_id: light.master_bathroom
          state: "{{ trigger.to_state.state }}"
