################################################################
## Packages / Nap Time
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'nap_time'

      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

    ################################################
    ## Script
    ################################################

    script.nap_time:
      <<: *customize
      friendly_name: "Nap Time"
      icon: mdi:sleep

################################################
## Script
################################################

script:
  nap_time:
    sequence:
      - service: remote.send_command
        data:
          entity_id: remote.living_room
          device: 38739413
          command: 'Pause'
      - service: script.say
        data_template:
          message: >-
            {% if is_state('switch.apple_tv', 'on') %}
              It is time to take a nap. Please turn off the Apple TV and go lie down.
            {% else %}
              It is time to take a nap. Please go lie down and take a nap.
            {% endif %}
      - delay: '00:01:00'
      - condition: state
        entity_id: switch.apple_tv
        state: 'on'
      - service: script.say
        data:
          message: "I am now turning off the Apple TV for you. Enjoy your nap!"
      - service: switch.turn_off
        data:
          entity_id: switch.apple_tv
