################################################################
## Packages / Philips Hue
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'philips_hue'

      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

    ################################################
    ## Hidden Lights
    ################################################

    light.back_porch_light:
      <<: *customize
      friendly_name: "Back Porch Light"
      hidden: true

    light.chandelier_light_1:
      <<: *customize
      friendly_name: "Chandelier Light 1"
      hidden: true

    light.chandelier_light_2:
      <<: *customize
      friendly_name: "Chandelier Light 2"
      hidden: true

    light.chandelier_light_3:
      <<: *customize
      friendly_name: "Chandelier Light 3"
      hidden: true

    light.dining_room_light_1:
      <<: *customize
      friendly_name: "Dining Room Light 1"
      hidden: true

    light.dining_room_light_2:
      <<: *customize
      friendly_name: "Dining Room Light 2"
      hidden: true

    light.entry:
      <<: *customize
      friendly_name: "Entry"
      hidden: true

    light.entry_light_1:
      <<: *customize
      friendly_name: "Entry Light 1"
      hidden: true

    light.entry_light_2:
      <<: *customize
      friendly_name: "Entry Light 2"
      hidden: true

    light.front_porch_light:
      <<: *customize
      friendly_name: "Front Porch Light"
      hidden: true

    light.garage:
      <<: *customize
      friendly_name: "Garage"
      hidden: true

    light.garage_opener_light_1:
      <<: *customize
      friendly_name: "Garage Opener Light 1"
      hidden: true

    light.garage_opener_light_2:
      <<: *customize
      friendly_name: "Garage Opener Light 2"
      hidden: true

    light.guest_bathroom_light_1:
      <<: *customize
      friendly_name: "Guest Bathroom Light 1"
      hidden: true

    light.guest_bathroom_light_2:
      <<: *customize
      friendly_name: "Guest Bathroom Light 2"
      hidden: true

    light.guest_bedroom_light:
      <<: *customize
      friendly_name: "Guest Bedroom Light"
      hidden: true

    light.hallway_light:
      <<: *customize
      friendly_name: "Hallway Light"
      hidden: true

    light.kitchen:
      <<: *customize
      friendly_name: "Kitchen"
      hidden: true

    light.laundry_room_light:
      <<: *customize
      friendly_name: "Laundry Room Light"
      hidden: true

    light.living_room_light_1:
      <<: *customize
      friendly_name: "Living Room Light 1"
      hidden: true

    light.living_room_light_2:
      <<: *customize
      friendly_name: "Living Room Light 2"
      hidden: true

    light.master_bathroom_light_1:
      <<: *customize
      friendly_name: "Master Bathroom Light 1"
      hidden: true

    light.master_bathroom_light_2:
      <<: *customize
      friendly_name: "Master Bathroom Light 2"
      hidden: true

    light.master_bedroom_light_1:
      <<: *customize
      friendly_name: "Master Bedroom Light 1"
      hidden: true

    light.master_bedroom_light_2:
      <<: *customize
      friendly_name: "Master Bedroom Light 2"
      hidden: true

    light.master_closet_light:
      <<: *customize
      friendly_name: "Master Closet Light"
      hidden: true

    light.parker_closet_light:
      <<: *customize
      friendly_name: "Parker Closet Light"
      hidden: true

    ################################################
    ## Visible Lights
    ################################################

    light.back_porch:
      <<: *customize
      friendly_name: "Back Porch"

    light.chandelier:
      <<: *customize
      friendly_name: "Chandelier"

    light.dining_room:
      <<: *customize
      friendly_name: "Dining Room"

    light.entry_lamp:
      <<: *customize
      friendly_name: "Entry Lamp"

    light.front_porch:
      <<: *customize
      friendly_name: "Front Porch"

    light.garage_opener:
      <<: *customize
      friendly_name: "Garage Opener"

    light.guest_bathroom:
      <<: *customize
      friendly_name: "Guest Bathroom"

    light.guest_bedroom:
      <<: *customize
      friendly_name: "Guest Bedroom"

    light.hallway:
      <<: *customize
      friendly_name: "Hallway"

    light.laundry_room:
      <<: *customize
      friendly_name: "Laundry Room"

    light.living_room:
      <<: *customize
      friendly_name: "Living Room"

    light.master_bathroom:
      <<: *customize
      friendly_name: "Master Bathroom"

    light.master_bedroom:
      <<: *customize
      friendly_name: "Master Bedroom"

    light.master_closet:
      <<: *customize
      friendly_name: "Master Closet"

    light.parker_closet:
      <<: *customize
      friendly_name: "Parker Closet"

    light.range_light:
      <<: *customize
      friendly_name: "Range"

    light.sink_light:
      <<: *customize
      friendly_name: "Sink"

    ################################################
    ## Automation
    ################################################

    automation.hue_master_bedroom_dimmer_good_morning_good_night:
      <<: *customize
      friendly_name: "Hue Master Bedroom Dimmer Good Morning Good Night"

    automation.hue_master_bedroom_dimmer_motion_on_motion_off:
      <<: *customize
      friendly_name: "Hue Master Bedroom Dimmer Motion On Motion Off"

    ################################################
    ## Binary Sensor
    ################################################

    binary_sensor.guest_bathroom_motion:
      <<: *customize
      friendly_name: "Guest Bathroom Motion"
      device_class: motion

    ################################################
    ## Sensor
    ################################################

    sensor.guest_bathroom_lux:
      <<: *customize
      friendly_name: "Guest Bathroom Lux"

    sensor.guest_bathroom_temperature:
      <<: *customize
      friendly_name: "Guest Bathroom Temperature"

    sensor.dining_room_dimmer:
      <<: *customize
      friendly_name: "Dining Room Dimmer"
      hidden: true

    sensor.guest_bedroom_dimmer:
      <<: *customize
      friendly_name: "Guest Bedroom Dimmer"
      hidden: true

    sensor.master_bedroom_dimmer:
      <<: *customize
      friendly_name: "Master Bedroom Dimmer"
      hidden: true

    # sensor.parker_bedroom_tap:
    #   <<: *customize
    #   friendly_name: "Parker Bedroom Tap"

################################################
## Light
################################################

light:
  - platform: hue
    filename: !secret hue_filename
    host: !secret hue_host
    allow_hue_groups: true
    allow_unreachable: true

################################################
## Automation
################################################

automation:
  - alias: hue_master_bedroom_dimmer_good_morning_good_night
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: sensor.master_bedroom_dimmer
        to: 'hold_1'
      - platform: state
        entity_id: sensor.master_bedroom_dimmer
        to: 'hold_4'
    action:
      - service: script.turn_on
        data_template:
          entity_id: >-
            script.good_{{ 'night' if trigger.to_state.state == 'hold_4' else 'morning' }}

  - alias: hue_master_bedroom_dimmer_motion_on_motion_off
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: sensor.master_bedroom_dimmer
        to: 'hold_2'
      - platform: state
        entity_id: sensor.master_bedroom_dimmer
        to: 'hold_3'
    action:
      - service_template: >-
          automation.turn_{{ 'on' if trigger.to_state.state == 'hold_2' else 'off' }}
        data:
          entity_id: automation.master_bedroom_motion

################################################
## Binary Sensor
################################################

binary_sensor:
  - platform: rest
    name: guest_bathroom_motion
    resource: !secret hue_url_guest_bathroom_motion
    scan_interval: 2
    value_template: >-
      {{ value_json.state.presence }}

################################################
## Sensor
################################################

sensor:
  ################################################
  ## Dining Room
  ################################################

  - platform: rest
    name: dining_room_dimmer
    resource: !secret hue_url_dining_room_dimmer
    scan_interval: 2
    value_template: >-
      {% set last_updated = as_timestamp(value_json.state.lastupdated ~ '-00:00')|int %}
      {% if as_timestamp(now())|int - last_updated > 10 %}
        idle
      {% else %}
        {% set button_event = value_json.state.buttonevent|string %}
        {{ ('hold' if button_event[3]|int % 2 == 1 else 'click') ~ '_' ~ button_event[0] }}
      {% endif %}

  ################################################
  ## Guest Bathroom
  ################################################

  - platform: rest
    name: guest_bathroom_lux
    resource: !secret hue_url_guest_bathroom_lux
    scan_interval: 10
    unit_of_measurement: Lux
    value_template: >-
      {{ value_json.state.lightlevel }}

  - platform: rest
    name: guest_bathroom_temperature
    resource: !secret hue_url_guest_bathroom_temperature
    scan_interval: 60
    unit_of_measurement: '°C'
    value_template: >-
      {{ value_json.state.temperature|float / 100 }}

  ################################################
  ## Guest Bedroom
  ################################################

  - platform: rest
    name: guest_bedroom_dimmer
    resource: !secret hue_url_guest_bedroom_dimmer
    scan_interval: 2
    value_template: >-
      {% set last_updated = as_timestamp(value_json.state.lastupdated ~ '-00:00')|int %}
      {% if as_timestamp(now())|int - last_updated > 10 %}
        idle
      {% else %}
        {% set button_event = value_json.state.buttonevent|string %}
        {{ ('hold' if button_event[3]|int % 2 == 1 else 'click') ~ '_' ~ button_event[0] }}
      {% endif %}

  ################################################
  ## Master Bedroom
  ################################################

  - platform: rest
    name: master_bedroom_dimmer
    resource: !secret hue_url_master_bedroom_dimmer
    scan_interval: 2
    value_template: >-
      {% set last_updated = as_timestamp(value_json.state.lastupdated ~ '-00:00')|int %}
      {% if as_timestamp(now())|int - last_updated > 10 %}
        idle
      {% else %}
        {% set button_event = value_json.state.buttonevent|string %}
        {{ ('hold' if button_event[3]|int % 2 == 1 else 'click') ~ '_' ~ button_event[0] }}
      {% endif %}

  ################################################
  ## Parker's Bedroom
  ################################################

  # - platform: mqtt
  #   name: parker_bedroom_tap
  #   state_topic: hue/parker_tap/buttonevent
