################################################################
## Packages / Plex
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'plex'

      contained: &contained
        <<: *customize
        haaska_hidden: true
        homebridge_hidden: true

      exposed: &exposed
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

      hidden: &hidden
        <<: *contained
        hidden: true

    ################################################
    ## Media Player
    ################################################

    media_player.plex_living_room:
      <<: *contained
      friendly_name: "Living Room (Plex)"
      icon: mdi:plex

    ################################################
    ## Sensor
    ################################################

    sensor.plex_activity:
      <<: *hidden
      friendly_name: "Plex Activity"

################################################
## Media Player
################################################

media_player:
  - platform: plex
    entity_namespace: 'plex'
    include_non_clients: false
    scan_interval: 5
    show_all_controls: false
    use_custom_entity_ids: false
    use_episode_art: true

################################################
## Sensor
################################################

sensor:
  - platform: plex
    name: plex_activity
    host: !secret plex_host
    port: !secret plex_port
    username: !secret plex_username
    password: !secret plex_password
