################################################################
## Packages / Plex
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    packages.plex: &customize
      haaska_hidden: true
      hidden: true
      package: 'plex'

    sensor.plex_activity:
      <<: *customize
      friendly_name: 'Plex Activity'

################################################
## Media Player
################################################

media_player:
  - platform: plex
    entity_namespace: 'plex'
    include_non_clients: false
    scan_interval: 5
    show_all_controls: false
    use_custom_entity_ids: false
    use_episode_art: true

################################################
## Sensor
################################################

sensor:
  - platform: plex
    name: plex_activity
    host: !secret plex_host
    port: !secret plex_port
    username: !secret plex_username
    password: !secret plex_password
