################################################################
## Packages / Presence
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'presence'

      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

    ################################################
    ## Automation
    ################################################

    automation.presence_detection:
      <<: *expose
      friendly_name: "Presence Detection"
      icon: mdi:map-marker

    ################################################
    ## Group
    ################################################

    group.arrival_lights:
      <<: *expose
      friendly_name: "Arrival Lights"
      icon: mdi:lightbulb

    ################################################
    ## Script
    ################################################

    script.arrival:
      <<: *expose
      friendly_name: "Arrival"
      icon: mdi:map-marker

    script.departure:
      <<: *expose
      friendly_name: "Departure"
      icon: mdi:map-marker-off

################################################
## Automation
################################################

automation:
  - alias: presence_detection
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: group.household
        from: 'not_home'
        to: 'home'
      - platform: state
        entity_id: group.household
        from: 'home'
        to: 'not_home'
    # condition:
    #   - condition: state
    #     entity_id: input_boolean.guest_mode
    #     state: 'off'
    action:
      - service_template: >-
          {% if trigger.to_state.state == 'home' %}
            script.arrival
          {% elif trigger.from_state.state == 'home' %}
            script.departure
          {% endif %}

################################################
## Group
################################################

group:
  arrival_lights:
    entities:
      - light.entry_lamp
      - light.laundry_room
      - light.dining_room
      - light.garage_light

################################################
## Script
################################################

script:
  arrival:
    sequence:
      # - service: script.ios_notify_arrival
      - service: cover.open_cover
        data:
          entity_id: cover.garage_door
      - service: lock.unlock
        data:
          entity_id: lock.front_door_locked
      - service: script.light_control
        data:
          # entity_id for light_control currently does not handle lists
          entity_id: group.arrival_lights
          state: 'on'
      - service: script.front_porch_light
      - service: climate.set_hold_mode
        data:
          entity_id: climate.ecobee3
          hold_mode: 'home'
      - service: switch.turn_on
        data:
          entity_id:
            - switch.eventghost_blueiris
            - switch.eventghost_monitor

  departure:
    sequence:
      - service: lock.lock
        data:
          entity_id: lock.front_door_locked
      - service: script.light_control
        data:
          entity_id: group.all_lights
          state: 'off'
      - service: script.front_porch_light
      - service: climate.set_hold_mode
        data:
          entity_id: climate.ecobee3
          hold_mode: 'away'
      - service: switch.turn_off
        data:
          entity_id: switch.eventghost_monitor
