################################################################
## Packages / Presence
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'presence'

      contained: &contained
        <<: *customize
        haaska_hidden: true
        homebridge_hidden: true

      exposed: &exposed
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

      hidden: &hidden
        <<: *contained
        hidden: true

    ################################################
    ## Automation
    ################################################

    automation.presence_detection:
      <<: *exposed
      friendly_name: "Presence Detection"
      icon: mdi:map-marker

    ################################################
    ## Group
    ################################################

    group.arrival_lights:
      <<: *exposed
      friendly_name: "Arrival Lights"
      icon: mdi:lightbulb

    ################################################
    ## Input Boolean
    ################################################

    input_boolean.guest_mode:
      friendly_name: "Guest Mode"
      icon: mdi:account

    ################################################
    ## Script
    ################################################

    script.arrival:
      <<: *exposed
      friendly_name: "Arrival"
      icon: mdi:map-marker

    script.departure:
      <<: *exposed
      friendly_name: "Departure"
      icon: mdi:map-marker-off

################################################
## Automation
################################################

automation:
  - alias: presence_detection
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: group.household
        from: 'not_home'
        to: 'home'
      - platform: state
        entity_id: group.household
        from: 'home'
        to: 'not_home'
    condition:
      - condition: state
        entity_id: input_boolean.guest_mode
        state: 'off'
    action:
      - service_template: >-
          {% if trigger.to_state.state == 'home' %}
            script.arrival
          {% elif trigger.from_state.state == 'home' %}
            script.departure
          {% endif %}

################################################
## Group
################################################

group:
  arrival_lights:
    entities:
      - light.entry_lamp
      - light.laundry_room
      - light.dining_room
      - light.garage

################################################
## Input Boolean
################################################

input_boolean:
  guest_mode:
    initial: off

################################################
## Script
################################################

script:
  arrival:
    sequence:
      - service: script.ios_notify_arrival
      - service: script.light_control
        data_template:
          # entity_id for light_control currently does not handle lists
          entity_id: group.arrival_lights
          state: 'on'
      - service: script.front_porch_light
      - service: climate.set_hold_mode
        data:
          entity_id: climate.home
          hold_mode: 'home'
      - service: switch.turn_on
        data:
          entity_id:
            - switch.eventghost_blueiris
            - switch.eventghost_monitor

  departure:
    sequence:
      - service: lock.lock
        data:
          entity_id: !secret lock_front_door
      - service: script.light_control
        data:
          entity_id: group.all_lights
          state: 'off'
      - service: script.front_porch_light
      - service: climate.set_hold_mode
        data:
          entity_id: climate.home
          hold_mode: 'away'
      - service: switch.turn_off
        data:
          entity_id: switch.eventghost_monitor
