################################################################
## Packages / SABnzbd
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'sabnzbd'

      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

    ################################################
    ## Group
    ################################################

    group.sabnzbd:
      <<: *customize
      friendly_name: "SABnzbd"
      icon: mdi:download

    ################################################
    ## Sensor
    ################################################

    sensor.sabnzbd_disk:
      <<: *customize
      friendly_name: "SABnzbd Disk"

    sensor.sabnzbd_disk_free:
      <<: *customize
      friendly_name: "SABnzbd Disk Free"

    sensor.sabnzbd_left:
      <<: *customize
      friendly_name: "SABnzbd Left"

    sensor.sabnzbd_queue:
      <<: *customize
      friendly_name: "SABnzbd Queue"

    sensor.sabnzbd_speed:
      <<: *customize
      friendly_name: "SABnzbd Speed"

    sensor.sabnzbd_status:
      <<: *customize
      friendly_name: "SABnzbd Status"

################################################
## Group
################################################

group:
  sabnzbd:
    control: hidden
    entities:
      - sensor.sabnzbd_disk
      - sensor.sabnzbd_disk_free
      - sensor.sabnzbd_left
      - sensor.sabnzbd_queue
      - sensor.sabnzbd_speed
      - sensor.sabnzbd_status

################################################
## Sensor
################################################

sensor:
  - platform: sabnzbd
    host: !secret sabnzbd_host
    api_key: !secret sabnzbd_api_key
    monitored_variables:
      - 'current_status'
      - 'speed'
      - 'queue_size'
      - 'queue_remaining'
      - 'disk_size'
      - 'disk_free'
