################################################################
## Packages / Secrets Container
################################################################

homeassistant:
  customize:
    packages.secrets: &customize
      haaska_hidden: true
      hidden: true
      homebridge_hidden: true
      package_file: 'packages/secrets_container.yaml'

    sensor.secrets:
      <<: *customize
      friendly_name: "Secrets"
      icon: mdi:file-lock
      secret_of_yours: !secret secret_of_yours
      secret_of_mine: !secret secret_of_mine

sensor:
  - platform: template
    sensors:
      secrets:
        value_template: "Secrets Container"
