################################################################
## Packages / Secrets Container
################################################################

sensor:
  - platform: template
    sensors:
      secrets:
        value_template: "{{ states.sensor.secrets.attributes|length - 3 }}"
