################################################################
## Packages / Secrets Container
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    packages.secrets: &customize
      haaska_hidden: true
      hidden: true
      homebridge_hidden: true
      package: 'secrets_container'

    sensor.secrets:
      <<: *customize
      friendly_name: "Secrets"
      icon: mdi:file-lock
      eventghost_url: !secret eventghost_url
      secret_of_yours: !secret secret_of_yours
      secret_of_mine: !secret secret_of_mine

################################################
## Sensor
################################################

sensor:
  - platform: template
    sensors:
      secrets:
        value_template: "Secrets Container"
