################################################################
## Package / Sensor Lights
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    packages.sensor_lights: &customize
      haaska_hidden: false
      homebridge_hidden: false
      package: 'sensor_lights'

    automation.laundry_room_motion:
      <<: *customize
      friendly_name: "Laundry Room Motion"
      icon: mdi:walk

    automation.kitchen_motion:
      <<: *customize
      friendly_name: "Kitchen Motion"
      icon: mdi:walk

    automation.master_bathroom_motion:
      <<: *customize
      friendly_name: "Bathroom Motion"
      icon: mdi:walk

    automation.master_bedroom_motion:
      <<: *customize
      friendly_name: "Bedroom Motion"
      icon: mdi:walk

    automation.garage_lighting:
      <<: *customize
      friendly_name: "Garage Lighting"
      icon: mdi:lightbulb

    automation.master_closet_lighting:
      <<: *customize
      friendly_name: "Closet Lighting"
      icon: mdi:lightbulb

    automation.parker_closet_lighting:
      <<: *customize
      friendly_name: "Parker Closet Lighting"
      icon: mdi:lightbulb

################################################
## Automation
################################################

automation:

  ################################################
  ## Motion Activated Lights
  ################################################

  - alias: laundry_room_motion
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: !secret binary_sensor_laundry_room_motion
        from: 'off'
        to: 'on'
      - platform: state
        entity_id: !secret binary_sensor_laundry_room_motion
        from: 'on'
        to: 'off'
        for: '00:04:00'
    action:
      - service: script.light_control
        data_template:
          entity_id: light.laundry_room
          state: "{{ trigger.to_state.state }}"

  - alias: kitchen_motion
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.kitchen_sensor
        from: 'off'
        to: 'on'
      - platform: state
        entity_id: binary_sensor.kitchen_sensor
        from: 'on'
        to: 'off'
        for: '00:04:00'
    action:
      - service: script.light_control
        data_template:
          entity_id: light.kitchen
          state: "{{ trigger.to_state.state }}"

  - alias: master_bathroom_motion
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.master_bathroom_sensor
        from: 'off'
        to: 'on'
      - platform: state
        entity_id: binary_sensor.master_bathroom_sensor
        from: 'on'
        to: 'off'
        for: '00:04:00'
    action:
      - service: script.light_control
        data_template:
          entity_id: light.master_bathroom
          state: "{{ trigger.to_state.state }}"

  - alias: master_bedroom_motion
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.master_bedroom_motion
        from: 'off'
        to: 'on'
      - platform: state
        entity_id: binary_sensor.master_bedroom_motion
        from: 'on'
        to: 'off'
        for: '00:04:00'
    action:
      - service: script.light_control
        data_template:
          entity_id: light.master_bedroom
          state: "{{ trigger.to_state.state }}"

  ################################################
  ## Door Activated Lights
  ################################################

  - alias: garage_lighting
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.garage_entry_contact
        from: 'off'
        to: 'on'
      - platform: state
        entity_id: binary_sensor.garage_entry_contact
        from: 'on'
        to: 'off'
        for: '00:05:00'
    action:
      - service: script.light_control
        data_template:
          entity_id: light.laundry_room, light.garage
          state: "{{ trigger.to_state.state }}"

  - alias: master_closet_lighting
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.closet_door_contact
    action:
      - service: script.light_control
        data_template:
          entity_id: light.master_closet
          state: "{{ trigger.to_state.state }}"

  - alias: parker_closet_lighting
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.parker_closet_door_contact
    action:
      - service: script.light_control
        data_template:
          entity_id: light.parker_closet
          state: "{{ trigger.to_state.state }}"
