################################################################
## Packages / Shower Mode
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'shower_mode'

      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

    ################################################
    ## Automation
    ################################################

    automation.shower_mode_disabled:
      friendly_name: "Shower Mode Disabled"
      hidden: true

    automation.shower_mode_enabled:
      friendly_name: "Shower Mode Enabled"
      hidden: true

    automation.toggle_shower_mode:
      friendly_name: "Toggle Shower Mode"
      hidden: true

    ################################################
    ## Input Boolean
    ################################################

    input_boolean.shower_mode:
      <<: *expose
      friendly_name: "Shower Mode"
      icon: mdi:water-pump

################################################
## Automation
################################################

automation:
  - alias: shower_mode_enabled
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: input_boolean.shower_mode
        from: 'off'
        to: 'on'
    action:
      - service: automation.turn_off
        data:
          entity_id: automation.master_bathroom_motion
      - service: script.light_control
        data_template:
          entity_id: light.master_bathroom
          state: 'on'
      - delay: '00:30:00'
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.shower_mode

  - alias: shower_mode_disabled
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: input_boolean.shower_mode
        from: 'on'
        to: 'off'
    action:
      - service: automation.turn_on
        data:
          entity_id: automation.master_bathroom_motion
      - condition: state
        entity_id: binary_sensor.master_bathroom_sensor
        state: 'off'
      - service: script.light_control
        data:
          entity_id: light.master_bathroom
          state: 'off'

  - alias: toggle_shower_mode
    initial_state: 'on'
    trigger:
      - platform: mqtt
        topic: dash-button/ziploc
        payload: 'active'
    action:
      - service: input_boolean.toggle
        data:
          entity_id: input_boolean.shower_mode

################################################
## Input Boolean
################################################

input_boolean:
  shower_mode:
    initial: off
