################################################################
## Packages / SmartThings
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'smartthings'

      exposed: &exposed
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

      hidden: &hidden
        <<: *customize
        hidden: true

    ################################################
    ## Binary Sensor
    ################################################

    binary_sensor.closet_door_contact:
      <<: *exposed
      device_class: opening
      friendly_name: "Closet Door"

    binary_sensor.garage_entry_contact:
      <<: *exposed
      device_class: opening
      friendly_name: "Garage Entry Door"

    binary_sensor.master_bedroom_motion:
      <<: *exposed
      device_class: motion
      friendly_name: "Master Bedroom Motion"

    binary_sensor.parker_closet_door_contact:
      <<: *exposed
      device_class: opening
      friendly_name: "Parker Closet Door"

    ################################################
    ## Sensor
    ################################################

    sensor.closet_door_battery:
      <<: *customize
      friendly_name: "Closet Door Battery"
      icon: mdi:battery

    sensor.closet_door_temperature:
      <<: *exposed
      friendly_name: "Closet Door Temperature"
      icon: mdi:thermometer

    sensor.garage_entry_battery:
      <<: *customize
      friendly_name: "Garage Entry Battery"
      icon: mdi:battery

    sensor.garage_entry_temperature:
      <<: *exposed
      friendly_name: "Garage Entry Temperature"
      icon: mdi:thermometer

    sensor.master_bedroom_battery:
      <<: *customize
      friendly_name: "Master Bedroom Battery"
      icon: mdi:battery

    sensor.master_bedroom_motion_temperature:
      <<: *exposed
      friendly_name: "Master Bedroom Temperature"
      icon: mdi:thermometer

    sensor.network_cabinet_battery:
      <<: *customize
      friendly_name: "Network Cabinet Battery"
      icon: mdi:battery

    sensor.network_cabinet_temperature:
      <<: *exposed
      friendly_name: "Network Cabinet Temperature"
      icon: mdi:thermometer

    sensor.parker_closet_door_battery:
      <<: *customize
      friendly_name: "Parker Closet Door Battery"
      icon: mdi:battery

    sensor.parker_closet_door_temperature:
      <<: *exposed
      friendly_name: "Parker Closet Door Temperature"
      icon: mdi:thermometer

    sensor.pepper_fan_power:
      <<: *customize
      friendly_name: "Pepper Fan Power"
      icon: mdi:flash

    ################################################
    ## Switch
    ################################################

    switch.pepper_fan:
      <<: *customize
      friendly_name: "Pepper Fan"
      icon: mdi:fan

################################################
## Binary Sensor
################################################

binary_sensor:
  - platform: mqtt
    name: closet_door_contact
    state_topic: smartthings/closet_door/contact
    payload_on: 'open'
    payload_off: 'closed'

  - platform: mqtt
    name: garage_entry_contact
    state_topic: smartthings/garage_entry/contact
    payload_on: 'open'
    payload_off: 'closed'

  - platform: mqtt
    name: master_bedroom_motion
    state_topic: smartthings/master_bedroom_motion/motion
    payload_on: 'active'
    payload_off: 'inactive'

  - platform: mqtt
    name: parker_closet_door_contact
    state_topic: smartthings/parker_closet_door/contact
    payload_on: 'open'
    payload_off: 'closed'

################################################
## Sensor
################################################

sensor:
  - platform: mqtt
    name: closet_door_battery
    state_topic: smartthings/closet_door/battery
    unit_of_measurement: '%'

  - platform: mqtt
    name: closet_door_temperature
    state_topic: smartthings/closet_door/temperature
    unit_of_measurement: '°F'

  - platform: mqtt
    name: garage_entry_battery
    state_topic: smartthings/garage_entry/battery
    unit_of_measurement: '%'

  - platform: mqtt
    name: garage_entry_temperature
    state_topic: smartthings/garage_entry/temperature
    unit_of_measurement: '°F'

  - platform: mqtt
    name: master_bedroom_battery
    state_topic: smartthings/master_bedroom_motion/battery
    unit_of_measurement: '%'

  - platform: mqtt
    name: master_bedroom_motion_temperature
    state_topic: smartthings/master_bedroom_motion/temperature
    unit_of_measurement: '°F'

  - platform: mqtt
    name: network_cabinet_battery
    state_topic: smartthings/network_cabinet/battery
    unit_of_measurement: '%'

  - platform: mqtt
    name: network_cabinet_temperature
    state_topic: smartthings/network_cabinet/temperature
    unit_of_measurement: '°F'

  - platform: mqtt
    name: parker_closet_door_battery
    state_topic: smartthings/parker_closet_door/battery
    unit_of_measurement: '%'

  - platform: mqtt
    name: parker_closet_door_temperature
    state_topic: smartthings/parker_closet_door/temperature
    unit_of_measurement: '°F'

  - platform: mqtt
    name: pepper_fan_power
    state_topic: smartthings/pepper_fan/power
    unit_of_measurement: 'W'

################################################
## Switch
################################################

switch:
  - platform: mqtt
    name: pepper_fan
    state_topic: smartthings/pepper_fan/switch
    command_topic: smartthings/pepper_fan/switch
    payload_on: 'on'
    payload_off: 'off'
    retain: true
