################################################################
## Packages / Speech
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'speech'

      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

    ################################################
    ## Script
    ################################################

    script.say:
      <<: *customize
      friendly_name: "Say"
      hidden: true
      icon: mdi:microphone

################################################
## Script
################################################

script:
  say:
    sequence:
      - service_template: >-
          tts.{{ platform|default('amazon_polly') }}_say
        data_template:
          entity_id: >-
            {{ entity_id|default('media_player.dining_room_home') }}
          message: >-
            {{ message }}
