################################################################
## Packages / Speech
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    packages.speech: &customize
      haaska_hidden: true
      hidden: true
      homebridge_hidden: true
      package: 'speech'

    script.say:
      <<: *customize
      friendly_name: "Say"
      icon: mdi:microphone

################################################
## Script
################################################

script:
  say:
    sequence:
      - service_template: >-
          tts.{{ platform|default('amazon_polly') }}_say
        data_template:
          entity_id: >-
            {{ entity_id|default('media_player.dining_room_home') }}
          message: >-
            {{ message }}
