################################################################
## Packages / System
################################################################

homeassistant:
  customize:
    packages.system: &customize
      haaska_hidden: true
      homebridge_hidden: true
      package_file: 'packages/system.yaml'

    packages.system_hidden: &customize_hidden
      <<: *customize
      hidden: true

    automation.startup_notification:
      <<: *customize
      friendly_name: "Startup Notification"
      icon: mdi:message-text

    automation.update_notification:
      <<: *customize
      friendly_name: "Update Notification"
      icon: mdi:message-text

    binary_sensor.system_ready:
      <<: *customize_hidden
      friendly_name: "System Ready"
      icon: mdi:flag-checkered

    group.system:
      <<: *customize
      friendly_name: "System"
      icon: mdi:settings-box

    sensor.date:
      <<: *customize
      friendly_name: "System Date"
      icon: mdi:calendar

    sensor.startup_time:
      <<: *customize
      friendly_name: "Startup Time"
      icon: mdi:clock-start

    sensor.time:
      <<: *customize
      friendly_name: "System Time"
      icon: mdi:clock

group:
  system:
    entities:
      - updater.updater
      - sensor.date
      - sensor.time
      - binary_sensor.system_ready
      - sensor.startup_time

automation:
  - alias: startup_notification
    trigger:
      - platform: homeassistant
        event: start
    action:
      - service: notify.telegram
        data:
          message: Home Assistant is now up and running.

  - alias: update_notification
    trigger:
      - platform: state
        entity_id: updater.updater
      - platform: homeassistant
        event: start
    condition:
      - condition: template
        value_template: >-
          {{ states('updater.updater') != 'unknown' }}
    action:
      - service: notify.telegram
        data_template:
          message: >-
            Home Assistant {{ states('updater.updater') }} is now available.

binary_sensor:
  - platform: template
    sensors:
      system_ready:
        entity_id: sensor.startup_time
        value_template: >-
          {{ states('sensor.startup_time') != 'unknown' }}

sensor:
  - platform: time_date
    display_options:
      - date
      - time

  - platform: template
    sensors:
      startup_time:
        entity_id: automation.startup_notification
        value_template: >-
          {{ (states.automation.startup_notification.attributes|default).last_triggered|default('unknown') }}
