################################################################
## Packages / System
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'system'

      contained: &contained
        <<: *customize
        haaska_hidden: true
        homebridge_hidden: true

      exposed: &exposed
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

      hidden: &hidden
        <<: *contained
        hidden: true

    ################################################
    ## Automation
    ################################################

    automation.startup_notification:
      <<: *contained
      friendly_name: "Startup Notification"
      icon: mdi:message-text

    automation.update_notification:
      <<: *contained
      friendly_name: "Update Notification"
      icon: mdi:message-text

    ################################################
    ## Group
    ################################################

    group.system:
      <<: *contained
      friendly_name: "System"
      icon: mdi:settings-box

    ################################################
    ## Sensor
    ################################################

    sensor.date:
      <<: *contained
      friendly_name: "System Date"
      icon: mdi:calendar

    sensor.ha_github_version:
      <<: *contained
      friendly_name: "GitHub Version"
      icon: mdi:github-box

    sensor.ha_pypi_version:
      <<: *contained
      friendly_name: "PyPi Version"
      icon: mdi:language-python

    sensor.ha_startup_time:
      <<: *contained
      friendly_name: "Startup Time"
      icon: mdi:clock-start

    sensor.ha_version:
      <<: *contained
      friendly_name: "Installed Version"
      icon: mdi:settings-box

    sensor.time:
      <<: *contained
      friendly_name: "System Time"
      icon: mdi:clock

################################################
## Group
################################################

group:
  system:
    control: hidden
    entities:
      - sensor.date
      - sensor.time
      - sensor.ha_startup_time
      - sensor.ha_version
      - sensor.ha_github_version
      - sensor.ha_pypi_version
      - sensor.vixen_vapors_cpu_load
      - switch.eventghost_blueiris
      - switch.eventghost_monitor

################################################
## Automation
################################################

automation:
  - alias: startup_notification
    initial_state: 'on'
    trigger:
      - platform: homeassistant
        event: start
      - platform: time
        seconds: '/5'
    action:
      - service: automation.turn_off
        data:
          entity_id: automation.startup_notification
      - service: notify.telegram
        data:
          message: "Home Assistant is now up and running."
      - service: automation.trigger
        data:
          entity_id: automation.update_global_brightness
      - service: shell_command.generate_graph

  - alias: update_notification
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: sensor.ha_github_version
      - platform: state
        entity_id: sensor.ha_pypi_version
    condition:
      - condition: template
        value_template: >-
          {{ trigger.to_state.state }}
      - condition: template
        value_template: >-
          {{ trigger.to_state.state != states('sensor.ha_version') }}
      - condition: template
        value_template: >-
          {{ trigger.to_state.state != 'unknown' }}
    action:
      - service: notify.telegram
        data_template:
          message: >-
            Home Assistant {{ trigger.to_state.state }} is now available on {{ trigger.to_state.name.split(' ')[0] }}.

################################################
## Sensor
################################################

sensor:
  - platform: time_date
    display_options:
      - date
      - time

  - platform: template
    sensors:
      ha_startup_time:
        entity_id: automation.startup_notification
        value_template: >-
          {{ as_timestamp((states.automation.startup_notification.attributes|default).last_triggered|default(None))|timestamp_local or 'unknown' }}

  - platform: command_line
    name: ha_version
    command: >-
      cat $HASS_CONFIG/.HA_VERSION
    scan_interval: 86400

  - platform: rest
    name: ha_github_version
    resource: 'https://api.github.com/repos/home-assistant/home-assistant/releases/latest'
    headers:
      accept: application/vnd.github.v3+json
      content-type: application/json
      user-agent: home-assistant/rest-sensor
    value_template: >-
      {{ value_json.tag_name if value_json.tag_name.split('.')|length != 2 else value_json.tag_name ~ '.0' }}
    scan_interval: 1800

  - platform: rest
    name: ha_pypi_version
    resource: 'https://pypi.python.org/pypi/homeassistant/json'
    value_template: >-
      {{ value_json.info.version }}
    scan_interval: 1800
