################################################################
## Packages / System
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    packages.system: &customize
      haaska_hidden: true
      homebridge_hidden: true
      package: 'system'

    packages.system_hidden: &customize_hidden
      <<: *customize
      hidden: true

    automation.startup_notification:
      <<: *customize
      friendly_name: "Startup Notification"
      icon: mdi:message-text

    automation.update_notification:
      <<: *customize
      friendly_name: "Update Notification"
      icon: mdi:message-text

    binary_sensor.system_ready:
      <<: *customize_hidden
      friendly_name: "System Ready"
      icon: mdi:flag-checkered

    group.system:
      <<: *customize
      friendly_name: "System"
      icon: mdi:settings-box

    sensor.date:
      <<: *customize
      friendly_name: "System Date"
      icon: mdi:calendar

    sensor.ha_github_version:
      <<: *customize
      friendly_name: "GitHub Version"
      icon: mdi:github-box

    sensor.ha_pypi_version:
      <<: *customize
      friendly_name: "PyPi Version"
      icon: mdi:language-python

    sensor.ha_startup_time:
      <<: *customize
      friendly_name: "Startup Time"
      icon: mdi:clock-start

    sensor.ha_version:
      <<: *customize
      friendly_name: "Installed Version"
      icon: mdi:settings-box

    sensor.time:
      <<: *customize
      friendly_name: "System Time"
      icon: mdi:clock

################################################
## Group
################################################

group:
  system:
    control: hidden
    entities:
      - sensor.date
      - sensor.time
      - binary_sensor.system_ready
      - sensor.ha_startup_time
      - sensor.ha_version
      - sensor.ha_github_version
      - sensor.ha_pypi_version
      - switch.eventghost_blueiris
      - switch.eventghost_monitor

################################################
## Automation
################################################

automation:
  - alias: startup_notification
    initial_state: 'on'
    trigger:
      - platform: homeassistant
        event: start
      - platform: event
        event_type: zwave.network_ready
    action:
      - service: automation.turn_off
        data:
          entity_id: automation.startup_notification
      - service: notify.telegram
        data:
          message: "Home Assistant is now up and running."

  - alias: update_notification
    initial_state: 'on'
    trigger:
      - platform: homeassistant
        event: start
      - platform: event
        event_type: zwave.network_ready
      - platform: state
        entity_id: sensor.ha_github_version
      - platform: state
        entity_id: sensor.ha_pypi_version
    condition:
      - condition: or
        conditions:
          - condition: template
            value_template: >-
              {{ states('sensor.ha_github_version') != states('sensor.ha_version') }}
          - condition: template
            value_template: >-
              {{ states('sensor.ha_pypi_version') != states('sensor.ha_version') }}
    action:
      - service: notify.telegram
        data_template:
          message: >-
            {% if trigger.platform == 'state' %}
              Home Assistant {{ trigger.to_state.state }} is now available on {{ trigger.to_state.name.split(' ')[0] }}.
            {% elif states('sensor.ha_pypi_version') != states('sensor.ha_version') %}
              Home Assistant {{ states('sensor.ha_pypi_version') }} is now available on PyPi.
            {% else %}
              Home Assistant {{ states('sensor.ha_github_version') }} is now available on GitHub.
            {% endif %}

################################################
## Binary Sensor
################################################

binary_sensor:
  - platform: template
    sensors:
      system_ready:
        entity_id: sensor.ha_startup_time
        value_template: >-
          {{ states('sensor.ha_startup_time') != 'unknown' }}

################################################
## Sensor
################################################

sensor:
  - platform: time_date
    display_options:
      - date
      - time

  - platform: template
    sensors:
      ha_startup_time:
        entity_id: automation.startup_notification
        value_template: >-
          {{ as_timestamp((states.automation.startup_notification.attributes|default).last_triggered|default(None))|timestamp_custom("%b %d %X") or 'unknown' }}

  - platform: command_line
    name: ha_version
    command: >-
      cat $HASS_CONFIG/.HA_VERSION
    scan_interval: 86400

  - platform: rest
    name: ha_github_version
    resource: 'https://api.github.com/repos/home-assistant/home-assistant/releases/latest'
    headers:
      accept: application/vnd.github.v3+json
      content-type: application/json
      user-agent: home-assistant/rest-sensor
    value_template: >-
      {{ value_json.tag_name }}
    scan_interval: 1800

  - platform: rest
    name: ha_pypi_version
    resource: 'https://pypi.python.org/pypi/homeassistant/json'
    value_template: >-
      {{ value_json.info.version }}
    scan_interval: 1800
