################################################################
## Packages / Telegram
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'telegram'

      exposed: &exposed
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

      hidden: &hidden
        <<: *customize
        hidden: true

    ################################################
    ## Automation
    ################################################

    automation.telegram_restart:
      <<: *customize
      friendly_name: "Telegram: Restart"
      icon: mdi:power

automation:
  - alias: telegram_restart
    trigger:
      - platform: event
        event_type: telegram_command
        event_data:
          command: '/restart'
    action:
      - service: notify.telegram
        data:
          message: "Restarting Home Assistant, please wait..."
      - service: script.restart_hass

  - alias: telegram_roll
    trigger:
      - platform: event
        event_type: telegram_command
        event_data:
          command: '/roll'
    action:
      - service: notify.telegram
        data_template:
          message: >-
            {% set sides = (trigger.event.data.args|default)[0]|default(6) %}
            I rolled a {{ sides|string ~ '-sided die' if sides != 6 else 'die' }} and got {{ range(1, sides + 1)|random }}.

telegram_bot:
  platform: webhooks
  api_key: !secret telegram_api_key
  allowed_chat_ids:
    - !secret telegram_chat_id

notify:
  - platform: telegram
    name: telegram
    chat_id: !secret telegram_chat_id
