################################################################
## Packages / TTS Alerts
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    packages.tts_alerts: &customize
      haaska_hidden: true
      homebridge_hidden: true
      package: 'tts_alerts'

    automation.alert_triggered:
      <<: *customize
      friendly_name: Alert Triggered

################################################
## Automation
################################################

automation:
  - alias: alert_triggered
    # initial_state: 'on'
    trigger:
      - platform: event
        event_type: call_service
        event_data:
          domain: notify
          service: tts_alerts
    action:
      - service: notify.syslog
        data_template:
          message: >-
            {{ trigger|tojson(2) }}
      - service: script.say
        data_template:
          message: >-
            {% set alert_name = trigger.event.data.service_data.message %}
            {% set alert_map = {
              'garage_door_open': 'The garage door is open.',
              'Garage Door Open': 'Fix the garage door alert.'
            } %}
            {{ alert_map[alert_name]|default(alert_name) }}

################################################
## Notify
################################################

notify:
  - platform: file
    name: tts_alerts
    filename: tts_alerts.log
    timestamp: true
