################################################################
## Packages / TTS Alerts
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    packages.tts_alerts: &customize
      haaska_hidden: true
      homebridge_hidden: true
      package: 'tts_alerts'

    automation.alert_triggered:
      <<: *customize
      friendly_name: Alert Triggered

################################################
## Automation
################################################

automation:
  - alias: alert_triggered
    initial_state: 'on'
    trigger:
      - platform: event
        event_type: call_service
        event_data:
          domain: notify
          service: tts_alerts
    action:
      - service: script.say
        data_template:
          message: >-
            {% set entity_id = trigger.event.data.service_data.message %}
            {{ (states.alert[entity_id].attributes|default).speech|default(entity_id|replace('_', ' ')) }}

################################################
## Notify
################################################

notify:
  - platform: file
    name: tts_alerts
    filename: tts_alerts.log
    timestamp: true
