################################################################
## Packages / UPS (Battery Backup)
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'ups'

      exposed: &exposed
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

      hidden: &hidden
        <<: *customize
        hidden: true

    ################################################
    ## Group
    ################################################

    group.ups:
      <<: *customize
      friendly_name: "Battery Backup"
      icon: mdi:car-battery

    ################################################
    ## Sensor
    ################################################

    sensor.ups_battery:
      <<: *customize
      friendly_name: "UPS Battery"

    sensor.ups_input_voltage:
      <<: *customize
      friendly_name: "UPS Input Voltage"

    sensor.ups_last_self_test:
      <<: *customize
      friendly_name: "UPS Last Self Test"

    sensor.ups_load:
      <<: *customize
      friendly_name: "UPS Load"

    sensor.ups_nominal_input_voltage:
      <<: *customize
      friendly_name: "UPS Nominal Input Voltage"

    sensor.ups_nominal_output_power:
      <<: *customize
      friendly_name: "UPS Nominal Output Power"

    sensor.ups_output_voltage:
      <<: *customize
      friendly_name: "UPS Output Voltage"

    sensor.ups_startup_time:
      <<: *customize
      friendly_name: "UPS Startup Time"

    sensor.ups_status:
      <<: *customize
      friendly_name: "UPS Status"

    sensor.ups_status_date:
      <<: *customize
      friendly_name: "UPS Status Date"

    sensor.ups_time_left:
      <<: *customize
      friendly_name: "UPS Time Left"

    sensor.ups_time_on_battery:
      <<: *customize
      friendly_name: "UPS Time on Battery"

    sensor.ups_total_time_on_battery:
      <<: *customize
      friendly_name: "UPS Total Time on Battery"

    sensor.ups_transfer_count:
      <<: *customize
      friendly_name: "UPS Transfer Count"

    sensor.ups_transfer_from_battery:
      <<: *customize
      friendly_name: "UPS Transfer from Battery"

    sensor.ups_transfer_to_battery:
      <<: *customize
      friendly_name: "UPS Transfer to Battery"

################################################
## Group
################################################

group:
  ups:
    control: hidden
    entities:
      - sensor.ups_battery
      - sensor.ups_input_voltage
      - sensor.ups_last_self_test
      - sensor.ups_load
      - sensor.ups_nominal_input_voltage
      - sensor.ups_nominal_output_power
      - sensor.ups_output_voltage
      - sensor.ups_startup_time
      - sensor.ups_status
      - sensor.ups_status_date
      - sensor.ups_time_left
      - sensor.ups_time_on_battery
      - sensor.ups_total_time_on_battery
      - sensor.ups_transfer_count
      - sensor.ups_transfer_from_battery
      - sensor.ups_transfer_to_battery

################################################
## APCUPSd
################################################

apcupsd:
  host: !secret apcupsd_host
  port: !secret apcupsd_port

################################################
## Sensor
################################################

sensor:
  - platform: apcupsd
    resources:
      - bcharge
      - cumonbatt
      - date
      - linev
      - loadpct
      - nominv
      - nompower
      - numxfers
      - outputv
      - selftest
      - starttime
      - status
      - timeleft
      - tonbatt
      - xoffbatt
      - xonbatt
