################################################################
## Packages / Web Power Switch
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    packages.web_power_switch: &customize
      haaska_hidden: true
      homebridge_hidden: true
      package: 'web_power_switch'

    group.web_power_switch:
      <<: *customize
      friendly_name: "Web Power Switch"
      icon: mdi:power-settings

    switch.rack_cable_modem:
      <<: *customize
      friendly_name: "Cable Modem"
      icon: mdi:switch

    switch.rack_media_server:
      <<: *customize
      friendly_name: "Media Server"
      icon: mdi:filmstrip

    switch.rack_ikea_tradfri:
      <<: *customize
      friendly_name: "IKEA Tradfri"
      icon: mdi:lightbulb

    switch.rack_printer:
      <<: *customize
      friendly_name: "Printer"
      icon: mdi:printer

    switch.rack_projector:
      <<: *customize
      friendly_name: "Projector"
      icon: mdi:projector

    switch.rack_router:
      <<: *customize
      friendly_name: "Router"
      icon: mdi:router-wireless

    switch.rack_usb_panel:
      <<: *customize
      friendly_name: "USB Panel"
      icon: mdi:usb

    switch.rack_yamaha_avr:
      <<: *customize
      friendly_name: "Yamaha AVR"
      icon: mdi:music-box

################################################
## Group
################################################

group:
  web_power_switch:
    control: hidden
    entities:
      - switch.rack_cable_modem
      - switch.rack_media_server
      - switch.rack_ikea_tradfri
      - switch.rack_printer
      - switch.rack_projector
      - switch.rack_router
      - switch.rack_usb_panel
      - switch.rack_yamaha_avr

################################################
## Switch
################################################

switch:
  - platform: digitalloggers
    name: rack
    host: !secret digitalloggers_host
    password: !secret digitalloggers_password
