################################################################
## Packages / Xbox Live
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'xbox_live'

      contained: &contained
        <<: *customize
        haaska_hidden: true
        homebridge_hidden: true

      exposed: &exposed
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

      hidden: &hidden
        <<: *contained
        hidden: true

    ################################################
    ## Sensor
    ################################################

    sensor.gremlinjku:
      <<: *customize
      friendly_name: "GremlinJKU"

################################################
## Sensor
################################################

sensor:
  - platform: xbox_live
    api_key: !secret xbox_live_api_key
    xuid:
      - !secret xbox_live_xuid
