################################################################
## Packages / Xiaomi
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'xiaomi'

      exposed: &exposed
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

      hidden: &hidden
        <<: *customize
        hidden: true

    ################################################
    ## Secrets
    ################################################

    !secret binary_sensor_doorbell:
      <<: *customize
      friendly_name: "Doorbell"
      device_class: sound

    !secret binary_sensor_laundry_room_motion:
      <<: *customize
      friendly_name: "Laundry Room Motion"
      device_class: motion

    !secret binary_sensor_xiaomi_button:
      <<: *hidden
      friendly_name: "Xiaomi Switch"
      icon: mdi:gamepad

    !secret light_gateway_light:
      <<: *exposed
      friendly_name: "Gateway Light"
      persistent: true

    !secret sensor_gateway_lux:
      <<: *customize
      friendly_name: "Gateway Lux"

    !secret switch_xiaomi_plug:
      <<: *hidden
      friendly_name: "Xiaomi Plug"
      icon: mdi:power-plug

    ################################################
    ## Input Slider
    ################################################

    input_slider.xiaomi_ringtone_volume:
      <<: *customize
      friendly_name: "Xiaomi Ringtone Volume"

    ################################################
    ## Script
    ################################################

    script.xiaomi_ringtone:
      <<: *hidden
      friendly_name: "Xiaomi Ringtone"

################################################
## Xiaomi
################################################

xiaomi:
  gateways:
    - sid: !secret xiaomi_gateway_sid
      key: !secret xiaomi_gateway_key

################################################
## Input Slider
################################################

input_slider:
  xiaomi_ringtone_volume:
    initial: 1
    min: 1
    max: 100
    step: 1

################################################
## Script
################################################

script:
  xiaomi_ringtone:
    sequence:
      - service: xiaomi.play_ringtone
        data_template:
          ringtone_id: "{{ ringtone|default(10000) }}"
          ringtone_vol: "{{ volume|default(states('input_slider.xiaomi_ringtone_volume')|int(100)) }}"
          gw_sid: >-
            {% if gateway is defined %}
              {{ gateway }}
            {% else %}
              {% for light in states.light if 'gateway_light_' in light.entity_id %}
                {{ light.entity_id|replace('light.gateway_light_', '') if loop.index == 1 }}
              {% endfor %}
            {% endif %}
