################################################################
## Packages / Xiaomi
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    packages.xiaomi: &customize
      package: 'xiaomi'

    packages.xiaomi_exposed: &customize_exposed
      <<: *customize
      haaska_hidden: false
      homebridge_hidden: false

    packages.xiaomi_contained: &customize_contained
      <<: *customize
      haaska_hidden: true
      homebridge_hidden: true

    !secret binary_sensor_doorbell:
      <<: *customize_contained
      friendly_name: "Doorbell"
      device_class: sound

    !secret binary_sensor_laundry_room_motion:
      <<: *customize_contained
      friendly_name: "Laundry Room Motion"
      device_class: motion

    !secret binary_sensor_xiaomi_button:
      <<: *customize_contained
      friendly_name: "Xiaomi Switch"
      hidden: true
      icon: mdi:gamepad

    !secret light_gateway_light:
      <<: *customize_exposed
      friendly_name: "Gateway Light"
      persistent: true

    !secret sensor_gateway_lux:
      <<: *customize_contained
      friendly_name: "Gateway Lux"

    !secret switch_xiaomi_plug:
      <<: *customize_contained
      friendly_name: "Xiaomi Plug"
      hidden: true
      icon: mdi:power-plug

    input_slider.xiaomi_ringtone_volume:
      <<: *customize_contained
      friendly_name: "Xiaomi Ringtone Volume"

    script.xiaomi_ringtone:
      <<: *customize_contained
      friendly_name: "Xiaomi Ringtone"
      hidden: true

################################################
## Xiaomi
################################################

xiaomi:
  gateways:
    - sid: !secret xiaomi_gateway_sid
      key: !secret xiaomi_gateway_key

################################################
## Input Slider
################################################

input_slider:
  xiaomi_ringtone_volume:
    initial: 1
    min: 1
    max: 100
    step: 1

################################################
## Script
################################################

script:
  xiaomi_ringtone:
    sequence:
      - service: xiaomi.play_ringtone
        data_template:
          ringtone_id: "{{ ringtone|default(10000) }}"
          ringtone_vol: "{{ volume|default(states('input_slider.xiaomi_ringtone_volume')|int(100)) }}"
          gw_sid: >-
            {% if gateway is defined %}
              {{ gateway }}
            {% else %}
              {% for light in states.light if 'gateway_light_' in light.entity_id %}
                {{ light.entity_id|replace('light.gateway_light_', '') if loop.index == 1 }}
              {% endfor %}
            {% endif %}
