################################################################
## Packages / Zones
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'zones'

      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

    ################################################
    ## Zone
    ################################################

    zone.home:
      <<: *customize
      friendly_name: "Home"

    zone.office:
      <<: *customize
      friendly_name: "Office"
      icon: mdi:city

    zone.parents:
      <<: *customize
      friendly_name: "Parents"
      icon: mdi:cow

################################################
## Zone
################################################

zone:
  - name: office
    latitude: !secret office_latitude
    longitude: !secret office_longitude

  - name: parents
    latitude: !secret parents_latitude
    longitude: !secret parents_longitude
