################################################################
## Packages / Z-Wave Remotes
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    packages.zwave_remotes: &customize
      haaska_hidden: true
      hidden: true
      homebridge_hidden: true
      package: 'zwave_remotes'

    script.blue_iris_remote_1_click:
      <<: *customize
      friendly_name: "Toggle Monitor Power"

    script.blue_iris_remote_2_click:
      <<: *customize
      friendly_name: "Blue Iris: Toggle Focus"

    script.blue_iris_remote_3_click:
      <<: *customize
      friendly_name: "Blue Iris: Previous Camera"

    script.blue_iris_remote_3_hold:
      <<: *customize
      friendly_name: "Blue Iris: Show All Cameras"

    script.blue_iris_remote_4_click:
      <<: *customize
      friendly_name: "Blue Iris: Next Camera"

    script.blue_iris_remote_4_hold:
      <<: *customize
      friendly_name: "Blue Iris: Cycle Cameras"

################################################
## Script
################################################

script:
  ################################################
  ## Global Handler
  ################################################

  # minimote_button:
  #   sequence:
  #     - service: notify.syslog
  #       data_template:
  #         message: >-
  #           event_type: {{ event_type }}
  #           origin: {{ origin }}
  #           time_fired: {{ time_fired }}
  #           entity_id: {{ entity_id }}
  #           object_id: {{ object_id }}
  #           scene_id: {{ scene_id }}
  #           remote: {{ remote }}
  #           button: {{ button }}
  #           action: {{ action }}

  ################################################
  ## Blue Iris Remote
  ################################################

  blue_iris_remote_1_click:
    sequence:
      - service: switch.toggle
        data:
          entity_id: switch.eventghost_monitor

  blue_iris_remote_2_click:
    sequence:
      - service: switch.toggle
        data:
          entity_id: switch.eventghost_blueiris

  blue_iris_remote_3_click:
    sequence:
      - service: shell_command.curl
        data_template:
          method: post
          url: "{{ states.sensor.secrets.attributes.eventghost_url }}"
          payload:
            method: TriggerEvent
            args:
              - BlueIris.PreviousCam

  blue_iris_remote_3_hold:
    sequence:
      - service: shell_command.curl
        data_template:
          method: post
          url: "{{ states.sensor.secrets.attributes.eventghost_url }}"
          payload:
            method: TriggerEvent
            args:
              - BlueIris.AllCams

  blue_iris_remote_4_click:
    sequence:
      - service: shell_command.curl
        data_template:
          method: post
          url: "{{ states.sensor.secrets.attributes.eventghost_url }}"
          payload:
            method: TriggerEvent
            args:
              - BlueIris.NextCam

  blue_iris_remote_4_hold:
    sequence:
      - service: shell_command.curl
        data_template:
          method: post
          url: "{{ states.sensor.secrets.attributes.eventghost_url }}"
          payload:
            method: TriggerEvent
            args:
              - BlueIris.Cycle
