################################################################
## Packages / Z-Wave Remotes
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    packages.zwave_remotes: &customize
      haaska_hidden: true
      homebridge_hidden: true
      package: 'zwave_remotes'

################################################
## Script
################################################

script:
  minimote_button:
    sequence:
      - service: notify.syslog
        data_template:
          message: >-
            event_type: {{ event_type }}
            origin: {{ origin }}
            time_fired: {{ time_fired }}
            entity_id: {{ entity_id }}
            object_id: {{ object_id }}
            scene_id: {{ scene_id }}
            remote: {{ remote }}
            button: {{ button }}
            action: {{ action }}

  dining_room_remote_1_click:
    sequence:
      - service: notify.syslog
        data:
          message: "button 1 click handler"
#       - service: light.turn_on
#         data:
#           entity_id: light.living_room
#           brightness: 255

  dining_room_remote_1_hold:
    sequence:
      - service: notify.syslog
        data:
          message: "button 1 hold handler"
#       - service: switch.turn_on
#         data:
#           entity_id: switch.apple_tv

  dining_room_remote_2_click:
    sequence:
      - service: notify.syslog
        data:
          message: "button 2 click handler"
#       - service: light.turn_on
#         data:
#           entity_id: light.dining_room
#           brightness: 255

  dining_room_remote_3_click:
    sequence:
      - service: notify.syslog
        data:
          message: "button 3 click handler"
#       - service: light.turn_off
#         data:
#           entity_id: light.living_room

  dining_room_remote_3_hold:
    sequence:
      - service: notify.syslog
        data:
          message: "button 3 hold handler"
#       - service: switch.turn_off
#         data:
#           entity_id: switch.apple_tv

  dining_room_remote_4_click:
    sequence:
      - service: notify.syslog
        data:
          message: "button 4 click handler"
#       - service: light.turn_off
#         data:
#           entity_id: light.dining_room
