################################################################
## Packages / Z-Wave
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    packages.zwave: &customize
      package: 'zwave'

    packages.zwave_exposed: &customize_exposed
      <<: *customize
      haaska_hidden: false
      homebridge_hidden: false

    packages.zwave_contained: &customize_contained
      <<: *customize
      haaska_hidden: true
      homebridge_hidden: true

    !secret binary_sensor_front_door:
      <<: *customize_contained
      friendly_name: "Front Door Sensor"
      device_class: opening

    !secret binary_sensor_kitchen_motion:
      <<: *customize_contained
      friendly_name: "Kitchen Motion"
      device_class: motion

    !secret binary_sensor_master_bathroom_motion:
      <<: *customize_contained
      friendly_name: "Master Bathroom Motion"
      device_class: motion

    input_select.siren_sound:
      <<: *customize_contained
      friendly_name: "Siren Sound"

    !secret lock_front_door:
      <<: *customize_exposed
      friendly_name: "Front Door"

    script.siren_autostop_120s:
      <<: *customize_contained
      friendly_name: "Siren Autostop 120s"

    script.siren_autostop_30s:
      <<: *customize_contained
      friendly_name: "Siren Autostop 30s"

    script.siren_autostop_60s:
      <<: *customize_contained
      friendly_name: "Siren Autostop 60s"

    script.siren_autostop_never:
      <<: *customize_contained
      friendly_name: "Siren Autostop Never"

    script.siren_mode_all:
      <<: *customize_contained
      friendly_name: "Siren Mode All"

    script.siren_mode_siren:
      <<: *customize_contained
      friendly_name: "Siren Mode Siren"

    script.siren_mode_strobe:
      <<: *customize_contained
      friendly_name: "Siren Mode Strobe"

    !secret sensor_front_door_access_control:
      <<: *customize_contained
      friendly_name: "Front Door Access Control"
      hidden: true

    !secret sensor_kitchen_luminance:
      <<: *customize_contained
      friendly_name: "Kitchen Luminance"
      hidden: true
      icon: mdi:theme-light-dark

    !secret sensor_kitchen_moisture:
      <<: *customize_exposed
      friendly_name: "Kitchen Moisture"
      device_class: moisture
      icon: mdi:water-percent

    !secret sensor_kitchen_humidity:
      <<: *customize_exposed
      friendly_name: "Kitchen Humidity"
      icon: mdi:water-percent

    !secret sensor_kitchen_temperature:
      <<: *customize_exposed
      friendly_name: "Kitchen Temperature"
      icon: mdi:thermometer

    !secret sensor_master_bathroom_luminance:
      <<: *customize_contained
      friendly_name: "Master Bathroom Luminance"
      hidden: true
      icon: mdi:theme-light-dark

    !secret sensor_master_bathroom_humidity:
      <<: *customize_exposed
      friendly_name: "Master Bathroom Humidity"
      icon: mdi:water-percent

    !secret sensor_master_bathroom_temperature:
      <<: *customize_exposed
      friendly_name: "Master Bathroom Temperature"
      icon: mdi:thermometer

  customize_domain:
    zwave:
      <<: *customize
      hidden: true

################################################
## Z-Wave
################################################

zwave:
  config_path: !secret zwave_config_path
  usb_path: !secret zwave_usb_path
  device_config: !include ../zwave_device_config.yaml

################################################
## Input Select
################################################

input_select:
  siren_sound:
    initial: "Sound 1 - Low Volume"
    options:
      - "Sound 1 - Low Volume"
      - "Sound 1 - Mid Volume"
      - "Sound 1 - High Volume"
      - "Sound 2 - Low Volume"
      - "Sound 2 - Mid Volume"
      - "Sound 2 - High Volume"
      - "Sound 3 - Low Volume"
      - "Sound 3 - Mid Volume"
      - "Sound 3 - High Volume"
      - "Sound 4 - Low Volume"
      - "Sound 4 - Mid Volume"
      - "Sound 4 - High Volume"
      - "Sound 5 - Low Volume"
      - "Sound 5 - Mid Volume"
      - "Sound 5 - High Volume"

################################################
## Script
################################################

script:
  siren_mode_all:
    sequence:
      - service: zwave.set_config_parameter
        data:
          node_id: 16
          parameter: 0
          value: 0

  siren_mode_siren:
    sequence:
      - service: zwave.set_config_parameter
        data:
          node_id: 16
          parameter: 0
          value: 1

  siren_mode_strobe:
    sequence:
      - service: zwave.set_config_parameter
        data:
          node_id: 16
          parameter: 0
          value: 2

  siren_autostop_30s:
    sequence:
      - service: zwave.set_config_parameter
        data:
          node_id: 16
          parameter: 1
          value: 0

  siren_autostop_60s:
    sequence:
      - service: zwave.set_config_parameter
        data:
          node_id: 16
          parameter: 1
          value: 1

  siren_autostop_120s:
    sequence:
      - service: zwave.set_config_parameter
        data:
          node_id: 16
          parameter: 1
          value: 2

  siren_autostop_never:
    sequence:
      - service: zwave.set_config_parameter
        data:
          node_id: 16
          parameter: 1
          value: 3
