################################################################
## Packages / Z-Wave
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'zwave'

      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

    ################################################
    ## Binary Sensor
    ################################################

    binary_sensor.front_door_sensor:
      <<: *customize
      friendly_name: "Front Door Sensor"
      device_class: opening

    binary_sensor.kitchen_sensor:
      <<: *customize
      friendly_name: "Kitchen Motion"
      device_class: motion

    binary_sensor.master_bathroom_sensor:
      <<: *customize
      friendly_name: "Master Bathroom Motion"
      device_class: motion

    ################################################
    ## Input Select
    ################################################

    input_select.siren_sound:
      <<: *customize
      friendly_name: "Siren Sound"

    ################################################
    ## Lock
    ################################################

    lock.front_door_locked:
      <<: *expose
      friendly_name: "Front Door"

    ################################################
    ## Sensor
    ################################################

    sensor.front_door_access_control:
      <<: *customize
      friendly_name: "Front Door Access Control"
      hidden: true

    sensor.kitchen_luminance:
      <<: *customize
      friendly_name: "Kitchen Luminance"
      hidden: true
      icon: mdi:theme-light-dark

    sensor.kitchen_moisture:
      <<: *expose
      friendly_name: "Kitchen Moisture"
      device_class: moisture
      icon: mdi:water-percent

    sensor.kitchen_relative_humidity:
      <<: *expose
      friendly_name: "Kitchen Humidity"
      icon: mdi:water-percent

    sensor.kitchen_temperature:
      <<: *expose
      friendly_name: "Kitchen Temperature"
      icon: mdi:thermometer

    sensor.master_bathroom_luminance:
      <<: *customize
      friendly_name: "Master Bathroom Luminance"
      hidden: true
      icon: mdi:theme-light-dark

    sensor.master_bathroom_relative_humidity:
      <<: *expose
      friendly_name: "Master Bathroom Humidity"
      icon: mdi:water-percent

    sensor.master_bathroom_temperature:
      <<: *expose
      friendly_name: "Master Bathroom Temperature"
      icon: mdi:thermometer

  ################################################
  ## Customize Domain
  ################################################

  customize_domain:
    zwave:
      <<: *customize
      # hidden: true

################################################
## Z-Wave
################################################

zwave:
  usb_path: !secret zwave_usb_path
  network_key: !secret zwave_network_key
  device_config: !include ../zwave_device_config.yaml
